Repository knative/client, pull requests merged in 2019-11, with the labels that each got.

#469 fix English typo: 'an equally' instead of 'a equally'
  pkg/kn/commands/plugin/verifier.go
  pkg/kn/commands/plugin/verifier_windows.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#472 Add service account info into service describe
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
Labels: approved, cla: yes, lgtm, size/S

#475 Human-readable revision describe
  docs/cmd/kn_revision_describe.md
  pkg/kn/commands/describe.go
  pkg/kn/commands/describe_test.go
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/describe_test.go
  pkg/kn/commands/service/describe.go
  pkg/printers/prefixwriter.go
  pkg/serving/revision_template.go
  pkg/serving/revision_template_test.go
  test/e2e/basic_workflow_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#460 fix(service describe): Clarify URL labels
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, size/XS

#393 Add support for envFrom and volumeMounts
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/flags/traffic.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/util/orderedmap.go
  pkg/util/orderedmap_test.go
  pkg/util/parsing_helper.go
  pkg/util/parsing_helper_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#483 chore: Prep for v0.10.0 release
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/S

#486 Improve error message
  pkg/kn/commands/service/configuration_edit_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#488 chore: Update testing infrastructure
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/performance-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#493 chore: Update to k8s 1.15.5 and fixing go.sum error
  go.mod
  go.sum
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/json.go
  vendor/k8s.io/apimachinery/pkg/util/json/json.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#481 removes remaining references to 'lookup-plugins-in-path'
  pkg/kn/commands/plugin/handler_test.go
  pkg/kn/commands/plugin/plugin.go
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#478 Add completion to help message
  docs/cmd/kn.md
  docs/cmd/kn_completion.md
  pkg/kn/commands/completion/completion.go
Labels: approved, cla: yes, lgtm, size/M

#489 Separates cross compile in hack/build.sh from default flow
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/S

#494 chore: Add some clarification to the pull request template for where to put CHANGELOG entries
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/XS

#492 Support multiple NAMEs on service delete
  CHANGELOG.adoc
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/delete_test.go
  test/e2e/service_test.go
Labels: approved, cla: yes, lgtm, size/M

#502 chore(docs): Updates basic workflow doc
  docs/workflows/basic.md
Labels: approved, cla: yes, lgtm, size/M

#506 Uses BYO revision names for traffic splitting e2e tests
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/L

#503 Update vendor/knative.dev/test-infra
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#484 Shorten the --log-http Authorization mask value
  pkg/util/logging_http_transport.go
  pkg/util/logging_http_transport_test.go
Labels: approved, cla: yes, lgtm, size/XS

#495 chore: Add version information of eventing
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
Labels: approved, cla: yes, lgtm, size/S

#508 Verify service status before verifying traffic targets
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/S

#501 chore(e2e): Run e2e against latest released serving version v0.10.0
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#509 chore(build): Spacing fix for newer iTerm (>=3.3.7)
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/M

#491 In waiting for ready, watch falls back to polling.
  go.sum
  pkg/serving/v1alpha1/client.go
  pkg/wait/poll_watcher.go
  pkg/wait/poll_watcher_test.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#514 Add common codes for sources client
  pkg/eventing/sources/v1alpha1/client.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/commands/testing_helper_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_containersource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_cronjobsource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#522 Remove explicit flag parsing so that it works with go1.13
  test/e2e/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#524 fix(e2e): Removes workaround for ensuring LCR=LRR at client side
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/S

#525 tests: Avoid downloading deps in unit tests
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#527 tests: Use mock kn client tests for service list and delete
  pkg/kn/commands/service/delete_mock_test.go
  pkg/kn/commands/service/list_mock_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#523 fix(e2e): Removes explicit timeout flag in smoke tests
  test/e2e-smoke-tests.sh
Labels: approved, cla: yes, lgtm, size/XS
