Repository knative/client, pull requests merged in 2019-06, with the labels that each got.

#154 Update test-infra to the latest version
  go.mod
  go.sum
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#155 fix(service update): Only update fields which have been sent by server.
  pkg/kn/commands/configuration_edit_flags.go
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_create_test.go
  pkg/kn/commands/service_update.go
  pkg/kn/commands/service_update_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/service.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#145 Regroups code to use subpackages. Finishes issue #66
  cmd/kn/main.go
  go.mod
  go.sum
  hack/generate-docs.go
  pkg/kn/commands/human_readable_flags.go
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/revision/revision.go
  pkg/kn/commands/revision/revision_describe.go
  pkg/kn/commands/revision/revision_describe_test.go
  pkg/kn/commands/revision/revision_get.go
  pkg/kn/commands/revision/revision_get_flags.go
  pkg/kn/commands/revision/revision_get_test.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_delete.go
  pkg/kn/commands/service/service_describe.go
  pkg/kn/commands/service/service_describe_test.go
  pkg/kn/commands/service/service_get.go
  pkg/kn/commands/service/service_get_flags.go
  pkg/kn/commands/service/service_get_test.go
  pkg/kn/commands/service/service_update.go
  pkg/kn/commands/service/service_update_test.go
  pkg/kn/commands/service_get_flags.go
  pkg/kn/commands/test_helper.go
  pkg/kn/commands/types.go
  pkg/kn/commands/version.go
  pkg/kn/core/root.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#152 Add the support to build container image for kn
  config/release.yaml
  hack/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#160 feat(build.sh): Add a watch mode for automatic recompilation
  DEVELOPMENT.md
  hack/build.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#157 feat(service create/update): Add support of minScale/maxScale/target
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_update_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#105 Improve links in development docs
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#173 Remove unused value CfgFile
  pkg/kn/commands/test_helper.go
  pkg/kn/commands/types.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#175 fix(e2e): Use build.sh for compiling
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#171 fix(build.sh): Change from xnotify to fswatch for watching source code
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/S

#121 Adds a Golang version of e2e Basic workflow that can execute locally
  test/e2e-tests-local.sh
  test/e2e-tests.sh
  test/e2e/basic_workflow_test.go
  test/e2e/common.go
  test/e2e/e2e.go
  test/e2e/env.go
  test/e2e/kn.go
  test/e2e/kubectl.go
  test/e2e/version_test.go
Labels: approved, cla: yes, lgtm, size/L

#181 Fix typo in README.md
  docs/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#179 Renames service 'get' to 'list'
  docs/README.md
  docs/cmd/kn_service.md
  docs/cmd/kn_service_list.md
  docs/workflows.md
  go.mod
  go.sum
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/service_list.go
  pkg/kn/commands/service/service_list_flags.go
  pkg/kn/commands/service/service_list_test.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#180 Renames revision 'get' to 'list'
  docs/README.md
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_list.md
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/revision/revision.go
  pkg/kn/commands/revision/revision_list.go
  pkg/kn/commands/revision/revision_list_flags.go
  pkg/kn/commands/revision/revision_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#187 feat(build.sh) - Add mandatory license check
  hack/build-flags.sh
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/M

#178 Chore: Fix typos in docs
  DEVELOPMENT.md
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#169 fix(service update): Print success message after successful update
  pkg/kn/commands/service/service_update.go
  pkg/kn/commands/service/service_update_test.go
Labels: approved, cla: yes, lgtm, size/S

#194 List revisions for a given service
  docs/cmd/kn_revision_list.md
  pkg/kn/commands/revision/revision_list.go
  pkg/kn/commands/revision/revision_list_flags.go
  pkg/kn/commands/revision/revision_list_test.go
  test/e2e/basic_workflow_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#172 Set current namespace from kubeconfig by default
  cmd/kn/main.go
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/revision/revision_describe.go
  pkg/kn/commands/revision/revision_list.go
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_delete.go
  pkg/kn/commands/service/service_describe.go
  pkg/kn/commands/service/service_list.go
  pkg/kn/commands/service/service_update.go
  pkg/kn/commands/test_helper.go
  pkg/kn/commands/types.go
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#183 Restores the bash e2e tests as a smoke test
  test/e2e-smoke-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#199 fix(build.sh): Cosmetic spacing fix
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/S

#209 Add rhuss and maximilien to OWNERS to increase approver speed.
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#200 Fix the periodic CI flow error in client
  go.mod
  go.sum
  test/e2e/e2e_flags.go
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#156 feat(service create): Wait for a service to be ready when its created
  docs/cmd/kn_service_create.md
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/wait_args.go
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
  pkg/wait/test_wait_helper.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#186 feat(build.sh): Enable goimports + cleanup imports in source files
  go.mod
  go.sum
  hack/build.sh
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/revision/revision_list.go
  pkg/printers/tableprinter.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, size/M

#207 Add kn revision delete command
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_delete.md
  hack/generate-docs.go
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/delete_test.go
  pkg/kn/commands/revision/revision.go
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/wait_args.go
  pkg/kn/commands/test_helper.go
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
  pkg/wait/wait_for_ready.go
  test/e2e/revision_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#191 Added changes to support container port information while creating/updating service
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_update.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#170 Add the support to test against specified release of Knative serving
  test/e2e-tests.sh
  test/presubmit-integration-tests-latest-release.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#198 Fixes `limits-memory` and `requests-memory` descriptions
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
Labels: approved, cla: yes, lgtm, size/S
