Repository knative/client, pull requests merged in 2019-12, with the labels that each got.

#529 Update test-infra
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#528 Integration tests for Tekton
  test/e2e-common.sh
  test/e2e-smoke-tests.sh
  test/e2e-tests.sh
  test/e2e/common.go
  test/e2e/e2e_flags.go
  test/e2e/tekton_test.go
  test/resources/tekton/kn-deployer-rbac-template.yaml
  test/resources/tekton/kn-pipeline-resource-template.yaml
  test/resources/tekton/kn-pipeline-run.yaml
  test/resources/tekton/kn-pipeline.yaml
  test/tekton-tests.sh
  test/test_images/helloworld/Dockerfile
  test/test_images/helloworld/helloworld.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#538 Eventing setup in CI
  go.mod
  go.sum
  test/e2e-common.sh
  test/e2e-smoke-tests.sh
  test/e2e-tests.sh
  test/presubmit-integration-tests-latest-release.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#540 Remove unused emit-metrics flag for e2e tests
  test/e2e/e2e_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#537 Explicit name for serving client
  .gitignore
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/list.go
  pkg/kn/commands/route/describe.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/list.go
  pkg/kn/commands/service/service_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/commands/types.go
Labels: approved, cla: yes, lgtm, size/M

#543 service describe command : Move Cluster URL to --verbose from default output
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#415 kn source apiserver create/delete (as typed-builtin source)
  docs/cmd/kn.md
  docs/cmd/kn_source.md
  docs/cmd/kn_source_apiserver.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_delete.md
  pkg/eventing/sources/v1alpha1/client.go
  pkg/eventing/sources/v1alpha1/client_test.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/source/apiserver/apiserver.go
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_flag.go
  pkg/kn/commands/source/apiserver/create_flag_test.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/source/apiserver/delete.go
  pkg/kn/commands/source/apiserver/delete_test.go
  pkg/kn/commands/source/source.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/core/root.go
  vendor/modules.txt
Labels: approved, cla: yes, comp/source, lgtm, size/XL, topic/eventing-mvp

#536 kn source list-types (builtin types)
  docs/cmd/kn_source.md
  docs/cmd/kn_source_list-types.md
  go.mod
  pkg/dynamic/client.go
  pkg/dynamic/client_test.go
  pkg/eventing/sources/v1alpha1/client.go
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/source/list_types.go
  pkg/kn/commands/source/list_types_flags.go
  pkg/kn/commands/source/list_types_flags_test.go
  pkg/kn/commands/source/list_types_test.go
  pkg/kn/commands/source/source.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/commands/testing_helper_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  test/e2e-smoke-tests.sh
  test/e2e/source_list_types_test.go
  vendor/github.com/magiconair/properties/assert/assert.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#545 Vendor serving v0.11.0 and run tests against it
  go.mod
  go.sum
  test/presubmit-integration-tests-latest-release.sh
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/podscalable_types.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_accessors.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#535 Update deps using go 1.13
  DEVELOPMENT.md
  go.mod
  go.sum
  vendor/github.com/google/btree/btree_mem.go
  vendor/golang.org/x/sys/unix/mkasm_darwin.go
  vendor/golang.org/x/sys/unix/mkpost.go
  vendor/golang.org/x/sys/unix/mksyscall.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
  vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
  vendor/golang.org/x/sys/unix/mksyscall_solaris.go
  vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
  vendor/golang.org/x/sys/unix/mksysnum.go
  vendor/golang.org/x/sys/unix/types_aix.go
  vendor/golang.org/x/sys/unix/types_darwin.go
  vendor/golang.org/x/sys/unix/types_dragonfly.go
  vendor/golang.org/x/sys/unix/types_freebsd.go
  vendor/golang.org/x/sys/unix/types_netbsd.go
  vendor/golang.org/x/sys/unix/types_openbsd.go
  vendor/golang.org/x/sys/unix/types_solaris.go
  vendor/golang.org/x/text/encoding/internal/identifier/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen.go
  vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
  vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
  vendor/golang.org/x/text/unicode/norm/maketables.go
  vendor/golang.org/x/text/unicode/norm/triegen.go
  vendor/golang.org/x/text/width/gen.go
  vendor/golang.org/x/text/width/gen_common.go
  vendor/golang.org/x/text/width/gen_trieval.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#547 Selectively run e2e tests for serving, eventing
  test/e2e-tests-local.sh
  test/e2e/basic_workflow_test.go
  test/e2e/revision_test.go
  test/e2e/route_test.go
  test/e2e/service_options_test.go
  test/e2e/service_test.go
  test/e2e/source_list_types_test.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/XS

#548 chore: Refactor mock testing
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/delete_mock_test.go
  pkg/kn/commands/service/describe_test.go
  pkg/kn/commands/service/list_mock_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/serving/v1alpha1/client_mock.go
  pkg/serving/v1alpha1/client_mock_test.go
  pkg/util/mock/mock_helper.go
Labels: approved, cla: yes, lgtm, size/XL

#549 chore: Update version to v0.11.0 of serving and eventing
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
Labels: approved, cla: yes, lgtm, size/XS

#552 Add source apiserver create/delete e2e test
  test/e2e/source_apiserver_test.go
Labels: approved, cla: yes, lgtm, size/M

#541 Add command to create/delete a plain trigger
  docs/cmd/kn.md
  docs/cmd/kn_trigger.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_delete.md
  docs/cmd/kn_trigger_describe.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_mock.go
  pkg/eventing/v1alpha1/client_mock_test.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/delete.go
  pkg/kn/commands/trigger/delete_test.go
  pkg/kn/commands/trigger/describe.go
  pkg/kn/commands/trigger/describe_test.go
  pkg/kn/commands/trigger/flag.go
  pkg/kn/commands/trigger/flag_test.go
  pkg/kn/commands/trigger/trigger.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/kn/commands/types.go
  pkg/kn/core/root.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_broker.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/fake/fake_trigger.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1alpha1/trigger.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#555 Add readme for tests (#554)
  DEVELOPMENT.md
  test/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#558 Add trigger list
  docs/cmd/kn_trigger.md
  docs/cmd/kn_trigger_list.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_mock.go
  pkg/eventing/v1alpha1/client_mock_test.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/flags/list.go
  pkg/kn/commands/flags/list_test.go
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/delete_test.go
  pkg/kn/commands/trigger/list.go
  pkg/kn/commands/trigger/list_flags.go
  pkg/kn/commands/trigger/list_test.go
  pkg/kn/commands/trigger/trigger.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/kn/commands/trigger/update_flags.go
  pkg/kn/commands/trigger/update_flags_test.go
Labels: approved, cla: yes, lgtm, size/XL

#562 Add trigger update command
  docs/cmd/kn_trigger.md
  docs/cmd/kn_trigger_update.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_mock.go
  pkg/eventing/v1alpha1/client_mock_test.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/trigger.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/trigger/update_flags.go
  pkg/kn/commands/trigger/update_flags_test.go
  pkg/kn/commands/trigger/update_test.go
Labels: approved, cla: yes, lgtm, size/XL

#559 Add cronjob and apiserver source list commands
  docs/cmd/kn_source_apiserver.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_list.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_cronjob.md
  docs/cmd/kn_source_cronjob_list.md
  pkg/eventing/sources/v1alpha1/apiserver_client.go
  pkg/eventing/sources/v1alpha1/apiserver_client_mock.go
  pkg/eventing/sources/v1alpha1/apiserver_client_test.go
  pkg/eventing/sources/v1alpha1/cronjob_client.go
  pkg/eventing/sources/v1alpha1/cronjob_client_mock.go
  pkg/eventing/sources/v1alpha1/cronjob_client_test.go
  pkg/kn/commands/source/apiserver/apiserver.go
  pkg/kn/commands/source/apiserver/flags.go
  pkg/kn/commands/source/apiserver/list.go
  pkg/kn/commands/source/apiserver/list_test.go
  pkg/kn/commands/source/cronjob/cronjob.go
  pkg/kn/commands/source/cronjob/flags.go
  pkg/kn/commands/source/cronjob/list.go
  pkg/kn/commands/source/cronjob/list_test.go
Labels: approved, cla: yes, lgtm, size/XL

#560 chore(Changelog): Preparation for v0.11.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#561 chore(trigger): Cleanup Trigger create API
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_mock.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_flag_test.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/source/apiserver/flags.go
  pkg/kn/commands/source/apiserver/update.go
  pkg/kn/commands/source/cronjob/create.go
  pkg/kn/commands/source/cronjob/delete.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/trigger/update_flags.go
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
  test/e2e/source_apiserver_test.go
Labels: approved, cla: yes, lgtm, size/L

#573 Fix link in CHANGELOG
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/XS

#575 Retrurn error if exist duplicate key in filter option
  pkg/kn/commands/trigger/update_flags.go
  pkg/kn/commands/trigger/update_flags_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#468 load config values from viper if present in config
  pkg/kn/commands/plugin/list.go
  pkg/kn/commands/plugin/plugin.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/commands/types.go
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#582 Use the same flag definition for list command of list_type, service and route
  pkg/kn/commands/flags/list.go
  pkg/kn/commands/flags/listprint.go
  pkg/kn/commands/flags/listprint_test.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/route/list_flags.go
  pkg/kn/commands/route/list_flags_test.go
  pkg/kn/commands/service/list.go
  pkg/kn/commands/service/list_flags_test.go
  pkg/kn/commands/source/apiserver/list.go
  pkg/kn/commands/source/cronjob/list.go
  pkg/kn/commands/source/list_types.go
  pkg/kn/commands/source/list_types_flags.go
  pkg/kn/commands/source/list_types_flags_test.go
  pkg/kn/commands/trigger/list.go
Labels: approved, cla: yes, lgtm, size/L

#574 Allow for http and broker sinks
  pkg/dynamic/client.go
  pkg/dynamic/client_test.go
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/source/apiserver/apiserver_test.go
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/source/apiserver/update.go
  pkg/kn/commands/source/apiserver/update_test.go
  pkg/kn/commands/source/cronjob/create.go
  pkg/kn/commands/source/cronjob/create_test.go
  pkg/kn/commands/source/cronjob/cronjob_test.go
  pkg/kn/commands/source/cronjob/update.go
  pkg/kn/commands/source/cronjob/update_test.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/list_test.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/trigger/update_test.go
Labels: approved, cla: yes, lgtm, size/L
