Repository knative/client, pull requests merged in 2019-07, with the labels that each got.

#215 fix(serving): Fixed error message when timeout happens during wait for timeout
  pkg/wait/wait_for_ready.go
Labels: approved, cla: yes, lgtm, size/XS

#219 Exchange SERVICE and NAME column in kn revision list output
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/revision/revision_list.go
  pkg/kn/commands/revision/revision_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#220 Removes pausing between e2e smoke tests
  test/e2e-smoke-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#202 Add kn route list command
  docs/cmd/kn.md
  docs/cmd/kn_route.md
  docs/cmd/kn_route_list.md
  pkg/kn/commands/route/human_readable_flags.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/route/list_flags.go
  pkg/kn/commands/route/list_flags_test.go
  pkg/kn/commands/route/list_test.go
  pkg/kn/commands/route/route.go
  pkg/kn/core/root.go
  test/e2e-smoke-tests.sh
  test/e2e/basic_workflow_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#216 fix(serving): Fix logic 'service create --force' and some bogus tests
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_create_test.go
Labels: approved, cla: yes, lgtm, size/M

#218 fix(core): generic solution for issue #111 for all command groups
  docs/cmd/kn_revision.md
  docs/cmd/kn_service.md
  go.mod
  go.sum
  pkg/kn/core/root.go
  pkg/kn/core/root_test.go
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/github.com/pkg/errors/.gitignore
  vendor/github.com/pkg/errors/.travis.yml
  vendor/github.com/pkg/errors/LICENSE
  vendor/github.com/pkg/errors/README.md
  vendor/github.com/pkg/errors/appveyor.yml
  vendor/github.com/pkg/errors/errors.go
  vendor/github.com/pkg/errors/stack.go
  vendor/gotest.tools/LICENSE
  vendor/gotest.tools/assert/assert.go
  vendor/gotest.tools/assert/cmp/compare.go
  vendor/gotest.tools/assert/cmp/result.go
  vendor/gotest.tools/assert/result.go
  vendor/gotest.tools/internal/difflib/LICENSE
  vendor/gotest.tools/internal/difflib/difflib.go
  vendor/gotest.tools/internal/format/diff.go
  vendor/gotest.tools/internal/format/format.go
  vendor/gotest.tools/internal/source/defers.go
  vendor/gotest.tools/internal/source/source.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#221 fix(release.sh): Point to proper directory to extract the serving version
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#227 Add custom comparison for checking multiple substrings
  docs/cmd/kn_route.md
  pkg/kn/commands/revision/delete_test.go
  pkg/kn/commands/revision/revision_list_test.go
  pkg/kn/commands/route/list_test.go
  pkg/kn/commands/service/service_list_test.go
  pkg/kn/commands/test_helper.go
  pkg/util/compare.go
  pkg/util/compare_test.go
  test/e2e/revision_workflow_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#226 Added link to OpenShift kubeconfig creation docs
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#237 Small grammatical correction for README.md
  README.md
Labels: approved, cla: yes, lgtm, size/S

#238 Correct minor grammatical issue
  docs/README.md
Labels: approved, cla: yes, lgtm, size/S

#239 Add gofmt simplify code option in hack/build.sh
  hack/build.sh
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#243 Bulleted components in kn.md
  docs/cmd/kn.md
Labels: approved, cla: yes, lgtm, size/XS

#134 refactor(serving): KnClient interface for single point of cluster access
  go.mod
  go.sum
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/revision_describe.go
  pkg/kn/commands/revision/revision_list.go
  pkg/kn/commands/revision/revision_list_test.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_delete.go
  pkg/kn/commands/service/service_describe.go
  pkg/kn/commands/service/service_list.go
  pkg/kn/commands/service/service_list_test.go
  pkg/kn/commands/service/service_update.go
  pkg/kn/commands/test_helper.go
  pkg/kn/commands/types.go
  pkg/kn/core/root.go
  pkg/serving/schema_handling.go
  pkg/serving/schema_handling_test.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_test.go
  pkg/serving/v1alpha1/wait_args.go
  pkg/wait/test_wait_helper.go
  pkg/wait/wait_for_ready_test.go
  test/e2e/basic_workflow_test.go
  vendor/github.com/evanphx/json-patch/patch.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
  vendor/github.com/googleapis/gnostic/compiler/reader.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/gregjones/httpcache/README.md
  vendor/github.com/knative/build/pkg/apis/build/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/knative/pkg/apis/OWNERS
  vendor/github.com/knative/pkg/apis/contexts.go
  vendor/github.com/knative/pkg/apis/duck/OWNERS
  vendor/github.com/knative/pkg/apis/duck/typed.go
  vendor/github.com/knative/pkg/apis/duck/v1alpha1/addressable_types.go
  vendor/github.com/knative/pkg/configmap/OWNERS
  vendor/github.com/knative/pkg/kmeta/OWNERS
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#248 refactor(service): Removed io.writer from of KnClient.WaitForService()
  docs/cmd/kn.md
  pkg/kn/commands/service/service_create.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_test.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/M

#223 test(commands): backfills gotest.tools tests for version & completion
  pkg/kn/commands/completion_test.go
  pkg/kn/commands/help_testing.go
  pkg/kn/commands/version_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#241 chore(changelog): Add a changelog
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/L

#242 Adds Github issue and pull request templates
  .github/ISSUE_TEMPLATE/ask-question.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#150 get a particular service and revision based on name parameter
  docs/cmd/kn_revision_list.md
  docs/cmd/kn_service_list.md
  pkg/kn/commands/revision/revision_list.go
  pkg/kn/commands/revision/revision_list_test.go
  pkg/kn/commands/service/service_list.go
  pkg/kn/commands/service/service_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#247 fix(service): Show URL (external) instead of Address (internal) when listing service
  CHANGELOG.adoc
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/service/service_list_test.go
Labels: approved, cla: yes, lgtm, size/M

#244 fix: Update root docs for removing Build reference.
  docs/cmd/kn.md
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, size/S

#240 fix(service update): Retry an update in case of a conflict.
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_update.go
Labels: approved, cla: yes, lgtm, size/M

#250 chore(wait): Fixes for Smoke Tests + help messages
  docs/cmd/kn_service_create.md
  pkg/kn/commands/wait_flags.go
  test/e2e-smoke-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#251 Fix issue #205 to add route describe feature and test
  docs/cmd/kn_route.md
  docs/cmd/kn_route_describe.md
  pkg/kn/commands/route/route.go
  pkg/kn/commands/route/route_describe.go
  pkg/kn/commands/route/route_describe_test.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#256 Add e2e tests for service with concurrency options
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#263 Hide completion command from help.
  pkg/kn/commands/completion.go
Labels: approved, cla: yes, lgtm, size/XS

#264 Clean up e2e test assertion
  test/e2e/basic_workflow_test.go
  test/e2e/revision_workflow_test.go
  test/e2e/service_options_test.go
  test/e2e/version_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#265 fix(build): Minor build optimizations
  DEVELOPMENT.md
  docs/cmd/kn.md
  docs/cmd/kn_completion.md
  go.sum
  hack/build.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  pkg/kn/commands/completion.go
Labels: approved, cla: yes, lgtm, size/L

#222 Support multi config files
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#275 Rename lemonade-aware accessors to be less like methods that get from the server
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_update_test.go
  pkg/serving/config_changes.go
  pkg/serving/revision_template.go
  pkg/serving/service.go
Labels: approved, cla: yes, lgtm, size/L

#270 Command conventions doc
  conventions/cli.md
Labels: approved, cla: yes, lgtm, size/M

#281 Point release documentation to knative/test-infra
  hack/release.md
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/M

#271 feature(service): Wait on update for service to become ready.
  CHANGELOG.adoc
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_update.go
  pkg/kn/commands/service/service_update_test.go
  pkg/kn/commands/service/wait_args.go
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
Labels: approved, cla: yes, lgtm, size/L

#268 chore(build): Refactor to simplify and add dedicated test mode
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/M

#267 chore(revision): Remove unwanted log message in test
  pkg/kn/commands/revision/revision_list_test.go
Labels: approved, cla: yes, lgtm, size/XS

#274 Improves(e2e): improves integration tests and to better run locally
  test/e2e/basic_workflow_test.go
  test/e2e/common.go
  test/e2e/env.go
  test/e2e/revision_workflow_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/L

#279 Validate scale and container concurrency options when updating configuration resource
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/revision_template.go
  test/e2e/service_options_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#299 Move client conventions doc from Serving
  conventions/client.md
Labels: approved, cla: yes, lgtm, size/L

#291 Add E2E tests for Service, Revision, Route
  test/e2e/basic_workflow_test.go
  test/e2e/revision_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#302 improves(e2e): Update concurrency tests
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#300 test(service): Add e2e tests for min, max scale options
  test/e2e-tests-local.sh
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/M

#305 fix: Fix error when no current namespace is set
  pkg/kn/commands/namespaced.go
Labels: approved, cla: yes, lgtm, size/XS

#283 Document boolean flags by presence
  conventions/cli.md
Labels: approved, cla: yes, lgtm, size/XS

#307 Restructure E2E test suite
  test/e2e/basic_workflow_test.go
  test/e2e/common.go
  test/e2e/revision_test.go
  test/e2e/route_test.go
  test/e2e/service_options_test.go
  test/e2e/service_test.go
  test/e2e/version_test.go
Labels: approved, cla: yes, lgtm, size/L

#304 chore(tests): Update latest released version of serving to 0.7.1
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#306 feature(testing): Introduce a mock implementation for KnClient
  pkg/kn/commands/service/service_create_mock_test.go
  pkg/kn/commands/testing_helper.go
  pkg/serving/v1alpha1/client_mock.go
  pkg/serving/v1alpha1/client_mock_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#319 Use knative.dev/test-infra
  go.mod
  go.sum
  hack/release.sh
  hack/verify-codegen.sh
  pkg/dummy_test.go
  test/e2e-smoke-tests.sh
  test/e2e-tests.sh
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/LICENSE
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/dummy.go
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/markdown-lint-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#318 Report an error if no flag(s) set in service update
  pkg/kn/commands/service/service_update.go
  pkg/kn/commands/service/service_update_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#321 Adds Navid (@navidshaikh) to approvers list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS
