Repository knative/client, pull requests merged in 2019-05, with the labels that each got.

#81 added tests to `$kn service update ...` with --requests/limits-cpu/memory and removed required --image
  pkg/kn/commands/configuration_edit_flags.go
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_create_test.go
  pkg/kn/commands/service_update.go
  pkg/kn/commands/service_update_test.go
Labels: approved, lgtm, size/L

#93 Adds Cobra generated docs and means to generate them and first cut of other docs
  README.md
  docs/README.md
  docs/cmd/kn.md
  docs/cmd/kn_completion.md
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_describe.md
  docs/cmd/kn_revision_list.md
  docs/cmd/kn_service.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_list.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_version.md
  docs/plugins.md
  docs/workflows.md
  go.mod
  go.sum
  hack/generate-docs.go
  hack/generate-docs.sh
  vendor/github.com/cpuguy83/go-md2man/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/md2man/roff.go
  vendor/github.com/russross/blackfriday/.gitignore
  vendor/github.com/russross/blackfriday/.travis.yml
  vendor/github.com/russross/blackfriday/LICENSE.txt
  vendor/github.com/russross/blackfriday/README.md
  vendor/github.com/russross/blackfriday/block.go
  vendor/github.com/russross/blackfriday/doc.go
  vendor/github.com/russross/blackfriday/go.mod
  vendor/github.com/russross/blackfriday/html.go
  vendor/github.com/russross/blackfriday/inline.go
  vendor/github.com/russross/blackfriday/latex.go
  vendor/github.com/russross/blackfriday/markdown.go
  vendor/github.com/russross/blackfriday/smartypants.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/man_docs.md
  vendor/github.com/spf13/cobra/doc/md_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/rest_docs.go
  vendor/github.com/spf13/cobra/doc/rest_docs.md
  vendor/github.com/spf13/cobra/doc/util.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/github.com/spf13/cobra/doc/yaml_docs.md
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#98 License checking works now, enable it
  go.mod
  go.sum
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#88 Fix returning the namespace for listing resources
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/namespaced_test.go
Labels: approved, lgtm, ok-to-test, size/L

#85 Adds human-friendly table printing for resource listing
  pkg/printers/interface.go
  pkg/printers/tablegenerator.go
  pkg/printers/tableprinter.go
  pkg/printers/tabwriter.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#96 Set `SilenceErrors: true` on `rootCmd` so that we can deal with errors ourselves
  pkg/kn/commands/root.go
Labels: approved, lgtm, size/XS

#83 Add a Makefile
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/S

#90 Adds service get command
  go.mod
  pkg/kn/commands/human_readable_flags.go
  pkg/kn/commands/service.go
  pkg/kn/commands/service_get.go
  pkg/kn/commands/service_get_flags.go
  pkg/kn/commands/service_get_test.go
  vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L

#95 Adds info message after service create and delete operations
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_create_test.go
  pkg/kn/commands/service_delete.go
Labels: approved, lgtm, ok-to-test, size/S

#99 Adds basic workflow
  docs/workflows.md
Labels: approved, lgtm, size/L

#106 Disable cgo extensions in build-binaries.sh
  hack/build-binaries.sh
Labels: approved, lgtm, size/XS

#113 Fix command for "kn service" smoke test
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#109 Updates docs/workflows.md
  docs/workflows.md
Labels: approved, lgtm, size/M

#79 Adds --force flag to service create command (service replace)
  pkg/kn/commands/configuration_edit_flags.go
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_create_test.go
Labels: approved, lgtm, ok-to-test, size/L

#108 Updates generated Cobra docs for commands and adds new
  docs/cmd/kn.md
  docs/cmd/kn_completion.md
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_describe.md
  docs/cmd/kn_revision_get.md
  docs/cmd/kn_service.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_get.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_version.md
  hack/build.sh
  pkg/kn/commands/root.go
Labels: approved, lgtm, size/M

#115 Setup release infrastructure for Knative Client
  go.mod
  go.sum
  hack/NEXT_VERSION
  hack/build-binaries.sh
  hack/release.md
  hack/release.sh
  hack/util/flags.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#124 Fix auto releases of Knative Client
  go.mod
  go.sum
  hack/release.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#118 Checks if --image is given before applying image to config
  pkg/kn/commands/configuration_edit_flags.go
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_update.go
  pkg/kn/commands/service_update_test.go
Labels: approved, lgtm, ok-to-test, size/M

#122 fix(build.sh): Reintroduced build-flags.sh
  hack/build-flags.sh
  hack/build.sh
  hack/release.sh
Labels: approved, ok-to-test, size/S

#125 Copy-edit documentation, and make user guide start with installation.
  README.md
  docs/README.md
  docs/cmd/kn_revision_get.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_get.md
  docs/workflows.md
Labels: approved, lgtm, size/L

#112 Tests running simple workflow in e2e
  test/e2e-tests.sh
Labels: approved, lgtm, ok-to-test, size/S

#132 Adds Zsh completion (finishes issue #130)
  docs/cmd/kn.md
  docs/cmd/kn_completion.md
  pkg/kn/commands/completion.go
Labels: approved, lgtm, size/S

#131 Adds IBM's IKS to the list of services
  docs/README.md
Labels: approved, lgtm, size/XS

#119 Adds missing license to completion.go
  pkg/kn/commands/completion.go
Labels: approved, lgtm, ok-to-test, size/S

#137 fix: Update cli-runtime to include fix for cli options help
  docs/cmd/kn_revision_describe.md
  docs/cmd/kn_revision_get.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_get.md
  go.mod
  go.sum
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/jsonpath_flags.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/json.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/printers/jsonpath.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/resource/builder.go
  vendor/k8s.io/cli-runtime/pkg/genericclioptions/template_flags.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/M

#136 chore: Streamlined build.sh
  hack/build-flags.sh
  hack/build.sh
  hack/generate-docs.go
  hack/generate-docs.sh
  hack/release.sh
  pkg/kn/commands/version.go
Labels: approved, lgtm, ok-to-test, size/L

#148 update test-infra in vendor
  go.mod
  go.sum
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#149 feat(build.sh): Adding options and running tests
  DEVELOPMENT.md
  hack/build.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L
