Repository knative/client, pull requests merged in 2019-04, with the labels that each got.

#39 Adds DEVELOPMENT.md
  DEVELOPMENT.md
  README.md
Labels: approved, lgtm, size/L

#47 `service create` beginning implementation
  pkg/kn/commands/configuration_edit_flags.go
  pkg/kn/commands/service.go
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_create_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/service.go
Labels: approved, lgtm, size/L

#64 Add hack/verify-codegen.sh so CI verifies vendor/ doesn't drift
  hack/update-deps.sh
  hack/verify-codegen.sh
Labels: approved, lgtm, size/M

#60 Make image flag mandatory for service create command
  pkg/kn/commands/configuration_edit_flags.go
  pkg/kn/commands/service_create.go
Labels: approved, lgtm, size/XS

#55 Stub in an integration test
  go.mod
  go.sum
  test/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/L

#62 Adds example usage in service create command
  pkg/kn/commands/service_create.go
Labels: approved, lgtm, size/XS

#32 Support --all-namespaces option for service and revision list
  go.mod
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/revision.go
  pkg/kn/commands/revision_describe.go
  pkg/kn/commands/revision_list.go
  pkg/kn/commands/service.go
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_describe.go
  pkg/kn/commands/service_list.go
Labels: approved, lgtm, size/M

#63 Adds service delete command
  pkg/kn/commands/service.go
  pkg/kn/commands/service_delete.go
Labels: approved, lgtm, size/M

#73 Call GetNamespace to get namespace
  pkg/kn/commands/service_delete.go
Labels: approved, lgtm, size/XS

#69 adding hack/build* to make life easy and added version command
  .gitignore
  hack/build-binaries.sh
  hack/build.sh
  pkg/kn/commands/root.go
  pkg/kn/commands/service_describe_test.go
  pkg/kn/commands/version.go
  pkg/serving/config_changes_test.go
Labels: approved, lgtm, size/M

#74 Basic service update & a test for it.
  pkg/kn/commands/service.go
  pkg/kn/commands/service_update.go
  pkg/kn/commands/service_update_test.go
Labels: approved, lgtm, size/L

#77 fix(build.sh): Fix path to built kn when printing out the version
  hack/build.sh
Labels: approved, lgtm, ok-to-test, size/XS

#78 Added support for limits and requests of CPU and memory
  go.mod
  go.sum
  pkg/kn/commands/configuration_edit_flags.go
  pkg/kn/commands/service_create.go
  pkg/kn/commands/service_create_test.go
  pkg/serving/config_changes.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test, size/L
