Repository knative/client, pull requests merged in 2019-08, with the labels that each got.

#322 fix(bug) correct response for unknown command or plugin fixes(#309)
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, size/XS

#316 Update dev docs for some missing bits
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#326 Add --log-http option
  docs/cmd/kn.md
  docs/cmd/kn_plugin.md
  docs/cmd/kn_plugin_list.md
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_delete.md
  docs/cmd/kn_revision_describe.md
  docs/cmd/kn_revision_list.md
  docs/cmd/kn_route.md
  docs/cmd/kn_route_describe.md
  docs/cmd/kn_route_list.md
  docs/cmd/kn_service.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_list.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_version.md
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  pkg/kn/core/root.go
  pkg/util/logging_http_transport.go
  pkg/util/logging_http_transport_test.go
Labels: approved, cla: yes, lgtm, size/L

#332 List revisions sorted by configuration generation
  CHANGELOG.adoc
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/revision/revision_list.go
  pkg/kn/commands/revision/revision_list_test.go
  test/e2e/revision_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#341 Add 'creator' annotation on create --force
  pkg/kn/commands/service/service_create.go
Labels: approved, cla: yes, lgtm, size/S

#343 Only test in watch mode if passed test flag
  hack/build.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#252 feature(service describe): Output of service details
  CHANGELOG.adoc
  docs/cmd/kn_service.md
  docs/cmd/kn_service_describe.md
  go.mod
  go.sum
  pkg/kn/commands/service/service_create_mock_test.go
  pkg/kn/commands/service/service_describe.go
  pkg/kn/commands/service/service_describe_test.go
  pkg/kn/commands/service/service_test.go
  pkg/printers/prefixwriter.go
  pkg/printers/tableprinter.go
  pkg/printers/tabwriter.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_mock.go
  pkg/serving/v1alpha1/client_mock_test.go
  pkg/serving/v1alpha1/client_test.go
  test/e2e/basic_workflow_test.go
  vendor/github.com/golang/protobuf/proto/properties.go
  vendor/github.com/json-iterator/go/adapter.go
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/json-iterator/go/iter_skip.go
  vendor/github.com/json-iterator/go/reflect_native.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/stream_float.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#348 fix(test): Give the namespace some time setup to fix 'no serviceaccount default' flake
  test/e2e/common.go
Labels: approved, cla: yes, lgtm, size/XS

#313 refactor(plugins): Improved and simplified verifier and plugin list
  docs/cmd/kn_plugin.md
  docs/cmd/kn_plugin_list.md
  go.mod
  pkg/kn/commands/plugin/path_verifier.go
  pkg/kn/commands/plugin/path_verifier_test.go
  pkg/kn/commands/plugin/plugin_handler.go
  pkg/kn/commands/plugin/plugin_list.go
  pkg/kn/commands/plugin/plugin_list_flags.go
  pkg/kn/commands/plugin/plugin_list_flags_test.go
  pkg/kn/commands/plugin/plugin_list_test.go
  pkg/kn/commands/plugin/plugin_test_helper.go
  pkg/kn/commands/plugin/plugin_verifier.go
  pkg/kn/commands/plugin/plugin_verifier_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#330 List services sorted by alphabetical order
  CHANGELOG.adoc
  pkg/kn/commands/service/service_list.go
  pkg/kn/commands/service/service_list_test.go
Labels: approved, cla: yes, lgtm, size/S

#356 Add support for -A variant of --all-namespaces
  docs/cmd/kn_revision_list.md
  docs/cmd/kn_route_list.md
  docs/cmd/kn_service_list.md
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/namespaced_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#355 docs: References golang 1.12.7 or later in docs
  DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#352 Fix index out of range error
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, size/M

#351 Wrap flag usage to terminal size
  go.mod
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, size/S

#342 Service and Revision labels
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/service_create_mock_test.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_update_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/util/parsing_helper.go
  pkg/util/parsing_helper_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#346 Bool flags in the paired `--foo` and `--no-foo` format
  pkg/kn/core/root.go
  pkg/kn/flags/bool.go
  pkg/kn/flags/bool_test.go
Labels: approved, cla: yes, lgtm, size/L

#362 Clean up bool flags a little
  pkg/kn/flags/bool.go
  pkg/kn/flags/bool_test.go
Labels: approved, cla: yes, lgtm, size/M

#282 Specify names on service update and generate names client-side.
  CHANGELOG.adoc
  cmd/kn/main.go
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/service_update_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/service.go
  pkg/serving/service_test.go
Labels: approved, cla: yes, lgtm, size/L

#312 improved create service error message
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/errors/factory.go
  pkg/errors/factory_test.go
  pkg/errors/knerror.go
  pkg/errors/knerror_test.go
  pkg/errors/types.go
  pkg/serving/v1alpha1/client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#345 feature(service): Implements traffic splitting and tagging targets
  CHANGELOG.adoc
  docs/cmd/kn_service_update.md
  pkg/kn/commands/flags/traffic.go
  pkg/kn/commands/service/service_update.go
  pkg/kn/traffic/compute.go
  pkg/kn/traffic/compute_test.go
  test/e2e-tests.sh
  test/e2e/common.go
  test/e2e/env.go
  test/e2e/traffic_split_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#361 Always create in new format rather than old
  pkg/kn/commands/service/service_create.go
  pkg/kn/commands/service/service_create_mock_test.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_test.go
Labels: approved, cla: yes, lgtm, size/L

#363 Add reference to plugin in README.md
  docs/README.md
Labels: approved, cla: yes, lgtm, size/S

#370 kn version command to list supported serving versions and APIs
  CHANGELOG.adoc
  pkg/kn/commands/version.go
  pkg/kn/commands/version_test.go
Labels: approved, cla: yes, lgtm, size/M

#376 Fix json path to latest revision in e2e tests to something reliable
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/XS

#380 check if status detail is nil
  pkg/errors/factory.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#378 Retain the request body when logging HTTP.
  pkg/util/logging_http_transport.go
  pkg/util/logging_http_transport_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#382 Pass on args to e2e tests for local script
  test/e2e-tests-local.sh
Labels: approved, cla: yes, lgtm, size/XS

#371 Adds option in hack/build.sh to build cross platform binaries
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/S

#366 feature(service list): Print NAMESPACE column as the first column when --all-namespaces is specified
  CHANGELOG.adoc
  pkg/kn/commands/human_readable_flags.go
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/route/human_readable_flags.go
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/service/service_list.go
  pkg/kn/commands/service/service_list_flags.go
  pkg/kn/commands/service/service_list_mock_test.go
  pkg/kn/commands/service/service_list_test.go
  pkg/printers/interface.go
  pkg/printers/tableprinter.go
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/L

#359 chore(plugins, services, routes): Aligned "Not found" messages
  pkg/kn/commands/plugin/plugin_list.go
  pkg/kn/commands/plugin/plugin_list_test.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/route/list_test.go
  pkg/kn/commands/service/service_list.go
  pkg/kn/commands/service/service_list_test.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, size/S

#386 Remove namespace from args
  pkg/kn/commands/service/service_create.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#388 fix lint errors
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/plugin/plugin_handler_test.go
  pkg/kn/commands/plugin/plugin_list_test.go
  pkg/kn/commands/plugin/plugin_verifier.go
  pkg/kn/commands/plugin/plugin_verifier_windows.go
  pkg/kn/commands/service/service_create_test.go
  pkg/kn/commands/service/service_describe.go
  pkg/kn/commands/service/service_update.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  pkg/kn/core/root.go
  pkg/kn/traffic/compute.go
  pkg/serving/schema_handling.go
  pkg/util/parsing_helper.go
  test/e2e/common.go
  test/e2e/service_test.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
