Repository knative/client, pull requests merged in 2019-10, with the labels that each got.

#411 Fixes issue #338 by adding documentation for the Kn config
  docs/README.md
Labels: approved, cla: yes, lgtm, size/S

#379 Service describe: information about revision status, tags, latest [created, ready] revisions, and latest traffic
  docs/cmd/kn_plugin.md
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
  test/e2e/basic_workflow_test.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#428 fixes(#414): change plugins config keys to use - instead of camel case
  docs/cmd/kn.md
  docs/cmd/kn_plugin.md
  docs/cmd/kn_plugin_list.md
  pkg/kn/commands/plugin/list.go
  pkg/kn/commands/plugin/list_test.go
  pkg/kn/commands/plugin/plugin.go
  pkg/kn/commands/plugin/plugin_test.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/commands/types.go
  pkg/kn/core/root_test.go
Labels: approved, cla: yes, lgtm, size/M

#422 feat(annotations): Adds annotation flag for service create and update
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/L

#433 chore(test): Add a ContainsAllIgnoreCase helper method
  pkg/util/compare.go
  pkg/util/compare_test.go
Labels: approved, cla: yes, lgtm, size/M

#432 chore(build.sh) Add indicator in watch mode after successful compilation
  CHANGELOG.adoc
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#435 Minor grammar corrections
  docs/README.md
Labels: approved, cla: yes, lgtm, size/S

#437 Update README.md
  docs/workflows/README.md
Labels: approved, cla: yes, lgtm, size/XS

#436 Add navigation for management section
  docs/operations/management.md
Labels: approved, cla: yes, lgtm, size/S

#431 chore(service): Improvements for waiting on service readiness
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/list_mock_test.go
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/commands/testing_helper.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_mock.go
  pkg/serving/v1alpha1/client_mock_test.go
  pkg/serving/v1alpha1/client_test.go
  pkg/wait/test_wait_helper.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
  test/e2e/basic_workflow_test.go
  test/e2e/service_options_test.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#442 chore: Some minor printout fixes
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/version.go
  pkg/kn/commands/version_test.go
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, size/M

#448 Updates YAML transitive dependency to v2.2.4
  go.mod
  go.sum
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#451 Fix a small error in verify-codegen.sh
  .gitignore
  hack/verify-codegen.sh
Labels: approved, cla: yes, lgtm, size/XS

#446 fix(service): Set default timeout for update to the same value as for create
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/wait_flags.go
Labels: approved, cla: yes, lgtm, size/S

#450 chore: go mod tidy updates
  go.mod
  go.sum
Labels: approved, cla: yes, lgtm, size/M

#454 fix(e2e): Improves the error message upon mismatch of traffic targets
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/XS

#455 Runs go mod tidy part of updating dependencies in hack/build.sh
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#453 fix(version): Displays supported APIs and version
  hack/build-flags.sh
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
  pkg/kn/core/root.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/M

#407 Refine route list output
  pkg/kn/commands/route/human_readable_flags.go
  pkg/kn/commands/route/list_test.go
  test/e2e/route_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#439 removes zsh completion since it does not work (fixes #426)
  pkg/kn/commands/completion.go
  pkg/kn/commands/completion_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#441 Add revision information to service list
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/service/list_mock_test.go
  pkg/kn/commands/service/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#461 chore: Update changelog in prep for 0.8.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/L

#430 Refactor describe: printing levels and shared kn code
  pkg/kn/commands/describe.go
  pkg/kn/commands/describe_test.go
  pkg/kn/commands/service/describe.go
  pkg/printers/prefixwriter.go
  pkg/printers/prefixwriter_test.go
Labels: approved, cla: yes, lgtm, size/XL

#463 chore: Final preps for 0.9.0 release
  CHANGELOG.adoc
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
Labels: approved, cla: yes, lgtm, size/XS

#443 Updates spf13/cobra dep to v0.0.5
  go.mod
  vendor/github.com/cpuguy83/go-md2man/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/md2man/roff.go
  vendor/github.com/cpuguy83/go-md2man/v2/LICENSE.md
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/md2man.go
  vendor/github.com/cpuguy83/go-md2man/v2/md2man/roff.go
  vendor/github.com/russross/blackfriday/doc.go
  vendor/github.com/russross/blackfriday/go.mod
  vendor/github.com/russross/blackfriday/html.go
  vendor/github.com/russross/blackfriday/latex.go
  vendor/github.com/russross/blackfriday/markdown.go
  vendor/github.com/russross/blackfriday/v2/.gitignore
  vendor/github.com/russross/blackfriday/v2/.travis.yml
  vendor/github.com/russross/blackfriday/v2/LICENSE.txt
  vendor/github.com/russross/blackfriday/v2/README.md
  vendor/github.com/russross/blackfriday/v2/block.go
  vendor/github.com/russross/blackfriday/v2/doc.go
  vendor/github.com/russross/blackfriday/v2/esc.go
  vendor/github.com/russross/blackfriday/v2/go.mod
  vendor/github.com/russross/blackfriday/v2/html.go
  vendor/github.com/russross/blackfriday/v2/inline.go
  vendor/github.com/russross/blackfriday/v2/markdown.go
  vendor/github.com/russross/blackfriday/v2/node.go
  vendor/github.com/russross/blackfriday/v2/smartypants.go
  vendor/github.com/shurcooL/sanitized_anchor_name/.travis.yml
  vendor/github.com/shurcooL/sanitized_anchor_name/LICENSE
  vendor/github.com/shurcooL/sanitized_anchor_name/README.md
  vendor/github.com/shurcooL/sanitized_anchor_name/go.mod
  vendor/github.com/shurcooL/sanitized_anchor_name/main.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/github.com/spf13/viper/go.mod
  vendor/github.com/spf13/viper/go.sum
  vendor/github.com/spf13/viper/viper.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL
