Repository knative/client, pull requests merged in 2019-02, with the labels that each got.

#19 Generate go.sum with go 1.11.5
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#21 Add more .gitignore
  .gitignore
Labels: lgtm, size/S

#20 Add building documentaiton
  README.md
Labels: approved, lgtm, size/S

#18 Add service describe
  pkg/kn/commands/service.go
  pkg/kn/commands/service_describe.go
  pkg/kn/commands/service_describe_test.go
Labels: approved, lgtm, size/L

#24 Fixes typo in the kn help command
  pkg/kn/commands/revision.go
  pkg/kn/commands/root.go
  pkg/kn/commands/service.go
Labels: lgtm, size/XS
