Repository knative/client, pull requests merged in 2019-03, with the labels that each got.

#34 Incorporate reference to knative/test-infra for setting up automated tests.
  .gitignore
  go.mod
  go.sum
  pkg/dummy_test.go
  test/presubmit-tests.sh
  vendor/github.com/knative/test-infra/LICENSE
  vendor/github.com/knative/test-infra/scripts/README.md
  vendor/github.com/knative/test-infra/scripts/dummy.go
  vendor/github.com/knative/test-infra/scripts/e2e-tests.sh
  vendor/github.com/knative/test-infra/scripts/library.sh
  vendor/github.com/knative/test-infra/scripts/markdown-link-check-config.rc
  vendor/github.com/knative/test-infra/scripts/markdown-lint-config.rc
  vendor/github.com/knative/test-infra/scripts/presubmit-tests.sh
  vendor/github.com/knative/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#27 Pickup config path from KUBECONFIG
  pkg/kn/commands/root.go
Labels: approved, lgtm, size/XS

#31 Support generating bash completion
  README.md
  pkg/kn/commands/completion.go
  pkg/kn/commands/root.go
Labels: approved, needs-ok-to-test, size/M

#46 go.mod and go.sum updates
  go.mod
  go.sum
  test/presubmit-tests.sh
Labels: approved, lgtm, size/XS

#44 Update links to docs repo
  README.md
Labels: approved, lgtm, size/XS

#42 Fix flag parse error by calling flag.Parse first
  pkg/kn/commands/root.go
Labels: approved, lgtm, needs-ok-to-test, size/XS

#43 Add SilenceUsage option to cobra command
  pkg/kn/commands/root.go
  pkg/kn/commands/service_describe.go
Labels: approved, lgtm, size/S
