Repository knative/client, pull requests merged in 2020-11, with the labels that each got.

#964 Feature: "kn service apply"
  docs/cmd/kn_service.md
  docs/cmd/kn_service_apply.md
  go.mod
  go.sum
  pkg/kn/commands/service/apply.go
  pkg/kn/commands/service/apply_mock_test.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/service.go
  pkg/serving/v1/apply.go
  pkg/serving/v1/apply_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
  pkg/serving/v1/client_mock_test.go
  pkg/util/unstructured.go
  test/e2e/service_apply_test.go
  vendor/k8s.io/apimachinery/pkg/util/jsonmergepatch/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1069 Export test refactor
  lib/test/service.go
  pkg/kn/commands/service/export_test.go
  test/e2e/service_export_test.go
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/pkg/gc/doc.go
  vendor/knative.dev/serving/pkg/gc/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/doc.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/store.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/doc.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/labels/doc.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/labels/labels.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/names/doc.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/names/names.go
  vendor/knative.dev/serving/pkg/reconciler/service/resources/names/doc.go
  vendor/knative.dev/serving/pkg/reconciler/service/resources/names/names.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1085 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_lifecycle.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/register.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/labels/labels.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1088 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1091 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1090 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/L

#1092 feat: Add channel sink prefix
  CHANGELOG.adoc
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  test/e2e/sink_test.go
Labels: approved, cla: yes, lgtm, size/M

#1094 Drop deprecated --async flag support
  CHANGELOG.adoc
  docs/cmd/kn_broker_delete.md
  docs/cmd/kn_revision_delete.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
  pkg/kn/flags/bool.go
  pkg/kn/flags/bool_test.go
Labels: approved, cla: yes, lgtm, size/M

#1065 feat: Add service import command
  CHANGELOG.adoc
  docs/cmd/kn_service.md
  docs/cmd/kn_service_import.md
  pkg/kn/commands/service/import.go
  pkg/kn/commands/service/import_test.go
  pkg/kn/commands/service/service.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
  pkg/serving/v1/client_mock_test.go
  test/e2e/service_import_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1103 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1104 [release-0.18] Backport #1092
  CHANGELOG.adoc
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  test/e2e/sink_test.go
Labels: approved, backport/pr, cla: yes, lgtm, size/M

#1106 feature: Add Linux arm64 builds to the release
  CHANGELOG.adoc
  hack/build.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/S

#1107 fix: Fix var initialization in lib/service function
  lib/test/service.go
Labels: approved, cla: yes, lgtm, size/S

#1108 feat: Add checksums.txt to release to have the sha256 checksums published, too.
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1105 [release-0.17] Backport #1092
  CHANGELOG.adoc
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  test/e2e-tests.sh
  test/e2e/sink_test.go
Labels: approved, backport/pr, cla: yes, lgtm, size/M

#1110 chore: Remove deprecated requests/limits flags
  CHANGELOG.adoc
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
Labels: approved, cla: yes, lgtm, size/L

#1111 Update version dependency to 0.19 + update version command
  go.mod
  go.sum
  pkg/kn/commands/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1112 tune changelog for 0.19.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#1115 quick fix for quoting which broke the release
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1116 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1117 Embed the namespace in request body while creating channels
  CHANGELOG.adoc
  pkg/kn/commands/channel/channel_test.go
  pkg/kn/commands/channel/create.go
  pkg/kn/commands/channel/create_test.go
  pkg/kn/commands/channel/describe_test.go
  pkg/kn/commands/channel/list_test.go
  pkg/messaging/v1beta1/channels_client.go
Labels: approved, cla: yes, lgtm, size/M

#1119 Fix a few more occurrences of divisive language
  cmd/kn/main.go
  cmd/kn/main_test.go
  pkg/kn/commands/options/options.go
  pkg/kn/config/config.go
  pkg/kn/config/testing_test.go
  pkg/kn/traffic/compute.go
  pkg/serving/v1/client_test.go
  pkg/util/logging_http_transport_test.go
Labels: approved, cla: yes, lgtm, size/M

#1120 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/sinkbinding_lifecycle.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/test/logging/.gitattributes
  vendor/knative.dev/pkg/test/logging/doc.go
  vendor/knative.dev/pkg/test/logging/error.go
  vendor/knative.dev/pkg/test/logging/logger.go
  vendor/knative.dev/pkg/test/logging/memory_encoder.go
  vendor/knative.dev/pkg/test/logging/spew_encoder.go
  vendor/knative.dev/pkg/test/logging/sugar.go
  vendor/knative.dev/pkg/test/logging/tlogger.go
  vendor/knative.dev/pkg/test/logging/zapr.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1118 Add url output for broker and channel
  CHANGELOG.adoc
  docs/cmd/kn_broker_describe.md
  docs/cmd/kn_channel_describe.md
  pkg/kn/commands/broker/describe.go
  pkg/kn/commands/broker/describe_test.go
  pkg/kn/commands/channel/channel_test.go
  pkg/kn/commands/channel/describe.go
  pkg/kn/commands/channel/describe_test.go
Labels: approved, cla: yes, lgtm, size/L

#1124 Add machine-readable output for broker
  CHANGELOG.adoc
  docs/cmd/kn_broker_describe.md
  pkg/eventing/v1beta1/client.go
  pkg/kn/commands/broker/describe.go
  pkg/kn/commands/broker/describe_test.go
Labels: approved, cla: yes, lgtm, size/M

#1132 [release-0.18] Backport of #1117
  CHANGELOG.adoc
  pkg/kn/commands/channel/channel_test.go
  pkg/kn/commands/channel/create.go
  pkg/kn/commands/channel/create_test.go
  pkg/kn/commands/channel/describe_test.go
  pkg/kn/commands/channel/list_test.go
  pkg/messaging/v1beta1/channels_client.go
Labels: approved, cla: yes, lgtm, size/M

#1134 [release-0.17] Backport of #1117
  CHANGELOG.adoc
  pkg/kn/commands/channel/channel_test.go
  pkg/kn/commands/channel/create.go
  pkg/kn/commands/channel/create_test.go
  pkg/kn/commands/channel/describe_test.go
  pkg/kn/commands/channel/list_test.go
  pkg/messaging/v1beta1/channels_client.go
Labels: approved, cla: yes, lgtm, size/M

#1136 Run e2e CI job against eventing v0.19.1 since nightly is broken
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1131 chore(e2e): Run latest release e2e job against v0.19.x
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1121 Add machine readable output for trigger
  CHANGELOG.adoc
  docs/cmd/kn_trigger_describe.md
  pkg/eventing/v1beta1/client.go
  pkg/kn/commands/trigger/describe.go
  pkg/kn/commands/trigger/describe_test.go
Labels: approved, cla: yes, lgtm, size/M

#1126 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1083 Cross-compile the kn binary for linux/s390x
  hack/build.sh
  hack/release.sh
Labels: approved, backport/candidate, cla: yes, lgtm, ok-to-test, size/XS

#1114 adds --scale range option
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
Labels: approved, cla: yes, lgtm, size/L

#1137 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1113 Fix race conditions when creating watches
  CHANGELOG.adoc
  pkg/eventing/v1beta1/client.go
  pkg/serving/v1/client.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/L

#1135 [release-0.19] Backport #1117 #1083 #1113
  CHANGELOG.adoc
  hack/build.sh
  hack/release.sh
  pkg/eventing/v1beta1/client.go
  pkg/kn/commands/channel/channel_test.go
  pkg/kn/commands/channel/create.go
  pkg/kn/commands/channel/create_test.go
  pkg/kn/commands/channel/describe_test.go
  pkg/kn/commands/channel/list_test.go
  pkg/messaging/v1beta1/channels_client.go
  pkg/serving/v1/client.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, backport/pr, cla: yes, lgtm, size/L

#1139 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1138 [release-0.18] Backport #1083 #1113
  CHANGELOG.adoc
  hack/build.sh
  hack/release.sh
  pkg/eventing/v1beta1/client.go
  pkg/serving/v1/client.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, backport/pr, cla: yes, lgtm, size/L

#1140 fix quoting in hack/release.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1141 fix quoting in hack/release.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1142 [release-0.18] Update hack/release.sh
  CHANGELOG.adoc
  hack/release.sh
Labels: approved, backport/pr, cla: yes, lgtm, size/XS

#1145 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1146 Add machine readable output (-o flag) to kn source apiserver describe
  CHANGELOG.adoc
  docs/cmd/kn_source_apiserver_describe.md
  pkg/kn/commands/source/apiserver/describe.go
  pkg/kn/commands/source/apiserver/describe_test.go
  pkg/sources/v1alpha2/apiserver_client.go
Labels: approved, cla: yes, lgtm, size/M

#1149 Carry changelogs from patch releases to main branch
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#1151 Run e2e-tests against eventing nightly
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1150 Add machine readable output (-o flag) to kn source ping describe
  CHANGELOG.adoc
  docs/cmd/kn_source_ping_describe.md
  pkg/kn/commands/source/ping/describe.go
  pkg/kn/commands/source/ping/describe_test.go
  pkg/sources/v1alpha2/ping_client.go
Labels: approved, cla: yes, lgtm, size/M

#1148 Add machine readable output (-o flag) to kn source binding describe
  CHANGELOG.adoc
  docs/cmd/kn_source_binding_describe.md
  pkg/kn/commands/source/binding/describe.go
  pkg/kn/commands/source/binding/describe_test.go
  pkg/sources/v1alpha2/binding_client.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1155 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1154 Improve error handling in clients
  CHANGELOG.adoc
  pkg/sources/v1alpha2/apiserver_client.go
  pkg/sources/v1alpha2/ping_client.go
Labels: approved, cla: yes, lgtm, size/S

#1153 Build and release binaries for linux/ppc64le
  hack/build.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1152 Remove unnecessary help message
  CHANGELOG.adoc
  pkg/kn/commands/source/apiserver/describe.go
  pkg/kn/commands/source/ping/describe.go
  pkg/kn/commands/trigger/describe.go
Labels: approved, cla: yes, lgtm, size/S
