Repository knative/client, pull requests merged in 2020-03, with the labels that each got.

#696 fix(e2e): Update revision e2e tests
  test/e2e/revision_test.go
Labels: approved, cla: yes, lgtm, size/S

#677 chore: Cleaned up README
  README.md
  docs/DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/M

#697 chore: Cleanup templates and tuned icons
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/free-form.md
  .github/pull-request-template.md
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/L

#693 Re-enable markdown link check
  go.mod
  go.sum
  test/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#665 Add serviceaccount and resources config to cronjob source handling
  CHANGELOG.adoc
  docs/cmd/kn_source_cronjob_create.md
  docs/cmd/kn_source_cronjob_update.md
  pkg/eventing/legacysources/v1alpha1/cronjob_client.go
  pkg/kn/commands/source/cronjob/create.go
  pkg/kn/commands/source/cronjob/create_test.go
  pkg/kn/commands/source/cronjob/cronjob_test.go
  pkg/kn/commands/source/cronjob/describe.go
  pkg/kn/commands/source/cronjob/describe_test.go
  pkg/kn/commands/source/cronjob/flags.go
  pkg/kn/commands/source/cronjob/list_test.go
  pkg/kn/commands/source/cronjob/update.go
  pkg/kn/commands/source/cronjob/update_test.go
  test/e2e/cronjob_test.go
Labels: approved, cla: yes, lgtm, size/L

#701 fix(wait): Only use MODIFIED events when waiting for Read == True
  pkg/serving/v1/client.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/M

#704 Setup `./hack/update-deps.sh` so that we can auto-update CLI.
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#707 Follow up on Roland's review comment.
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, size/XS

#706 Use ko's strict mode for better errors messages
  config/release.yaml
  hack/release.sh
Labels: approved, cla: yes, lgtm, size/XS

#680 chore: Add option to generate frontmatter to gendocs.
  README.md
  hack/generate-docs.go
Labels: approved, cla: yes, lgtm, size/M

#711 golang format tools
  hack/generate-docs.go
Labels: approved, cla: yes, lgtm, size/XS

#714 fix(docs): Fix links to knative install and relative reference
  docs/DEVELOPMENT.md
  test/README.md
Labels: approved, cla: yes, lgtm, size/XS

#712 Fix spelling errors
  pkg/dynamic/client_test.go
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/source/apiserver/apiserver_test.go
  pkg/kn/commands/source/binding/describe.go
  pkg/kn/commands/source/ping/ping_test.go
Labels: approved, cla: yes, lgtm, size/S

#715 fix(docs): Revert markdown changes for cobra's auto-docs
  docs/cmd/kn.md
  docs/cmd/kn_completion.md
  docs/cmd/kn_plugin.md
  docs/cmd/kn_plugin_list.md
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_delete.md
  docs/cmd/kn_revision_describe.md
  docs/cmd/kn_revision_list.md
  docs/cmd/kn_route.md
  docs/cmd/kn_route_describe.md
  docs/cmd/kn_route_list.md
  docs/cmd/kn_service.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_list.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source.md
  docs/cmd/kn_source_apiserver.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_delete.md
  docs/cmd/kn_source_apiserver_describe.md
  docs/cmd/kn_source_apiserver_list.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_delete.md
  docs/cmd/kn_source_binding_describe.md
  docs/cmd/kn_source_binding_list.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_list-types.md
  docs/cmd/kn_source_ping.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_delete.md
  docs/cmd/kn_source_ping_describe.md
  docs/cmd/kn_source_ping_list.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_trigger.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_delete.md
  docs/cmd/kn_trigger_describe.md
  docs/cmd/kn_trigger_list.md
  docs/cmd/kn_trigger_update.md
  docs/cmd/kn_version.md
Labels: approved, cla: yes, lgtm, size/L

#709 feat(version): Add JSON/YAML output formats for version command
  CHANGELOG.adoc
  docs/cmd/kn_version.md
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
Labels: approved, cla: yes, lgtm, size/L

#703 Add option for adding labels only to service and/or template
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, size/L

#720 chore: fix a typo in pull request template
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, size/XS

#666 feat(source): Add 'kn source list'
  CHANGELOG.adoc
  docs/cmd/kn_source.md
  docs/cmd/kn_source_list.md
  go.mod
  pkg/dynamic/client.go
  pkg/dynamic/client_test.go
  pkg/dynamic/lib.go
  pkg/dynamic/lib_test.go
  pkg/kn/commands/flags/listfilters.go
  pkg/kn/commands/flags/listfilters_test.go
  pkg/kn/commands/source/duck/multisourcelist.go
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/source/list.go
  pkg/kn/commands/source/list_test.go
  pkg/kn/commands/source/list_types.go
  pkg/kn/commands/source/list_types_test.go
  pkg/kn/commands/source/source.go
  pkg/util/compare.go
  pkg/util/compare_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_list_test.go
  vendor/github.com/magiconair/properties/assert/assert.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#669 add "kn service export" (#653)
  CHANGELOG.adoc
  docs/cmd/kn_service.md
  docs/cmd/kn_service_export.md
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/export_test.go
  pkg/kn/commands/service/service.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#725 Improve reporting for missing kubeconfig and error connecting to the cluster
  CHANGELOG.adoc
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/errors/factory.go
  pkg/errors/factory_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
Labels: approved, cla: yes, lgtm, size/L

#729 chore(service export): Rename `--history` to `--with-revisions`
  docs/cmd/kn_service_export.md
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/export_test.go
Labels: approved, cla: yes, lgtm, size/S

#730 chore(e2e): Support parsing int64 user id in test verification
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/S

#726 feat(trigger): add --inject-broker flag to trigger create command
  CHANGELOG.adoc
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/kn/commands/trigger/update_flags.go
  test/e2e/trigger_inject_broker_test.go
Labels: approved, cla: yes, lgtm, size/L

#731 fix(e2e): make local-e2e-tests.sh executable
  test/local-e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#629 fixes(#606): adds --cluster-local / --no-cluster-local flags
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
  test/e2e/service_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#734 fix: typo in issue template feature-request.md file
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#735 missing paren
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
Labels: approved, cla: yes, lgtm, size/S

#727 Verify "source ping describe" in ping e2e test
  test/e2e/cli.go
  test/e2e/ping_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#736 chore: Update changelog.adoc
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/L

#742 chore: Update test-infra
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/markdown-link-check-config.rc
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/knative.dev/test-infra/scripts/release.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#739 e2e for service export
  docs/cmd/kn_service.md
  docs/cmd/kn_service_export.md
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/export_test.go
  test/e2e/service_export_import_apply_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#745 fix(trigger): Make --filter flag truly optional
  CHANGELOG.adoc
  docs/cmd/kn_trigger_create.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/describe.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/M

#746 fix(trigger): Fix filter delete for trigger update
  CHANGELOG.adoc
  pkg/eventing/v1alpha1/client.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/S

#747 fix(e2e): Fix typos in TestBrokerTrigger
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XS

#738 Run plugin on Windows
  CHANGELOG.adoc
  docs/plugins/README.md
  pkg/kn/commands/plugin/handler.go
  pkg/kn/commands/plugin/handler_test.go
  pkg/kn/commands/plugin/plugin_test_helper.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#752 fix: Fix default config path on Windows
  CHANGELOG.adoc
  pkg/kn/commands/types.go
Labels: approved, cla: yes, lgtm, size/S

#755 Replace alias `clientservingv1alpha` to `clientservingv1`
  pkg/kn/commands/revision/list.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#749 fix(trigger): Backport trigger filter fixes
  CHANGELOG.adoc
  docs/cmd/kn_trigger_create.md
  docs/plugins/README.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/plugin/handler.go
  pkg/kn/commands/plugin/handler_test.go
  pkg/kn/commands/plugin/plugin_test_helper.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/describe.go
  pkg/kn/commands/types.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#756 chore: Update dependencies on to serving and eventing
  go.mod
  go.sum
  pkg/serving/config_changes.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#759 Update test-infra to pick up the fix
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#760 chore: Fix changelog on master
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/XS
