Repository knative/client, pull requests merged in 2020-04, with the labels that each got.

#765 (refactor) address the e2e extract / refactor of issue #763
  CHANGELOG.adoc
  go.mod
  go.sum
  hack/build.sh
  lib/test/cli.go
  lib/test/flags.go
  lib/test/integration.go
  lib/test/result_collector.go
  test/e2e/basic_workflow_test.go
  test/e2e/ping_test.go
  test/e2e/plugins_test.go
  test/e2e/revision_test.go
  test/e2e/route_test.go
  test/e2e/service_export_import_apply_test.go
  test/e2e/service_options_test.go
  test/e2e/service_test.go
  test/e2e/sinkprefix_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_binding_test.go
  test/e2e/source_list_test.go
  test/e2e/tekton_test.go
  test/e2e/traffic_split_test.go
  test/e2e/trigger_inject_broker_test.go
  test/e2e/trigger_test.go
  test/e2e/version_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#771 fix(769): various issues with godoc documents
  CHANGELOG.adoc
  lib/test/cli.go
  lib/test/integration.go
  lib/test/result_collector.go
  test/e2e/service_options_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#774 fix(plugin): Fix plugin lookup with file ext on Windows
  CHANGELOG.adoc
  pkg/kn/commands/plugin/handler.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#781 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/condition_set.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#779 Remove unused variables and unreachable code
  pkg/eventing/v1alpha1/client.go
  pkg/kn/commands/describe.go
  pkg/sources/v1alpha2/binding_client.go
Labels: approved, cla: yes, lgtm, size/XS

#778 fix(issue #762): correct error message when updating service
  CHANGELOG.adoc
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#780 Add badges in README
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#783 Use vendored deps while running e2e locally
  test/local-e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#785 Update sink binding create usage string
  docs/cmd/kn_source_binding_create.md
  pkg/kn/commands/source/binding/create.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#773 fix(#772) refactored / simplified parameters to KnResultCollector
  lib/test/cli.go
  lib/test/result_collector.go
  test/e2e/basic_workflow_test.go
  test/e2e/ping_test.go
  test/e2e/plugins_test.go
  test/e2e/revision_test.go
  test/e2e/route_test.go
  test/e2e/service_export_import_apply_test.go
  test/e2e/service_options_test.go
  test/e2e/service_test.go
  test/e2e/sinkprefix_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_binding_test.go
  test/e2e/source_list_test.go
  test/e2e/tekton_test.go
  test/e2e/traffic_split_test.go
  test/e2e/trigger_inject_broker_test.go
  test/e2e/trigger_test.go
  test/e2e/version_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#784 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#770 Remove the delete propagation flag
  docs/cmd/kn_revision_delete.md
  docs/cmd/kn_service_delete.md
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
Labels: approved, cla: yes, lgtm, size/S

#788 Add target-utilization option for `service create` and `service update`
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/describe_test.go
  pkg/kn/commands/service/update_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/revision_template.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#782 Add -a flag as alias for --annotation
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/S

#791 [master] Auto-update dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/test-infra/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#775 Fix error when output is set to name
  pkg/kn/commands/flags/listprint.go
  pkg/kn/commands/flags/listprint_test.go
  pkg/kn/commands/service/list.go
  pkg/printers/tableprinter.go
  pkg/util/unstructured.go
  pkg/util/unstructured_test.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, size/L

#797 Pin serving to v0.13.2 and update version command
  go.mod
  go.sum
  pkg/kn/commands/version/version.go
  vendor/github.com/google/uuid/.travis.yml
  vendor/github.com/google/uuid/CONTRIBUTING.md
  vendor/github.com/google/uuid/CONTRIBUTORS
  vendor/github.com/google/uuid/LICENSE
  vendor/github.com/google/uuid/README.md
  vendor/github.com/google/uuid/dce.go
  vendor/github.com/google/uuid/doc.go
  vendor/github.com/google/uuid/go.mod
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/marshal.go
  vendor/github.com/google/uuid/node.go
  vendor/github.com/google/uuid/node_js.go
  vendor/github.com/google/uuid/node_net.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/time.go
  vendor/github.com/google/uuid/util.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version1.go
  vendor/github.com/google/uuid/version4.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/register.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/serverlessservice_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_conversion.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#790 Show all revisions when run `service describe -v`
  CHANGELOG.adoc
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
Labels: approved, backport/candidate, cla: yes, lgtm, ok-to-test, size/M

#766 Add e2e test for different service and revision label
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/S

#799 Fix resource listing with -oname flag
  pkg/kn/commands/revision/list.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/source/apiserver/list.go
  pkg/kn/commands/source/binding/list.go
  pkg/kn/commands/source/ping/list.go
  pkg/kn/commands/trigger/list.go
  test/e2e/ping_test.go
  test/e2e/revision_test.go
  test/e2e/route_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_binding_test.go
  test/e2e/trigger_test.go
Labels: approved, backport/candidate, cla: yes, lgtm, size/M

#802 Make wait, no-wait and async flags per bool var CLI convention
  docs/cmd/kn_revision_delete.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/service_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
  pkg/kn/flags/bool.go
  pkg/kn/flags/bool_test.go
Labels: approved, backport/candidate, cla: yes, lgtm, size/L

#794 e2e: Foreground delete for revisions and services in e2e
  test/e2e/basic_workflow_test.go
  test/e2e/revision_test.go
Labels: approved, backport/candidate, cla: yes, lgtm, size/XS

#803 e2e: Run tekton e2e against pipeline v0.11.1
  test/e2e/tekton_test.go
  test/resources/tekton/buildah.yaml
  test/resources/tekton/kn-pipeline-run.yaml
  test/resources/tekton/kn-pipeline.yaml
  test/tekton-tests.sh
Labels: approved, backport/candidate, cla: yes, lgtm, size/M

#804 Update CHANGELOG for v0.13.2
  CHANGELOG.adoc
Labels: approved, backport/candidate, cla: yes, lgtm, size/S

#807 chore(e2): Run tests against v0.14.0 release of serving, eventing
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#813 Update link of a PR in CHANGELOG
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/XS

#805 Check DeleteTimestamp before updating resource
  CHANGELOG.adoc
  pkg/kn/commands/service/update_test.go
  pkg/kn/commands/source/apiserver/update.go
  pkg/kn/commands/source/apiserver/update_test.go
  pkg/kn/commands/source/binding/update.go
  pkg/kn/commands/source/binding/update_test.go
  pkg/kn/commands/source/ping/update.go
  pkg/kn/commands/source/ping/update_test.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/trigger/update_test.go
  pkg/serving/v1/client.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#820 chore: Update changelog for 0.14.0
  CHANGELOG.adoc
  go.mod
  go.sum
  pkg/kn/commands/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
