Repository knative/client, pull requests merged in 2020-09, with the labels that each got.

#996 fix: Make API parameter type public
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
Labels: approved, cla: yes, lgtm, size/S

#1004 fix: Fix service export annotations
  pkg/kn/commands/service/export.go
  test/e2e/service_export_test.go
Labels: approved, cla: yes, lgtm, size/M

#1005 Fix channel create example with inbuilt alias for imcv1beta1
  docs/cmd/kn_channel_create.md
  pkg/kn/commands/channel/create.go
Labels: approved, cla: yes, lgtm, size/XS

#1006 fix: Fix service export example doc
  CHANGELOG.adoc
  docs/cmd/kn_service_export.md
  pkg/kn/commands/service/export.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1007 Fix a couple typos in README
  README.md
Labels: approved, cla: yes, lgtm, size/S

#990 Add changes for --scale-init support
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1012 CHANGELOG entry for PR #990
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1017 Remove -mod=readonly from the helloworld's Dockerfile
  test/test_images/helloworld/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1021 fix: Fix autoscaling annotations in Service metadata
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/L

#1019 Print logs from PipelineRun pods when Tekton tests fail
  test/e2e/tekton_test.go
Labels: approved, cla: yes, lgtm, size/S

#1030 [Automated] Fix misspellings
  CHANGELOG.adoc
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#1028 [Automated] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/test-infra/presubmit-tests.sh
  vendor/knative.dev/eventing/pkg/apis/duck/v1/fuzzer.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1beta1/subscribable_types_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/container_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1033 Pin serving and eventing to release-0.18
  go.mod
  go.sum
  hack/update-deps.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1036 chore(e2e): Run e2e against serving/eventing v0.18.0
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1029 adding annotation-service and annotation-revision to kn service create/update
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L
