Repository knative/client, pull requests merged in 2020-08, with the labels that each got.

#958 Deprecates --max-scale/--min-scale for more consistent naming
  cmd/kn/main_test.go
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/operations/autoscaling.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/M

#948 List inbuilt sources if CRD access is restricted
  pkg/dynamic/client.go
  pkg/dynamic/client_test.go
  pkg/dynamic/lib.go
  pkg/dynamic/lib_test.go
  pkg/errors/errors.go
  pkg/errors/factory.go
  pkg/errors/factory_test.go
  pkg/kn/commands/source/list.go
  pkg/kn/commands/source/list_test.go
  pkg/kn/commands/source/list_types.go
  pkg/sources/v1alpha2/apiserver_client.go
  pkg/sources/v1alpha2/client.go
  pkg/sources/v1alpha2/client_test.go
Labels: approved, cla: yes, lgtm, size/L

#966 Use Tekton Catalog GA structure for tasks
  test/e2e/tekton_test.go
Labels: approved, cla: yes, lgtm, size/S

#943 Separate PodSpec flags from Service flags
  CHANGELOG.adoc
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_test.go
Labels: approved, cla: yes, lgtm, size/L

#950 [master] Auto-update dependencies
  go.mod
  go.sum
  scripts/test-infra/COMMIT
  scripts/test-infra/e2e-tests.sh
  scripts/test-infra/library.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/zerrors_freebsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_freebsd_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_386.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm.go
  vendor/golang.org/x/sys/unix/zerrors_netbsd_arm64.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/apis/duck/proxy.go
  vendor/knative.dev/pkg/apis/duck/typed.go
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/ptr/ptr.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#963 fix: `kn source list` command print spelling problems
  pkg/kn/commands/source/list.go
  test/e2e/source_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#971 Fix exit code on service delete and revision delete
  CHANGELOG.adoc
  lib/test/revision.go
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/delete_test.go
  pkg/kn/commands/revision/revision_test.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/delete_mock_test.go
  test/e2e/service_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#972 Add mock tests for the dynamic client
  CHANGELOG.adoc
  pkg/dynamic/client_mock.go
  pkg/dynamic/client_mock_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#976 Pin knative/pkg to release-0.17
  go.mod
  go.sum
  hack/update-deps.sh
  scripts/test-infra/COMMIT
  scripts/test-infra/e2e-tests.sh
  scripts/test-infra/library.sh
  third_party/VENDOR-LICENSE/github.com/go-logr/logr/LICENSE
  third_party/VENDOR-LICENSE/k8s.io/klog/v2/LICENSE
  third_party/VENDOR-LICENSE/knative.dev/networking/pkg/apis/networking/LICENSE
  vendor/github.com/go-logr/logr/LICENSE
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/any_str.go
  vendor/github.com/json-iterator/go/config.go
  vendor/github.com/json-iterator/go/iter_object.go
  vendor/github.com/json-iterator/go/reflect_extension.go
  vendor/github.com/json-iterator/go/reflect_map.go
  vendor/github.com/json-iterator/go/reflect_optional.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/json-iterator/go/stream.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/config.go
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/increase_level.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/k8s.io/klog/v2/.gitignore
  vendor/k8s.io/klog/v2/CONTRIBUTING.md
  vendor/k8s.io/klog/v2/LICENSE
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/RELEASE.md
  vendor/k8s.io/klog/v2/SECURITY_CONTACTS
  vendor/k8s.io/klog/v2/code-of-conduct.md
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/utils/trace/README.md
  vendor/k8s.io/utils/trace/trace.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_types.go
  vendor/knative.dev/networking/pkg/apis/config/defaults.go
  vendor/knative.dev/networking/pkg/apis/config/doc.go
  vendor/knative.dev/networking/pkg/apis/config/store.go
  vendor/knative.dev/networking/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/configmap/informed_watcher.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#977 Sync knative/test-infra to latest in its release-0.17 branch
  scripts/test-infra/COMMIT
  scripts/test-infra/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#975 fix(volume): Generate volume name compliant with DNS Label names
  CHANGELOG.adoc
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, size/M

#980 Set client custom GVK for source list for machine readable output
  CHANGELOG.adoc
  pkg/dynamic/client.go
  pkg/dynamic/client_test.go
Labels: approved, cla: yes, lgtm, size/M

#982 v0.16.1 release backports
  CHANGELOG.adoc
  README.md
  lib/test/revision.go
  pkg/dynamic/client.go
  pkg/dynamic/client_test.go
  pkg/dynamic/lib.go
  pkg/dynamic/lib_test.go
  pkg/errors/errors.go
  pkg/errors/factory.go
  pkg/errors/factory_test.go
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/delete_test.go
  pkg/kn/commands/revision/revision_test.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/delete_mock_test.go
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/source/list.go
  pkg/kn/commands/source/list_test.go
  pkg/kn/commands/source/list_types.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/sources/v1alpha2/apiserver_client.go
  pkg/sources/v1alpha2/client.go
  pkg/sources/v1alpha2/client_test.go
  test/e2e/service_test.go
  test/e2e/source_list_test.go
  test/e2e/tekton_test.go
Labels: approved, backport/pr, cla: yes, lgtm, size/XL

#981 Add kafka source desc for kn source list-types
  pkg/kn/commands/source/human_readable_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#984 Vendor serving and eventing at v0.17.0
  go.mod
  go.sum
  pkg/kn/commands/version/version.go
  test/presubmit-integration-tests-latest-release.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_defaults.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/register.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#902 Add support for internal plugins
  CHANGELOG.adoc
  docs/plugins/README.md
  go.sum
  lib/test/broker.go
  pkg/kn/config/config.go
  pkg/kn/plugin/manager.go
  pkg/kn/plugin/manager_test.go
Labels: approved, cla: yes, lgtm, size/L

#991 Plugin inlining (backport)
  CHANGELOG.adoc
  docs/plugins/README.md
  go.sum
  lib/test/broker.go
  pkg/kn/config/config.go
  pkg/kn/plugin/manager.go
  pkg/kn/plugin/manager_test.go
Labels: approved, backport/pr, cla: yes, lgtm, size/L

#967 feat(channel): Manage knative eventing channels
  CHANGELOG.adoc
  docs/cmd/kn.md
  docs/cmd/kn_channel.md
  docs/cmd/kn_channel_create.md
  docs/cmd/kn_channel_delete.md
  docs/cmd/kn_channel_describe.md
  docs/cmd/kn_channel_list.md
  lib/test/channel.go
  pkg/errors/factory.go
  pkg/errors/factory_test.go
  pkg/kn/commands/channel/channel.go
  pkg/kn/commands/channel/channel_test.go
  pkg/kn/commands/channel/create.go
  pkg/kn/commands/channel/create_test.go
  pkg/kn/commands/channel/delete.go
  pkg/kn/commands/channel/delete_test.go
  pkg/kn/commands/channel/describe.go
  pkg/kn/commands/channel/describe_test.go
  pkg/kn/commands/channel/flags.go
  pkg/kn/commands/channel/list.go
  pkg/kn/commands/channel/list_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  pkg/kn/config/config.go
  pkg/kn/config/config_test.go
  pkg/kn/config/testing.go
  pkg/kn/config/testing_test.go
  pkg/kn/config/types.go
  pkg/kn/flags/channel_types.go
  pkg/kn/flags/channel_types_test.go
  pkg/kn/root/root.go
  pkg/messaging/v1beta1/channels_client.go
  pkg/messaging/v1beta1/channels_client_mock.go
  pkg/messaging/v1beta1/client.go
  test/e2e/channels_test.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/channel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/inmemorychannel.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/messaging_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/messaging/v1beta1/subscription.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#992 update changelog for 0.17.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M
