Repository knative/client, pull requests merged in 2020-12, with the labels that each got.

#1156 fix(release): Fix checksum quoting
  hack/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1158 remove unnecessary help message
  CHANGELOG.adoc
  pkg/kn/commands/source/binding/describe.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1147 Remove unwanted var in hack/build.sh
  hack/build.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1159 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1016 Add command group for ContainerSource
  docs/cmd/kn_source.md
  docs/cmd/kn_source_container.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_delete.md
  docs/cmd/kn_source_container_describe.md
  docs/cmd/kn_source_container_list.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/commands/source/container/container.go
  pkg/kn/commands/source/container/container_test.go
  pkg/kn/commands/source/container/create.go
  pkg/kn/commands/source/container/create_test.go
  pkg/kn/commands/source/container/delete.go
  pkg/kn/commands/source/container/delete_test.go
  pkg/kn/commands/source/container/describe.go
  pkg/kn/commands/source/container/describe_test.go
  pkg/kn/commands/source/container/human_readable_flags.go
  pkg/kn/commands/source/container/list.go
  pkg/kn/commands/source/container/list_test.go
  pkg/kn/commands/source/container/update.go
  pkg/kn/commands/source/container/update_test.go
  pkg/kn/commands/source/source.go
  pkg/kn/flags/podspec.go
  pkg/sources/v1alpha2/client.go
  pkg/sources/v1alpha2/container_client.go
  pkg/sources/v1alpha2/container_client_mock.go
  pkg/sources/v1alpha2/container_client_mock_test.go
  pkg/sources/v1alpha2/container_client_test.go
  test/e2e/source_container_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1163 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1164 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/.gitignore
  vendor/github.com/blendle/zapdriver/LICENSE
  vendor/github.com/blendle/zapdriver/README.md
  vendor/github.com/blendle/zapdriver/config.go
  vendor/github.com/blendle/zapdriver/core.go
  vendor/github.com/blendle/zapdriver/encoder.go
  vendor/github.com/blendle/zapdriver/go.mod
  vendor/github.com/blendle/zapdriver/go.sum
  vendor/github.com/blendle/zapdriver/http.go
  vendor/github.com/blendle/zapdriver/label.go
  vendor/github.com/blendle/zapdriver/logger.go
  vendor/github.com/blendle/zapdriver/operation.go
  vendor/github.com/blendle/zapdriver/report.go
  vendor/github.com/blendle/zapdriver/service.go
  vendor/github.com/blendle/zapdriver/source.go
  vendor/github.com/blendle/zapdriver/trace.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1166 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1167 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/S

#1168 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1170 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle_mt.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_lifecycle_mt.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/parallel_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/test_helpers.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/parallel_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_defaults.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/sequence_validation.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1beta1/test_helpers.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1171 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1174 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1173 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/M

#1176 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1177 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
