Repository knative/client, pull requests merged in 2020-10, with the labels that each got.

#1038 Update error message when autoscaling annotation used in service
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1013 feat: Subscription CRUD
  CHANGELOG.adoc
  docs/cmd/kn.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_delete.md
  docs/cmd/kn_subscription_describe.md
  docs/cmd/kn_subscription_list.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  lib/printing/describe.go
  lib/test/subscription.go
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/subscription/create.go
  pkg/kn/commands/subscription/create_test.go
  pkg/kn/commands/subscription/delete.go
  pkg/kn/commands/subscription/delete_test.go
  pkg/kn/commands/subscription/describe.go
  pkg/kn/commands/subscription/describe_test.go
  pkg/kn/commands/subscription/flags.go
  pkg/kn/commands/subscription/list.go
  pkg/kn/commands/subscription/list_test.go
  pkg/kn/commands/subscription/subscription.go
  pkg/kn/commands/subscription/subscription_test.go
  pkg/kn/commands/subscription/update.go
  pkg/kn/commands/subscription/update_test.go
  pkg/kn/flags/channel_types.go
  pkg/kn/flags/channel_types_test.go
  pkg/kn/root/root.go
  pkg/messaging/v1beta1/client.go
  pkg/messaging/v1beta1/subscriptions_client.go
  pkg/messaging/v1beta1/subscriptions_client_mock.go
  test/e2e/subscription_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1040 [v0.17.1]: Backport PR for v0.17.1
  CHANGELOG.adoc
  docs/cmd/kn.md
  docs/cmd/kn_channel_create.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_delete.md
  docs/cmd/kn_subscription_describe.md
  docs/cmd/kn_subscription_list.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  lib/printing/describe.go
  lib/test/subscription.go
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/channel/create.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/subscription/create.go
  pkg/kn/commands/subscription/create_test.go
  pkg/kn/commands/subscription/delete.go
  pkg/kn/commands/subscription/delete_test.go
  pkg/kn/commands/subscription/describe.go
  pkg/kn/commands/subscription/describe_test.go
  pkg/kn/commands/subscription/flags.go
  pkg/kn/commands/subscription/list.go
  pkg/kn/commands/subscription/list_test.go
  pkg/kn/commands/subscription/subscription.go
  pkg/kn/commands/subscription/subscription_test.go
  pkg/kn/commands/subscription/update.go
  pkg/kn/commands/subscription/update_test.go
  pkg/kn/flags/channel_types.go
  pkg/kn/flags/channel_types_test.go
  pkg/kn/root/root.go
  pkg/messaging/v1beta1/client.go
  pkg/messaging/v1beta1/subscriptions_client.go
  pkg/messaging/v1beta1/subscriptions_client_mock.go
  test/e2e/subscription_test.go
Labels: approved, backport/pr, cla: yes, lgtm, size/XXL

#1037 chore: Update version command for release v0.18.0
  pkg/kn/commands/version/version.go
Labels: approved, cla: yes, lgtm, size/XS

#1044 fix(e2e): Let the subscription and related resource reconcile
  lib/test/subscription.go
Labels: approved, cla: yes, lgtm, size/XS

#1046 fix(e2e): Run eventing e2e tests only against nightly and fix service export tests
  test/e2e/service_export_test.go
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/S

#1010 Added back functionality to deprecated max-scale/min-scale
  pkg/kn/commands/service/configuration_edit_flags.go
Labels: approved, backport/candidate, cla: yes, lgtm, size/XS

#1027 feat: List available channel types
  CHANGELOG.adoc
  docs/cmd/kn_channel.md
  docs/cmd/kn_channel_list-types.md
  lib/test/channel.go
  pkg/dynamic/client.go
  pkg/dynamic/client_mock.go
  pkg/dynamic/client_mock_test.go
  pkg/dynamic/client_test.go
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/channel/channel.go
  pkg/kn/commands/channel/flags.go
  pkg/kn/commands/channel/list_types.go
  pkg/kn/commands/channel/list_types_test.go
  pkg/messaging/v1beta1/client.go
  test/e2e/channels_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1049 Carry CHANGELOG from v0.17.1 patch release
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/S

#1050 Update CHANGELOG.adoc for version 0.18.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#1048 [0.17] Backport 1044 and 10101
  CHANGELOG.adoc
  lib/test/subscription.go
  pkg/kn/commands/service/configuration_edit_flags.go
Labels: approved, backport/pr, cla: yes, lgtm, size/S

#1051 fix(e2e): Skip service export test
  test/e2e/service_export_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1052 Fix for test flake when sync waiting and an intermediate error occurs
  go.sum
  lib/test/result_collector.go
  pkg/wait/wait_for_ready.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1056 fix(docs): Fix message broker doc
  docs/cmd/kn.md
  docs/cmd/kn_broker.md
  docs/cmd/kn_broker_create.md
  docs/cmd/kn_broker_delete.md
  docs/cmd/kn_broker_describe.md
  docs/cmd/kn_broker_list.md
  pkg/kn/commands/broker/broker.go
Labels: approved, cla: yes, lgtm, size/S

#1054 Add WithLabel list filter to serving client lib
  CHANGELOG.adoc
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock_test.go
  pkg/serving/v1/client_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1058 [release-0.17] Backport #1052 and #1054
  CHANGELOG.adoc
  go.sum
  lib/test/result_collector.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock_test.go
  pkg/serving/v1/client_test.go
  pkg/wait/wait_for_ready.go
Labels: approved, backport/pr, cla: yes, lgtm, size/L

#1059 [release-0.18] Backport #1052 and #1054
  CHANGELOG.adoc
  go.sum
  lib/test/result_collector.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock_test.go
  pkg/serving/v1/client_test.go
  pkg/wait/wait_for_ready.go
Labels: approved, backport/pr, cla: yes, lgtm, size/L

#1060 Update CHANGELOG
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/S

#1057 Fix various misspellings and linter items
  .github/pull-request-template.md
  CHANGELOG.adoc
  cmd/kn/main_test.go
  conventions/cli.md
  conventions/client.md
  docs/README.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_binding_list.md
  docs/operations/autoscaling.md
  docs/workflows/basic.md
  lib/test/capture_output.go
  lib/test/cli.go
  lib/test/integration.go
  lib/test/result_collector.go
  pkg/dynamic/client.go
  pkg/dynamic/client_mock.go
  pkg/dynamic/client_mock_test.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/commands/source/binding/list.go
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/subscription/flags.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/version/version_test.go
  pkg/kn/config/config.go
  pkg/kn/flags/channel_types.go
  pkg/kn/flags/podspec.go
  pkg/kn/plugin/manager.go
  pkg/kn/traffic/compute.go
  pkg/kn/traffic/compute_test.go
  pkg/messaging/v1beta1/client.go
  pkg/serving/v1/client_mock.go
  pkg/util/compare.go
  pkg/util/unstructured.go
  pkg/util/unstructured_test.go
  pkg/wait/test_wait_helper.go
  scripts/test-infra/library.sh
  scripts/test-infra/performance-tests.sh
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1061 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1067 fix(e2e): Remove "serving.knative.dev/route" revision label
  test/e2e/service_export_test.go
Labels: approved, cla: yes, lgtm, size/XS

#1062 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  scripts/test-infra/library.sh
  scripts/test-infra/performance-tests.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1064 Fix bogus warning in build.sh
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#1063 chore(e2e): Run e2e against eventing v0.18.3
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1068 Fix golangci-lint errors
  pkg/dynamic/client_test.go
  pkg/kn/commands/channel/list_types_test.go
  pkg/kn/commands/subscription/flags.go
  pkg/kn/flags/channel_types.go
  pkg/messaging/v1beta1/subscriptions_client_mock.go
Labels: approved, cla: yes, lgtm, size/M

#1072 [Automated] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1074 fix(tekton e2e): Fix CONTAINER_REGISTRY name generation
  test/tekton-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1024 Add ResolvePodSpec to podspec.go and move the related utilities to podspec_helper
  CHANGELOG.adoc
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/kn/flags/podspec_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/util/corev1_helper.go
  pkg/util/corev1_helper_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#1081 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1075 Uniform multiple writeSink(s) to DescribeSink
  CHANGELOG.adoc
  lib/printing/describe.go
  pkg/kn/commands/source/apiserver/describe.go
  pkg/kn/commands/source/binding/describe.go
  pkg/kn/commands/source/ping/describe.go
  pkg/kn/commands/trigger/describe.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1084 updating to use the hack repo
  go.mod
  go.sum
  hack/build.sh
  hack/release.sh
  hack/tools.go
  hack/update-codegen.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  scripts/test-infra/COMMIT
  scripts/test-infra/markdown-link-check-config.rc
  scripts/test-infra/markdown-lint-config.rc
  scripts/test-infra/update-test-infra.sh
  test/common.sh
  test/presubmit-tests.sh
  vendor/github.com/grpc-ecosystem/grpc-gateway/internal/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/BUILD.bazel
  vendor/github.com/grpc-ecosystem/grpc-gateway/utilities/BUILD.bazel
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/hack/LICENSE
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/go.mod
  vendor/knative.dev/hack/hack.go
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/performance-tests.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/hack/shellcheck-presubmit.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL
