Repository knative/client, pull requests merged in 2020-07, with the labels that each got.

#917 Use broker injection label key from trigger types
  lib/test/broker.go
Labels: approved, cla: yes, lgtm, size/S

#920 Setup eventing extension: sugar controller
  test/common.sh
Labels: approved, cla: yes, lgtm, size/XS

#916 Add support for service url in svc describe output
  CHANGELOG.adoc
  docs/cmd/kn_service_describe.md
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#919 Fixed the error message for min/max scale tests
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
Labels: approved, cla: yes, lgtm, size/XS

#921 Pin to knative.dev/{pkg,eventing,serving}@release-16
  hack/update-deps.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#915 add port name
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, size/L

#913 feat: Add --filename flag to service create command
  docs/cmd/kn_service_create.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_test.go
  test/e2e/service_file_test.go
Labels: approved, cla: yes, lgtm, size/L

#914 Added the option to use --scale for setting MinScale and MaxScale to the same value
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/L

#924 Add E2E test cases for "kn source list".
  test/e2e/source_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#926 Update CHANGELOG and error for port flag parsing
  CHANGELOG.adoc
  pkg/serving/config_changes.go
Labels: approved, cla: yes, lgtm, size/XS

#896 Revisit sink prefixes: Support only 'ksvc' prefix and drop 'svc', 'service' support for knative service
  CHANGELOG.adoc
  conventions/cli.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/source/apiserver/list_test.go
  pkg/kn/commands/source/apiserver/update.go
  pkg/kn/commands/source/apiserver/update_test.go
  pkg/kn/commands/source/binding/create.go
  pkg/kn/commands/source/binding/create_test.go
  pkg/kn/commands/source/binding/update_test.go
  pkg/kn/commands/source/duck/multisourcelist_test.go
  pkg/kn/commands/source/list_test.go
  pkg/kn/commands/source/ping/create.go
  pkg/kn/commands/source/ping/create_test.go
  pkg/kn/commands/source/ping/flags.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/trigger/update_test.go
  test/e2e/ping_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_binding_test.go
  test/e2e/source_list_test.go
  test/e2e/trigger_inject_broker_test.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#929 feat: Add plugin listing to "kn --help"
  CHANGELOG.adoc
  cmd/kn/main.go
  cmd/kn/main_test.go
  hack/build.sh
  hack/generate-docs.go
  pkg/kn/plugin/manager.go
  pkg/kn/plugin/manager_test.go
  pkg/kn/root/root.go
  pkg/kn/root/root_test.go
  pkg/templates/command_groups.go
  pkg/templates/command_groups_test.go
  pkg/templates/template_engine.go
  pkg/templates/template_engine_test.go
  pkg/templates/templates.go
  test/e2e/plugins_test.go
Labels: approved, cla: yes, lgtm, size/L

#931 Release preps for 0.16.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#934 fix(docs): Fix tekton task link
  README.md
Labels: approved, cla: yes, lgtm, size/XS

#937 feat: Add support to combine service create --filename with other options
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#944 Upgrade spf13/cobra dep to current master
  cmd/kn/main.go
  cmd/kn/main_test.go
  go.mod
  go.sum
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/custom_completions.go
  vendor/github.com/spf13/cobra/doc/README.md
  vendor/github.com/spf13/cobra/doc/man_docs.go
  vendor/github.com/spf13/cobra/doc/md_docs.md
  vendor/github.com/spf13/cobra/doc/yaml_docs.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#945 Remove unrelated file
  users.htpasswd
Labels: approved, cla: yes, lgtm, size/XS

#951 Fix missing NAMESPACE column header
  CHANGELOG.adoc
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/source/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#957 allow test image to be customized
  CHANGELOG.adoc
  lib/test/integration.go
  lib/test/service.go
  test/e2e-tests.sh
  test/e2e/service_export_test.go
  test/e2e/service_file_test.go
  test/e2e/service_options_test.go
  test/e2e/service_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
