Repository knative/client, pull requests merged in 2020-02, with the labels that each got.

#630 Show envFrom when running describe service or revision
  CHANGELOG.adoc
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/describe_test.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#635 Add support for command and args in service create
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#637 Add e2e test for cmd and arg options
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/S

#642 fix(serving): Fix test method wording
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, size/S

#644 fix(serving): Add an error window for ReadyCondition
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/M

#634 Add E2E test for "kn source binding" commands
  CHANGELOG.adoc
  docs/cmd/kn_source_binding_create.md
  pkg/kn/commands/source/binding/create.go
  test/e2e/source_binding_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#639 Rename --async to --no-wait and deprecate it
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
  test/e2e-smoke-tests.sh
Labels: approved, cla: yes, lgtm, size/L

#638 Fix capitalization of generated flags
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/flags/bool.go
Labels: approved, cla: yes, lgtm, size/S

#643 Implement human readable output for kn route describe
  CHANGELOG.adoc
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_describe.md
  docs/cmd/kn_route.md
  docs/cmd/kn_route_describe.md
  docs/cmd/kn_service.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_source_apiserver.md
  docs/cmd/kn_source_apiserver_describe.md
  docs/cmd/kn_source_binding.md
  docs/cmd/kn_source_binding_describe.md
  docs/cmd/kn_source_cronjob.md
  docs/cmd/kn_source_cronjob_describe.md
  docs/cmd/kn_trigger.md
  docs/cmd/kn_trigger_describe.md
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/describe_test.go
  pkg/kn/commands/route/describe.go
  pkg/kn/commands/route/describe_test.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
  pkg/kn/commands/source/apiserver/describe.go
  pkg/kn/commands/source/binding/describe.go
  pkg/kn/commands/source/cronjob/describe.go
  pkg/kn/commands/trigger/describe.go
  pkg/printers/prefixwriter.go
  test/e2e/route_test.go
Labels: approved, cla: yes, lgtm, size/L

#656 fix(#632): refactored UT to remove need of specifying sync twice
  CHANGELOG.adoc
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
Labels: approved, cla: yes, lgtm, size/L

#647 Fix --image flag to only allow single occurence
  CHANGELOG.adoc
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
Labels: approved, cla: yes, lgtm, size/M

#645 Add E2E tests for trigger
  pkg/kn/commands/trigger/trigger.go
  pkg/kn/commands/trigger/update.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#659 e2e: Dump stdout and describe ksvc
  test/e2e/common.go
Labels: approved, cla: yes, lgtm, size/S

#658 Harmonize list headers for trigger and sources
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/source/apiserver/flags.go
  pkg/kn/commands/source/apiserver/list_test.go
  pkg/kn/commands/source/binding/binding.go
  pkg/kn/commands/source/binding/flags.go
  pkg/kn/commands/source/binding/list_test.go
  pkg/kn/commands/source/cronjob/flags.go
  pkg/kn/commands/source/cronjob/list_test.go
  pkg/kn/commands/trigger/list_flags.go
  pkg/kn/commands/trigger/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#663 Add description for PingSource for 'kn source list-types'
  pkg/kn/commands/source/human_readable_flags.go
Labels: approved, cla: yes, lgtm, size/XS

#664 fix(help): initialize default help cmd early
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, size/XS

#661 fix(service wait): Wrong check for error window
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/M

#657 Support multiple arguments on revision delete
  CHANGELOG.adoc
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/delete_test.go
  test/e2e/revision_test.go
Labels: approved, cla: yes, lgtm, size/M

#660 feature(service update): Add generic mechanism to include retries on conflicts
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
Labels: approved, cla: yes, lgtm, size/L

#667 chore(e2e): Refactor to better track errors
  go.mod
  go.sum
  test/e2e/basic_workflow_test.go
  test/e2e/cli.go
  test/e2e/common.go
  test/e2e/cronjob_test.go
  test/e2e/e2e.go
  test/e2e/env.go
  test/e2e/kn.go
  test/e2e/kubectl.go
  test/e2e/plugins_test.go
  test/e2e/revision_test.go
  test/e2e/route_test.go
  test/e2e/service_options_test.go
  test/e2e/service_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_binding_test.go
  test/e2e/source_list_types_test.go
  test/e2e/tekton_test.go
  test/e2e/traffic_split_test.go
  test/e2e/trigger_test.go
  test/e2e/version_test.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/go.mod
  vendor/contrib.go.opencensus.io/exporter/stackdriver/go.sum
  vendor/contrib.go.opencensus.io/exporter/stackdriver/stackdriver.go
  vendor/contrib.go.opencensus.io/exporter/stackdriver/trace.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#672 Prevent service-specific labels from being put on the revision template
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, size/M

#670 chore(e2e): Minor cleanup
  pkg/serving/v1/client.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/S

#681 chore: Fix formatting error in changelog
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/XS

#684 fix typo in source list-types examples
  docs/cmd/kn_revision_list.md
  docs/cmd/kn_route_list.md
  docs/cmd/kn_source_apiserver_list.md
  docs/cmd/kn_source_binding_list.md
  docs/cmd/kn_source_cronjob_list.md
  docs/cmd/kn_source_list-types.md
  pkg/kn/commands/revision/list.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/source/apiserver/list.go
  pkg/kn/commands/source/binding/list.go
  pkg/kn/commands/source/cronjob/list.go
  pkg/kn/commands/source/list_types.go
Labels: approved, cla: yes, lgtm, size/M

#682 feat(wait): add wait for delete operation
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/delete_mock_test.go
  pkg/kn/commands/service/delete_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/wait_flags.go
  pkg/kn/commands/wait_flags_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
  pkg/serving/v1/client_mock_test.go
  pkg/serving/v1/client_test.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/L

#685 Disable markdown link check and enable presubmit test fail fast
  docs/README.md
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#687 chore(e2e): Increase e2e timeout to 45 minutes
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#676 Allow configuration sink prefixes
  CHANGELOG.adoc
  docs/README.md
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/types.go
  pkg/kn/core/root.go
  test/e2e/sinkprefix_test.go
Labels: approved, cla: yes, lgtm, size/L

#690 Fix for the failure of trigger e2e test
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/S

#679 Add --user flag for service create and update
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#668 feat(XDG home): use XDG_CONFIG_HOME as default config location
  docs/README.md
  docs/cmd/kn.md
  docs/cmd/kn_completion.md
  docs/cmd/kn_plugin.md
  docs/cmd/kn_plugin_list.md
  docs/cmd/kn_revision.md
  docs/cmd/kn_revision_delete.md
  docs/cmd/kn_revision_describe.md
  docs/cmd/kn_revision_list.md
  docs/cmd/kn_route.md
  docs/cmd/kn_route_describe.md
  docs/cmd/kn_route_list.md
  docs/cmd/kn_service.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_list.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source.md
  docs/cmd/kn_source_apiserver.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_delete.md
  docs/cmd/kn_source_apiserver_describe.md
  docs/cmd/kn_source_apiserver_list.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_delete.md
  docs/cmd/kn_source_binding_describe.md
  docs/cmd/kn_source_binding_list.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_cronjob.md
  docs/cmd/kn_source_cronjob_create.md
  docs/cmd/kn_source_cronjob_delete.md
  docs/cmd/kn_source_cronjob_describe.md
  docs/cmd/kn_source_cronjob_list.md
  docs/cmd/kn_source_cronjob_update.md
  docs/cmd/kn_source_list-types.md
  docs/cmd/kn_trigger.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_delete.md
  docs/cmd/kn_trigger_describe.md
  docs/cmd/kn_trigger_list.md
  docs/cmd/kn_trigger_update.md
  docs/cmd/kn_version.md
  pkg/kn/commands/plugin/list.go
  pkg/kn/commands/plugin/plugin.go
  pkg/kn/commands/plugin/plugin_test.go
  pkg/kn/commands/testing_helper.go
  pkg/kn/commands/types.go
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, size/L

#688 feat(wait): add sync revision delete operation
  docs/cmd/kn_revision_delete.md
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/delete_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
  pkg/serving/v1/client_mock_test.go
Labels: approved, cla: yes, lgtm, size/M

#692 add e2e for user flag
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS
