Repository knative/client, pull requests merged in 2020-05, with the labels that each got.

#819 refactor kn service export to export revisions
  docs/cmd/kn_service_export.md
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/export_test.go
  test/e2e/service_export_import_apply_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#826 Correct Typo in Pull Request Template
  .github/pull-request-template.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#818 fixes(#814) allow plugins to extend the 'source' command group
  CHANGELOG.adoc
  pkg/kn/commands/plugin/list_test.go
  pkg/kn/commands/plugin/plugin.go
  pkg/kn/commands/plugin/plugin_test.go
  pkg/kn/commands/plugin/verifier.go
  pkg/kn/commands/plugin/verifier_test.go
  pkg/kn/core/root.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#825 Skip LatestReadyRevisionName if Revision is Pending or Unknown
  CHANGELOG.adoc
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#831 chore: Reworked CLI conventions and include more details
  conventions/cli.md
Labels: approved, cla: yes, lgtm, size/L

#832 fix(e2e): Refactor e2e utils and resource actions
  lib/test/revision.go
  lib/test/service.go
  lib/test/utils.go
  test/e2e/basic_workflow_test.go
  test/e2e/ping_test.go
  test/e2e/revision_test.go
  test/e2e/route_test.go
  test/e2e/service_export_import_apply_test.go
  test/e2e/service_options_test.go
  test/e2e/service_test.go
  test/e2e/sinkprefix_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_binding_test.go
  test/e2e/traffic_split_test.go
  test/e2e/trigger_inject_broker_test.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/XL

#833 [master] Format markdown
  conventions/cli.md
Labels: approved, cla: yes, lgtm, size/L

#836 Add kn service delete --all
  CHANGELOG.adoc
  docs/cmd/kn_service_delete.md
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/delete_mock_test.go
  pkg/kn/commands/service/list_mock_test.go
  test/e2e/service_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#835 fix(e2e): Create next namespace for e2e if one exists
  lib/test/integration.go
  lib/test/utils.go
  test/e2e/plugins_test.go
  test/e2e/sinkprefix_test.go
Labels: approved, cla: yes, lgtm, size/M

#837 Refactor kn service delete --all e2e test
  CHANGELOG.adoc
  test/e2e/service_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#844 Update kn_completion.md
  docs/cmd/kn_completion.md
  pkg/kn/commands/completion/completion.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#848 Fix Panic for kn source ping describe with Sink URI
  CHANGELOG.adoc
  pkg/kn/commands/source/ping/describe.go
  pkg/kn/commands/source/ping/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#840 Fix test infra
  hack/release.sh
  hack/update-deps.sh
  hack/verify-codegen.sh
  scripts/test-infra/COMMIT
  scripts/test-infra/README.md
  scripts/test-infra/dummy.go
  scripts/test-infra/e2e-tests.sh
  scripts/test-infra/library.sh
  scripts/test-infra/markdown-link-check-config.rc
  scripts/test-infra/markdown-lint-config.rc
  scripts/test-infra/performance-tests.sh
  scripts/test-infra/presubmit-tests.sh
  scripts/test-infra/release.sh
  scripts/test-infra/shellcheck-presubmit.sh
  scripts/test-infra/update-test-infra.sh
  test/common.sh
  test/presubmit-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#853 Replace pkg/errors with stdlib errors.
  CHANGELOG.adoc
  go.mod
  lib/test/cli.go
  lib/test/integration.go
  pkg/kn/commands/plugin/verifier.go
  pkg/kn/commands/plugin/verifier_windows.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/delete_test.go
  pkg/kn/commands/trigger/update_flags.go
  pkg/serving/v1/client.go
  test/e2e/source_apiserver_test.go
Labels: approved, cla: yes, lgtm, size/M

#851 Remove Use of os.Exit() and Return Error Instead
  cmd/kn/main.go
  pkg/kn/commands/plugin/handler.go
  pkg/kn/core/root.go
  pkg/kn/core/root_test.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#861 Update Tekton resources to v1beta1
  test/e2e/tekton_test.go
  test/resources/tekton/kn-pipeline-run-template.yaml
  test/resources/tekton/kn-pipeline.yaml
  test/resources/tekton/resources.yaml
  test/tekton-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#862 docs: Update kn service create examples with real image
  docs/cmd/kn_service_create.md
  docs/operations/management.md
  pkg/kn/commands/service/create.go
Labels: approved, cla: yes, lgtm, size/M

#859 Add --requests and --limits resource flags
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  lib/test/service.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/flags/resources.go
  pkg/kn/flags/resources_test.go
  pkg/serving/config_changes.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/XL

#864 Add description for ContainerSource
  pkg/kn/commands/source/human_readable_flags.go
Labels: approved, cla: yes, lgtm, size/XS
