Repository knative/client, pull requests merged in 2020-06, with the labels that each got.

#865 Add --ce-override flag for apiserver and ping sources
  CHANGELOG.adoc
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  pkg/kn/commands/source/apiserver/apiserver_test.go
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/source/apiserver/describe.go
  pkg/kn/commands/source/apiserver/describe_test.go
  pkg/kn/commands/source/apiserver/flags.go
  pkg/kn/commands/source/apiserver/list_test.go
  pkg/kn/commands/source/apiserver/update.go
  pkg/kn/commands/source/apiserver/update_test.go
  pkg/kn/commands/source/binding/binding.go
  pkg/kn/commands/source/binding/binding_test.go
  pkg/kn/commands/source/binding/create.go
  pkg/kn/commands/source/binding/flags.go
  pkg/kn/commands/source/binding/update.go
  pkg/kn/commands/source/binding/update_test.go
  pkg/kn/commands/source/ping/create.go
  pkg/kn/commands/source/ping/create_test.go
  pkg/kn/commands/source/ping/describe.go
  pkg/kn/commands/source/ping/describe_test.go
  pkg/kn/commands/source/ping/flags.go
  pkg/kn/commands/source/ping/list_test.go
  pkg/kn/commands/source/ping/ping_test.go
  pkg/kn/commands/source/ping/update.go
  pkg/kn/commands/source/ping/update_test.go
  pkg/sources/v1alpha2/apiserver_client.go
  pkg/sources/v1alpha2/apiserver_client_test.go
  pkg/sources/v1alpha2/binding_client.go
  pkg/sources/v1alpha2/binding_client_test.go
  pkg/sources/v1alpha2/ping_client.go
  pkg/sources/v1alpha2/ping_client_test.go
  pkg/util/parsing_helper.go
Labels: approved, cla: yes, lgtm, size/L

#834 fixes(#827): allow plugins to extend all command groups
  CHANGELOG.adoc
  pkg/kn/commands/plugin/plugin.go
  pkg/kn/commands/plugin/plugin_test.go
  pkg/kn/commands/plugin/verifier.go
  pkg/kn/core/root.go
  pkg/kn/core/root_test.go
  test/e2e/basic_workflow_test.go
  test/e2e/plugins_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#860 Check deletionTimestamp for "kn revision delete"
  pkg/serving/v1/client.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#867 chore: Remove OWNERS files in vendor/ when updating deps
  hack/build.sh
  hack/update-deps.sh
  vendor/k8s.io/apimachinery/pkg/api/errors/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/meta/OWNERS
  vendor/k8s.io/apimachinery/pkg/api/resource/OWNERS
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/client-go/pkg/apis/clientauthentication/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/gcp/OWNERS
  vendor/k8s.io/client-go/plugin/pkg/client/auth/oidc/OWNERS
  vendor/k8s.io/client-go/rest/OWNERS
  vendor/k8s.io/client-go/tools/auth/OWNERS
  vendor/k8s.io/client-go/tools/cache/OWNERS
  vendor/k8s.io/client-go/tools/metrics/OWNERS
  vendor/k8s.io/client-go/transport/OWNERS
  vendor/k8s.io/client-go/util/cert/OWNERS
  vendor/k8s.io/client-go/util/keyutil/OWNERS
  vendor/k8s.io/client-go/util/retry/OWNERS
  vendor/k8s.io/klog/OWNERS
  vendor/k8s.io/kube-openapi/pkg/util/proto/OWNERS
  vendor/knative.dev/pkg/apis/OWNERS
  vendor/knative.dev/pkg/apis/duck/OWNERS
  vendor/knative.dev/pkg/configmap/OWNERS
  vendor/knative.dev/pkg/kmeta/OWNERS
  vendor/knative.dev/pkg/logging/OWNERS
  vendor/knative.dev/serving/pkg/apis/autoscaling/OWNERS
  vendor/knative.dev/serving/pkg/apis/networking/OWNERS
  vendor/sigs.k8s.io/yaml/OWNERS
Labels: approved, cla: yes, lgtm, size/L

#846 Fix kn source -h
  pkg/kn/commands/plugin/handler.go
  pkg/kn/commands/plugin/handler_test.go
  pkg/kn/core/root.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#868 chore(e2e): Run tests against serving and eventing 0.15 release
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#869 chore: Preps for release 0.15.0
  CHANGELOG.adoc
  go.mod
  go.sum
  hack/update-deps.sh
  pkg/kn/commands/version/version.go
  scripts/test-infra/COMMIT
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#870 chore: Unpin dependencies to follow master again
  go.mod
  go.sum
  hack/update-deps.sh
  scripts/test-infra/COMMIT
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/broker_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/register.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/config/store.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/in_memory_channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/container_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/sinkbinding_types.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/configmap/store.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/logging/config
  vendor/knative.dev/pkg/logging/object_encoders.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/config/store.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#872 Update flag names to --request and --limit
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/flags/resources.go
  pkg/kn/flags/resources_test.go
  pkg/serving/config_changes.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/L

#873 release(0.15.1): Backport fix for resource flags names
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/flags/resources.go
  pkg/kn/flags/resources_test.go
  pkg/serving/config_changes.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/L

#876 Update test-infra to stop using serving.yaml
  scripts/test-infra/COMMIT
  scripts/test-infra/library.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/S

#866 Update go.mod to specify the module is go1.14
  go.mod
  hack/build.sh
  hack/verify-codegen.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#883 Fix build.sh for macOs users
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/S

#880 Return Error Message from Using --untag with Nonexistent Tag
  CHANGELOG.adoc
  lib/test/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/traffic/compute.go
  pkg/kn/traffic/compute_test.go
  test/e2e/service_test.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#886 v0.15.2 release backports
  CHANGELOG.adoc
  go.mod
  hack/build.sh
  hack/verify-codegen.sh
  lib/test/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/traffic/compute.go
  pkg/kn/traffic/compute_test.go
  test/e2e/service_test.go
  test/e2e/traffic_split_test.go
  vendor/modules.txt
Labels: approved, backport/pr, cla: yes, lgtm, size/L

#893 chore: add missing CHANGELOG entry for grouped help messages
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/XS

#895 Refer broker from v1beta1 APIs and add missing e2e tests
  lib/test/broker.go
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  test/e2e/sink_test.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#897 Carry CHANGELOG of v0.15.2 release to master
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/S

#900 Fix Panic for kn trigger describe with Sink URI
  CHANGELOG.adoc
  pkg/kn/commands/trigger/describe.go
  pkg/kn/commands/trigger/describe_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#903 fix: Add mandatory --sink to ping source command's name
  docs/cmd/kn_source_ping_create.md
  pkg/kn/commands/source/ping/create.go
Labels: approved, cla: yes, lgtm, size/XS

#894 Add broker create, delete and list cmds
  docs/cmd/kn.md
  docs/cmd/kn_broker.md
  docs/cmd/kn_broker_create.md
  docs/cmd/kn_broker_delete.md
  docs/cmd/kn_broker_describe.md
  docs/cmd/kn_broker_list.md
  pkg/eventing/v1beta1/client.go
  pkg/eventing/v1beta1/client_mock.go
  pkg/eventing/v1beta1/client_mock_test.go
  pkg/eventing/v1beta1/client_test.go
  pkg/kn/commands/broker/broker.go
  pkg/kn/commands/broker/broker_test.go
  pkg/kn/commands/broker/create.go
  pkg/kn/commands/broker/create_test.go
  pkg/kn/commands/broker/delete.go
  pkg/kn/commands/broker/delete_test.go
  pkg/kn/commands/broker/describe.go
  pkg/kn/commands/broker/describe_test.go
  pkg/kn/commands/broker/list.go
  pkg/kn/commands/broker/list_test.go
  pkg/kn/root/root.go
  test/e2e/broker_test.go
Labels: approved, cla: yes, lgtm, size/XXL

#905 chore: Add broker management feature to changelog
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/XS

#901 Fix Panic for kn source apiserver and kn source binding describe with Sink URI
  CHANGELOG.adoc
  pkg/kn/commands/source/apiserver/apiserver_test.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/source/apiserver/delete_test.go
  pkg/kn/commands/source/apiserver/describe.go
  pkg/kn/commands/source/apiserver/describe_test.go
  pkg/kn/commands/source/apiserver/list_test.go
  pkg/kn/commands/source/apiserver/update_test.go
  pkg/kn/commands/source/binding/binding_test.go
  pkg/kn/commands/source/binding/create_test.go
  pkg/kn/commands/source/binding/delete_test.go
  pkg/kn/commands/source/binding/describe.go
  pkg/kn/commands/source/binding/describe_test.go
  pkg/kn/commands/source/binding/list_test.go
  pkg/kn/commands/source/binding/update_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#908 Add Missing Assertions for Command Unit Tests
  pkg/kn/commands/broker/create_test.go
  pkg/kn/commands/broker/delete_test.go
  pkg/kn/commands/source/ping/create_test.go
  pkg/kn/commands/source/ping/delete_test.go
  pkg/kn/commands/source/ping/list_test.go
  pkg/kn/commands/source/ping/update_test.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/delete_test.go
  pkg/kn/commands/trigger/update_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M
