Repository knative/client, pull requests merged in 2020-01, with the labels that each got.

#592 Handle map-like options consistently
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/trigger/update_flags.go
  pkg/kn/commands/trigger/update_flags_test.go
  pkg/util/parsing_helper.go
  pkg/util/parsing_helper_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#596 Delete k8s cluster resource in e2e test
  test/e2e/common.go
  test/e2e/source_apiserver_test.go
  test/e2e/tekton_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#599 Add E2E tests for CronJob source
  test/e2e/common.go
  test/e2e/cronjob_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#600 Remove redundant cleanup in Tekton tests
  test/e2e/tekton_test.go
Labels: approved, cla: yes, lgtm, size/XS

#602 review comments for pr 555
  test/README.md
Labels: approved, cla: yes, lgtm, needs-ok-to-test, size/XS

#591 fixes(#308): adds e2e tests for plugins
  test/e2e/common.go
  test/e2e/plugins_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#594 chore(e2e): Update tektoncd pipeline release to v0.9.2
  test/e2e/tekton_test.go
  test/resources/tekton/buildah.yaml
  test/resources/tekton/kn-pipeline-run.yaml
  test/resources/tekton/kn-pipeline.yaml
  test/tekton-tests.sh
  test/test_images/helloworld/Dockerfile
  test/test_images/helloworld/go.mod
  test/test_images/helloworld/helloworld.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#581 feature(#580): adds traffic and tags information to revision list
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/revision/list.go
  pkg/kn/commands/revision/list_flags.go
  pkg/kn/commands/revision/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#597 chore(e2e): Namespace specific k8s resources for tests
  test/e2e/source_apiserver_test.go
Labels: approved, cla: yes, lgtm, size/M

#587 fixes(#586): simplifies service update message to user
  pkg/kn/commands/service/service.go
Labels: approved, cla: yes, lgtm, size/XS

#603 Enable trigger filter to be optional
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_test.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/trigger/update_flags.go
  pkg/kn/commands/trigger/update_flags_test.go
  pkg/util/parsing_helper.go
  pkg/util/parsing_helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#608 refactor(service list): Removed special "default" namespace handling
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/service/list.go
  pkg/kn/commands/service/list_mock_test.go
  pkg/kn/commands/service/list_test.go
Labels: approved, cla: yes, lgtm, size/M

#610 Update test-infra: Eventing nightly release YAML rename
  go.mod
  go.sum
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#605 refactor,fix(revision list): Refactoring and fixing issues
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/revision/list.go
  pkg/kn/commands/revision/list_flags.go
  pkg/kn/commands/revision/list_test.go
  pkg/kn/commands/revision/revision.go
  pkg/kn/commands/revision/revision_test.go
Labels: approved, cla: yes, lgtm, size/L

#589 Fix misleading error message when verb is bad
  pkg/kn/core/root.go
  test/e2e/basic_workflow_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#615 Remove Printing Err When Running Root Command
  cmd/kn/main.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#614 feature(serving): Add --autoscale-window
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/revision_template.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, size/L

#618 Vendor serving v0.12.0
  go.mod
  go.sum
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
  test/presubmit-integration-tests-latest-release.sh
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/AUTHORS
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/networking/generic_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/serving/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/service_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/service_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  vendor/knative.dev/serving/pkg/gc/config.go
  vendor/knative.dev/serving/pkg/gc/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/network/bufferpool.go
  vendor/knative.dev/serving/pkg/network/error_handler.go
  vendor/knative.dev/serving/pkg/network/h2c.go
  vendor/knative.dev/serving/pkg/network/network.go
  vendor/knative.dev/serving/pkg/network/transports.go
  vendor/knative.dev/serving/pkg/network/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#617 Add --pull-secret flag
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: approved, cla: yes, lgtm, size/M

#611 fixes(#598): checks for namespace creation instead of waiting
  CHANGELOG.adoc
  test/e2e/common.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#590 Improve 'source apiserver update --resource'
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_flag_test.go
  pkg/kn/commands/source/apiserver/flags.go
  pkg/kn/commands/source/apiserver/flags_test.go
  pkg/kn/commands/source/apiserver/update.go
  pkg/util/parsing_helper.go
  pkg/util/parsing_helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#627 chore: Update changelog for 0.12.0 release
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#625 feature(source binding): Support for Sink Binding as source
  docs/cmd/kn_source.md
  docs/cmd/kn_source_binding.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_delete.md
  docs/cmd/kn_source_binding_describe.md
  docs/cmd/kn_source_binding_list.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_cronjob_describe.md
  pkg/eventing/legacysources/v1alpha1/apiserver_client_test.go
  pkg/eventing/legacysources/v1alpha1/cronjob_client_test.go
  pkg/eventing/v1alpha1/client.go
  pkg/eventing/v1alpha1/client_mock.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/human_readable_flags.go
  pkg/kn/commands/source/apiserver/flags.go
  pkg/kn/commands/source/binding/binding.go
  pkg/kn/commands/source/binding/binding_test.go
  pkg/kn/commands/source/binding/create.go
  pkg/kn/commands/source/binding/create_test.go
  pkg/kn/commands/source/binding/delete.go
  pkg/kn/commands/source/binding/delete_test.go
  pkg/kn/commands/source/binding/describe.go
  pkg/kn/commands/source/binding/describe_test.go
  pkg/kn/commands/source/binding/flags.go
  pkg/kn/commands/source/binding/list.go
  pkg/kn/commands/source/binding/list_test.go
  pkg/kn/commands/source/binding/update.go
  pkg/kn/commands/source/binding/update_test.go
  pkg/kn/commands/source/cronjob/cronjob_test.go
  pkg/kn/commands/source/cronjob/delete.go
  pkg/kn/commands/source/cronjob/describe.go
  pkg/kn/commands/source/cronjob/flags.go
  pkg/kn/commands/source/cronjob/update_test.go
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/source/source.go
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/delete_test.go
  pkg/kn/commands/trigger/describe_test.go
  pkg/kn/commands/trigger/list_test.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/trigger/update_test.go
  pkg/kn/commands/types.go
  pkg/sources/v1alpha1/binding_client.go
  pkg/sources/v1alpha1/binding_client_mock.go
  pkg/sources/v1alpha1/binding_client_mock_test.go
  pkg/sources/v1alpha1/binding_client_test.go
  pkg/sources/v1alpha1/client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_apiserversource.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/fake/fake_sources_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/generated_expansion.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sinkbinding.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/sources/v1alpha1/sources_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#628 chore(e2e): Update dependency to eventing v0.12.0
  go.mod
  go.sum
  test/presubmit-integration-tests-latest-release.sh
  vendor/knative.dev/test-infra/scripts/README.md
  vendor/knative.dev/test-infra/scripts/e2e-tests.sh
  vendor/knative.dev/test-infra/scripts/library.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
