Repository knative/client, pull requests merged in 2021-04, with the labels that each got.

#1266 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/xerrors/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/report_compare.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/prometheus/common/model/time.go
  vendor/google.golang.org/grpc/balancer/grpclb/grpc_lb_v1/load_balancer_grpc.pb.go
  vendor/google.golang.org/grpc/credentials/alts/internal/proto/grpc_gcp/handshaker_grpc.pb.go
  vendor/google.golang.org/grpc/encoding/proto/proto.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_defaults.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/subscription_validation.go
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1267 Add DomainMapping CRUD commands
  CHANGELOG.adoc
  docs/cmd/kn.md
  docs/cmd/kn_domain.md
  docs/cmd/kn_domain_create.md
  docs/cmd/kn_domain_delete.md
  docs/cmd/kn_domain_describe.md
  docs/cmd/kn_domain_list.md
  docs/cmd/kn_domain_update.md
  pkg/dynamic/fake/fake.go
  pkg/kn/commands/domain/create.go
  pkg/kn/commands/domain/create_test.go
  pkg/kn/commands/domain/delete.go
  pkg/kn/commands/domain/delete_test.go
  pkg/kn/commands/domain/describe.go
  pkg/kn/commands/domain/describe_test.go
  pkg/kn/commands/domain/domain.go
  pkg/kn/commands/domain/domain_test.go
  pkg/kn/commands/domain/human_readable_flags.go
  pkg/kn/commands/domain/list.go
  pkg/kn/commands/domain/list_test.go
  pkg/kn/commands/domain/update.go
  pkg/kn/commands/domain/update_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  pkg/kn/root/root.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_mock.go
  pkg/serving/v1alpha1/client_mock_test.go
  pkg/serving/v1alpha1/client_test.go
  test/common.sh
  test/e2e/domain_mapping_test.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL

#1277 Update OWNERS_ALIASES to match autogen in community
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#1280 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1263 Fix memory leak on closed watch channel
  CHANGELOG.adoc
  go.sum
  pkg/wait/poll_watcher.go
  pkg/wait/wait_for_ready.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1282 Prepare for release 0.22.0
  CHANGELOG.adoc
  go.mod
  go.sum
  pkg/kn/commands/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1283 Some fixes in `kn domain` help messages
  docs/cmd/kn_domain_describe.md
  docs/cmd/kn_domain_list.md
  pkg/kn/commands/domain/describe.go
  pkg/kn/commands/domain/list.go
Labels: approved, cla: yes, lgtm, size/S

#1285 chore(ci): Update E2E latest release versions for Serving & Eventing
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1279 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1276 Fix service/revision list output with '-o' param
  CHANGELOG.adoc
  pkg/kn/commands/broker/list.go
  pkg/kn/commands/broker/list_test.go
  pkg/kn/commands/channel/list.go
  pkg/kn/commands/channel/list_test.go
  pkg/kn/commands/channel/list_types.go
  pkg/kn/commands/channel/list_types_test.go
  pkg/kn/commands/revision/list.go
  pkg/kn/commands/revision/list_test.go
  pkg/kn/commands/route/list.go
  pkg/kn/commands/route/list_test.go
  pkg/kn/commands/service/list.go
  pkg/kn/commands/service/list_test.go
  pkg/kn/commands/source/apiserver/list.go
  pkg/kn/commands/source/apiserver/list_test.go
  pkg/kn/commands/source/binding/list.go
  pkg/kn/commands/source/binding/list_test.go
  pkg/kn/commands/source/container/list.go
  pkg/kn/commands/source/container/list_test.go
  pkg/kn/commands/source/list.go
  pkg/kn/commands/source/list_test.go
  pkg/kn/commands/source/list_types.go
  pkg/kn/commands/source/ping/list.go
  pkg/kn/commands/source/ping/list_test.go
  pkg/kn/commands/subscription/list.go
  pkg/kn/commands/subscription/list_test.go
  pkg/kn/commands/trigger/list.go
  pkg/kn/commands/trigger/list_test.go
  test/e2e/source_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1289 Add number of instances to describe command
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/describe_test.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/describe_test.go
Labels: approved, cla: yes, lgtm, size/S

#1288 Fix domain list output
  pkg/kn/commands/domain/list.go
  pkg/kn/commands/domain/list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1290 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1291 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1295 Drop --strict flag on ko
  hack/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1292 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/volatile_time.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1296 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_context.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_conversion.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_types.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/reconciler/events.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XXL
