Repository knative/client, pull requests merged in 2021-07, with the labels that each got.

#1333 Refactor waiting loop to use resourceVersion
  pkg/eventing/v1/client.go
  pkg/eventing/v1/client_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
  pkg/serving/v1/client_mock_test.go
  pkg/serving/v1/client_test.go
  pkg/wait/poll_watcher.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1362 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/logging/warning_handler.go
  vendor/knative.dev/pkg/ptr/value.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1367 Adding tests for printer pkg
  pkg/printers/interface_test.go
  pkg/printers/tablegenerator_test.go
  pkg/printers/tableprinter_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1363 [main] Update actions
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-stale.yaml
Labels: approved, cla: yes, lgtm, size/S

#1369 Do not cleanup on failure in Tekton tests
  test/e2e/tekton_test.go
  test/tekton-tests.sh
Labels: approved, cla: yes, lgtm, size/XS

#1370 Remove standalone DomainMapping setup
  test/common.sh
Labels: approved, cla: yes, lgtm, size/S

#1371 Adding tests for wait pkg
  pkg/wait/poll_watcher_test.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1366 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1375 Adding tests for commands/flag pkg
  pkg/kn/commands/flags/listprint_test.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/flags/traffic_test.go
  pkg/kn/commands/human_readable_flags_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1378 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1379 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/buffer/buffer.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/options.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/buffered_write_syncer.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/entry.go
  vendor/golang.org/x/net/http2/ascii.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/clientauth.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/impersonate.go
  vendor/golang.org/x/oauth2/google/jwt.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/gocommand/version.go
  vendor/golang.org/x/tools/internal/typeparams/doc.go
  vendor/golang.org/x/tools/internal/typeparams/notypeparams.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/store.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1380 make command as array instead of string
  CHANGELOG.adoc
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/kn/flags/podspec_test.go
Labels: approved, cla: yes, lgtm, size/M

#1383 Introduce -reusenamespace test flag
  lib/test/flags.go
  lib/test/integration.go
Labels: approved, cla: yes, lgtm, size/S

#1384 Run tests as project admin
  lib/test/broker.go
  test/README.md
  test/e2e/broker_test.go
  test/e2e/sink_test.go
  test/e2e/source_apiserver_test.go
  test/e2e/source_list_crd_test.go
  test/e2e/source_list_test.go
  test/e2e/trigger_test.go
Labels: approved, cla: yes, lgtm, size/L

#1388 Adding encoding flag and support for base64 data
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  pkg/kn/commands/source/ping/create.go
  pkg/kn/commands/source/ping/create_test.go
  pkg/kn/commands/source/ping/describe_test.go
  pkg/kn/commands/source/ping/flags.go
  pkg/kn/commands/source/ping/list_test.go
  pkg/kn/commands/source/ping/ping_test.go
  pkg/kn/commands/source/ping/update_test.go
  pkg/sources/v1beta2/ping_client.go
Labels: approved, cla: yes, lgtm, size/M

#1377 Adding tests for commands package
  pkg/kn/commands/describe_test.go
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/types_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1376 Adding test cases for serving pkg
  pkg/serving/config_changes_test.go
  pkg/serving/revision_template_test.go
  pkg/serving/v1/apply_test.go
  pkg/serving/v1/client_test.go
  pkg/serving/v1/gitops_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1393 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1395 Fix issue with Windows pathes not being escaped when applying a regexp.
  cmd/kn/main.go
  cmd/kn/main_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1391 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1390 Skip non modified event first while waiting for ready
  pkg/wait/test_wait_helper.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1396 Use namespaced kubectl for sa,role,rolebinding in tests
  test/e2e/source_apiserver_test.go
Labels: approved, cla: yes, lgtm, size/S

#1398 update plugin README
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1392 Adding base64 data handling to ping update command
  CHANGELOG.adoc
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  pkg/kn/commands/source/ping/create.go
  pkg/kn/commands/source/ping/describe.go
  pkg/kn/commands/source/ping/describe_test.go
  pkg/kn/commands/source/ping/flags.go
  pkg/kn/commands/source/ping/ping_test.go
  pkg/kn/commands/source/ping/update.go
  pkg/kn/commands/source/ping/update_test.go
  test/e2e/ping_test.go
Labels: approved, cla: yes, lgtm, size/L

#1400 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1364 Add an update timestamp to trigger the creation of a revision when needed.
  CHANGELOG.adoc
  pkg/kn/commands/flags/listprint_test.go
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/export_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/plugin/manager.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/revision_template.go
  pkg/serving/revision_template_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_test.go
  test/e2e/service_apply_test.go
  test/e2e/service_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1397 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/README.md
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/conversion_error.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/XL

#1401 Adding support for darwin/arm64
  CHANGELOG.adoc
  go.mod
  hack/build.sh
  hack/release.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1405 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M
