Repository knative/client, pull requests merged in 2021-11, with the labels that each got.

#1499 Rename `--extra-containers` to `--containers`
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/commands/container/add.go
  pkg/kn/commands/container/add_test.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_test.go
  test/e2e/extra_containers_test.go
Labels: lgtm, approved, size/M, cla: yes

#1497 Reword missing API error to mention client update
  CHANGELOG.adoc
  pkg/errors/errors.go
  pkg/errors/errors_test.go
  pkg/errors/factory.go
  pkg/errors/factory_test.go
  pkg/kn/commands/channel/list_types.go
  pkg/kn/commands/channel/list_types_test.go
  pkg/kn/commands/source/list_test.go
  pkg/kn/commands/source/list_types.go
Labels: lgtm, approved, size/M, cla: yes

#1500 Mark deprecated options as 'hidden'
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/flags/podspec.go
Labels: lgtm, approved, size/S, cla: yes

#1498 Removing deprecated flags
  pkg/kn/commands/service/configuration_edit_flags.go
Labels: lgtm, approved, size/S, cla: yes

#1501 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M, cla: yes

#1472 Add support to (not) initialize kn config file
  pkg/kn/config/config.go
  pkg/kn/config/config_test.go
Labels: lgtm, approved, size/M, ok-to-test, cla: yes

#1505 Fix fetching of Istio latest release
  test/common.sh
Labels: lgtm, approved, size/S, cla: yes

#1503 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M, cla: yes

#1504 Update changelog for 1.0 release
  CHANGELOG.adoc
Labels: approved, size/M, cla: yes

#1502 Fix config init for non-writable locations
  pkg/kn/config/config.go
Labels: size/XS, lgtm, approved, cla: yes

#1506 Remove lookup-plugins flag
  cmd/kn/main_test.go
  pkg/kn/config/config.go
  pkg/kn/config/types.go
  test/e2e/plugins_test.go
Labels: lgtm, approved, size/M, cla: yes

#1507 Update Serving and Eventing versions in E2E tests
  test/presubmit-integration-tests-latest-release.sh
Labels: size/XS, lgtm, approved, cla: yes

#1510 Fix the most common E2E flakes
  test/e2e/domain_mapping_test.go
  test/e2e/sink_test.go
  test/e2e/trigger_test.go
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#1511 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#1509 Fix fetching of Istion latest release
  test/common.sh
Labels: size/XS, lgtm, approved, cla: yes

#1508 update status of commands
  docs/cmd/kn_container_add.md
  docs/cmd/kn_domain_update.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_export.md
  docs/cmd/kn_service_import.md
  docs/cmd/kn_service_list.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/container/add.go
  pkg/kn/commands/domain/update.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/import.go
  pkg/kn/commands/service/list.go
  pkg/kn/commands/service/update.go
Labels: lgtm, approved, size/M, cla: yes

#1513 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1517 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1518 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/M, cla: yes

#1521 Move away from grpc-ping test image as symlink
  test/test_images/grpc-ping
  test/test_images/grpc-ping/release.yaml
Labels: lgtm, approved, size/S, cla: yes

#1519 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1523 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/metadata_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/pkg/apis/duck/v1/status_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/status_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/comment_parser.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/kmap/lookup.go
  vendor/knative.dev/pkg/kmap/map.go
  vendor/knative.dev/pkg/kmeta/map.go
  vendor/knative.dev/pkg/reconciler/filter.go
  vendor/knative.dev/pkg/test/spoof/error_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/autoscalerconfig.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: size/XL, lgtm, approved, cla: yes

#1524 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S, cla: yes

#1526 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/S, cla: yes

#1529 Fixed panic in kn service describe
  CHANGELOG.adoc
  pkg/kn/commands/revision/describe.go
Labels: lgtm, approved, size/S, cla: yes

#1516 Fix env, annotation and labels flags in service create/update/apply
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  pkg/kn/commands/container/add.go
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/source/container/create.go
  pkg/kn/commands/source/container/update.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_test.go
Labels: lgtm, approved, size/L, ok-to-test, cla: yes

#1531 Align autoscaling annotations in tests
  go.mod
  go.sum
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update_test.go
  pkg/serving/config_changes_test.go
  test/e2e/service_options_test.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved, cla: yes

#1514 Add --tag flag to service create and allow traffic split <100 when @latest is specified
  docs/cmd/kn_service_create.md
  pkg/kn/commands/flags/traffic.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/traffic/compute.go
  pkg/kn/traffic/compute_test.go
  test/e2e/traffic_split_test.go
Labels: lgtm, approved, size/L, cla: yes

#1532 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/modules.txt
Labels: lgtm, approved, size/M, cla: yes

#1533 Fixed panic when traffic split to unavailable revision
  CHANGELOG.adoc
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  pkg/serving/revision_template.go
  pkg/serving/revision_template_test.go
Labels: lgtm, approved, size/L, cla: yes
