Repository knative/client, pull requests merged in 2021-03, with the labels that each got.

#1245 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/controller/options.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/resource_view.go
  vendor/knative.dev/pkg/network/network.go
  vendor/knative.dev/pkg/system/clock.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/metric_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_validation.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1248 chore: Update CRDs API version to v1
  CHANGELOG.adoc
  pkg/dynamic/client.go
  pkg/kn/commands/channel/list_types_test.go
  pkg/kn/commands/source/list_test.go
  test/e2e/source_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1212 kn export defect to honor mode
  pkg/kn/commands/service/export.go
  pkg/kn/commands/service/export_test.go
  test/e2e/service_export_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1249 add changelog for 1212
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/XS

#1247 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1250 docs: About e2e prow jobs
  test/README.md
Labels: approved, cla: yes, lgtm, size/S

#1226 feat: Add knb plugin build tool
  .gitignore
  hack/build.sh
  tools/knb/README.md
  tools/knb/knb.go
  tools/knb/pkg/plugin/distro.go
  tools/knb/pkg/plugin/init.go
  tools/knb/pkg/plugin/plugin.go
  tools/knb/pkg/plugin/templates.go
  tools/knb/pkg/root/root.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1252 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/configs/register.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_defaults.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_types.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/configmappropagation_validation.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/doc.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/register.go
  vendor/knative.dev/eventing/pkg/apis/configs/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/register.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/go.sum
  vendor/knative.dev/pkg/controller/controller.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1255 Add David as approver
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1246 kn source-list types: adding column to specify built-in source
  CHANGELOG.adoc
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/source/list_test.go
  test/e2e/source_list_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1254 Drop master references to knative repos
  CHANGELOG.adoc
  README.md
  docs/dev/developer-guide.md
  docs/plugins/README.md
  docs/workflows/basic.md
  pkg/serving/v1/gitops_test.go
  test/README.md
Labels: approved, cla: yes, lgtm, size/S

#1256 Use net-istio provided version in E2E setup
  test/common.sh
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, size/M

#1258 Use common Eventing setup from hack library
  test/common.sh
Labels: approved, cla: yes, lgtm, size/S

#1257 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/microbenchmarks.sh
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1260 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/generic_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_types.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1261 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1262 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/zipkin/util.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1217 Add --prune & --prune-all options to delete the unreferenced revisions
  CHANGELOG.adoc
  docs/cmd/kn_revision_delete.md
  lib/test/revision.go
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/delete_mock_test.go
  pkg/kn/commands/revision/delete_test.go
  test/e2e/revision_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1265 Fix linting error SA5011
  pkg/kn/plugin/manager_test.go
Labels: approved, cla: yes, lgtm, size/S

#1264 Add support for namespace for all commands that takes a --sink option
  CHANGELOG.adoc
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  test/e2e-tests.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1270 Pass revision to git-clone Tekton task - fix nightly Tekton tests
  test/resources/tekton/kn-pipeline.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1271 Update --sink flag description
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/kn/commands/flags/sink.go
Labels: approved, cla: yes, lgtm, size/M

#1268 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1275 [Automated] Update knative/community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/L
