Repository knative/client, pull requests merged in 2021-10, with the labels that each got.

#1463 Changing the Default retry value
  pkg/config/defaults.go
  pkg/eventing/v1/client.go
  pkg/kn/commands/domain/update.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/source/container/update.go
  pkg/kn/commands/source/ping/ping.go
  pkg/kn/commands/source/ping/update.go
  pkg/kn/commands/subscription/update.go
  pkg/kn/commands/trigger/trigger.go
  pkg/kn/commands/trigger/update.go
  pkg/messaging/v1/subscriptions_client.go
  pkg/serving/v1/client.go
  pkg/serving/v1alpha1/client.go
  pkg/sources/v1/container_client.go
  pkg/sources/v1beta2/ping_client.go
Labels: lgtm, approved, size/L, cla: yes

#1468 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/conformance.go
  vendor/modules.txt
Labels: lgtm, approved, size/M, cla: yes

#1471 Fix assertion in ping source unit tests
  pkg/kn/commands/source/ping/delete_test.go
Labels: size/XS, lgtm, approved, ok-to-test, cla: yes

#1473 Fix changelog reference for pull request 1433
  CHANGELOG.adoc
Labels: size/XS, lgtm, approved, cla: yes

#1470 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/pkg/apis/contexts.go
  vendor/knative.dev/pkg/tracker/enqueue.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: lgtm, approved, size/M, ok-to-test, cla: yes

#1483 Calculate traffic split when N-1 revisions are specified
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/traffic/compute.go
  pkg/kn/traffic/compute_test.go
  test/e2e/traffic_split_test.go
Labels: size/XL, lgtm, approved, ok-to-test, cla: yes
