Repository knative/client, pull requests merged in 2021-08, with the labels that each got.

#1411 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1416 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1414 Add lint check to build.sh script
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/S

#1418 Fix unit tests clash with local kubeconfig
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/revision/revision_test.go
  pkg/kn/commands/types_test.go
Labels: approved, cla: yes, lgtm, size/L

#1420 Fix build.sh for symlinks and on macOs
  hack/build.sh
Labels: size/XS, lgtm, approved, cla: yes

#1406 Server errors should not be tainted by client error messages
  CHANGELOG.adoc
  pkg/errors/factory.go
  pkg/errors/factory_test.go
Labels: lgtm, approved, size/L, cla: yes

#1402 Adding class option to broker create
  CHANGELOG.adoc
  docs/cmd/kn_broker_create.md
  lib/test/broker.go
  pkg/eventing/v1/client.go
  pkg/eventing/v1/client_test.go
  pkg/kn/commands/broker/broker_test.go
  pkg/kn/commands/broker/create.go
  pkg/kn/commands/broker/create_test.go
  test/e2e/broker_test.go
Labels: lgtm, approved, size/M, cla: yes

#1415 Fixing bug when looking up plugins on path with slash in argument
  pkg/kn/plugin/manager.go
  pkg/kn/plugin/manager_test.go
Labels: lgtm, approved, size/M, ok-to-test, cla: yes

#1421 Fix unit tests to use NAMESPACE value in OpenShift CI env
  pkg/kn/commands/namespaced_test.go
Labels: lgtm, approved, size/L, cla: yes

#1417 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/register.go
  vendor/modules.txt
Labels: lgtm, approved, size/M, cla: yes

#1412 Look up plugins on $PATH by default
  pkg/kn/config/config.go
Labels: size/XS, lgtm, approved, ok-to-test, cla: yes

#1422 Deprecate `lookup-path` option and updated relevant documentation
  CHANGELOG.adoc
  docs/README.md
  docs/cmd/kn_plugin_list.md
  pkg/kn/commands/plugin/list.go
  pkg/kn/config/config.go
  pkg/kn/config/config_test.go
  pkg/kn/config/types.go
Labels: lgtm, approved, size/M, cla: yes

#1419 Adding --tls option to domain create command
  CHANGELOG.adoc
  docs/cmd/kn_domain_create.md
  pkg/kn/commands/domain/create.go
  pkg/kn/commands/domain/create_test.go
  pkg/kn/commands/domain/describe_test.go
  pkg/kn/commands/domain/domain.go
  pkg/kn/commands/domain/domain_test.go
  pkg/kn/commands/domain/list_test.go
  pkg/kn/commands/domain/update_test.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_test.go
  test/e2e/domain_mapping_test.go
Labels: lgtm, approved, size/L, ok-to-test, cla: yes

#1423 Prepare changelog and version for 0.25 release
  CHANGELOG.adoc
  pkg/kn/commands/version/version.go
Labels: lgtm, approved, size/M, cla: yes

#1424 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S, cla: yes

#1425 update versions to 0.25
  test/presubmit-integration-tests-latest-release.sh
Labels: size/XS, lgtm, approved, cla: yes

#1426 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#1427 Fix release script to published darwin/arm64 bits
  hack/release.sh
Labels: size/XS, lgtm, approved, cla: yes

#1429 Update code-of-conduct, readme and contrib files
  CONTRIBUTING.md
  README.md
  code-of-conduct.md
Labels: lgtm, approved, size/M, cla: yes

#1428 fix kn trigger list command to show correct v1/service sink output
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/source/duck/multisourcelist_test.go
  pkg/kn/commands/source/list_test.go
Labels: lgtm, approved, size/S, ok-to-test, cla: yes

#1431 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/interfaces.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/pkg/metrics/exporter.go
  vendor/knative.dev/pkg/network/error_handler.go
  vendor/knative.dev/pkg/tracker/interface.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved, cla: yes

#1432 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#1436 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved, cla: yes

#1435 TestServiceExport works with images specified by digest
  test/e2e/service_export_test.go
  test/e2e/source_container_test.go
Labels: lgtm, approved, size/S, cla: yes

#1437 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#1440 Tekton - use ClusterRoleBinding v1
  test/resources/tekton/kn-deployer-rbac-template.yaml
Labels: size/XS, lgtm, approved, cla: yes
