Repository knative/client, pull requests merged in 2021-06, with the labels that each got.

#1330 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/client/injection/ducks/duck/v1/addressable/addressable.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/logging/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/metrics/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/test/README.md
  vendor/knative.dev/pkg/test/clients.go
  vendor/knative.dev/pkg/test/e2e_flags.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/tracker/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1332 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/S

#1334 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/go.uber.org/zap/.travis.yml
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/CONTRIBUTING.md
  vendor/go.uber.org/zap/FAQ.md
  vendor/go.uber.org/zap/Makefile
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/field.go
  vendor/go.uber.org/zap/go.mod
  vendor/go.uber.org/zap/go.sum
  vendor/go.uber.org/zap/http_handler.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/sugar.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/error.go
  vendor/go.uber.org/zap/zapcore/field.go
  vendor/go.uber.org/zap/zapcore/write_syncer.go
  vendor/gopkg.in/evanphx/json-patch.v4/.travis.yml
  vendor/gopkg.in/evanphx/json-patch.v4/README.md
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/apis/duck/patch.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1336 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1335 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1339 Make e2e test run over other networks
  test/common.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1341 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: approved, cla: yes, lgtm, size/M

#1347 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1351 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1340 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/2q.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/arc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/doc.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/.gitignore
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/.travis.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/LICENSE
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/Makefile
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/README.md
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/appveyor.yml
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/decoder.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/go.mod
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/go.sum
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/ast/ast.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/ast/walk.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/parser/error.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/parser/parser.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/printer/nodes.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/printer/printer.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/scanner/scanner.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/strconv/quote.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/token/position.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/hcl/token/token.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/json/parser/flatten.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/json/parser/parser.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/json/scanner/scanner.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/json/token/position.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/json/token/token.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/lex.go
  third_party/VENDOR-LICENSE/github.com/hashicorp/hcl/parse.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/api_validation.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/feature/store.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/test/environment/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1343 increase code cov for sources
  pkg/kn/commands/source/apiserver/apiserver_test.go
  pkg/kn/commands/source/apiserver/create.go
  pkg/kn/commands/source/apiserver/create_test.go
  pkg/kn/commands/source/apiserver/delete_test.go
  pkg/kn/commands/source/apiserver/describe_test.go
  pkg/kn/commands/source/apiserver/list_test.go
  pkg/kn/commands/source/apiserver/update_test.go
  pkg/kn/commands/source/container/container_test.go
  pkg/kn/commands/source/container/create.go
  pkg/kn/commands/source/container/create_test.go
  pkg/kn/commands/source/container/delete_test.go
  pkg/kn/commands/source/container/describe.go
  pkg/kn/commands/source/container/describe_test.go
  pkg/kn/commands/source/container/list_test.go
  pkg/kn/commands/source/container/update.go
  pkg/kn/commands/source/container/update_test.go
  pkg/kn/commands/source/ping/delete_test.go
  pkg/kn/commands/source/ping/describe_test.go
  pkg/kn/commands/source/ping/update_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1348 Remove force update of go-licenses binary
  hack/build.sh
Labels: approved, cla: yes, lgtm, size/XS

#1354 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1357 Improve test coverage of main package
  cmd/kn/main.go
  cmd/kn/main_test.go
Labels: approved, cla: yes, lgtm, size/L

#1328 Add `env-value-from` flag & keep order of env vars in created/updated services
  CHANGELOG.adoc
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/service_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update_test.go
  pkg/kn/commands/source/container/create.go
  pkg/kn/commands/source/container/update.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/kn/flags/podspec_test.go
  test/e2e/service_options_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1356 Update changelog for 0.24.0 release
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/S

#1358 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1360 update versions to 0.24
  pkg/kn/commands/version/version.go
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/S

#1361 [release-0.23] Fix domain mapping CI setup
  go.mod
  go.sum
  test/common.sh
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1359 Move warning handler from `main()` to `RestConfig()`
  cmd/kn/main.go
  pkg/kn/commands/types.go
Labels: approved, cla: yes, lgtm, size/S
