Repository knative/client, pull requests merged in 2021-01, with the labels that each got.

#1179 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1182 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1183 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domainclaim_types.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1189 client release v0.20.0 prep
  CHANGELOG.adoc
  go.mod
  go.sum
  hack/update-k8s-deps.sh
  pkg/kn/commands/version/version.go
  test/presubmit-integration-tests-latest-release.sh
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1122 add git ops options
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_list.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/human_readable_flags.go
  pkg/kn/commands/service/apply.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/import.go
  pkg/kn/commands/service/list.go
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/types.go
  pkg/serving/v1/gitops.go
  pkg/serving/v1/gitops_test.go
Labels: approved, cla: yes, lgtm, size/XL

#1190 chore: Add gitops feature to changelog
  CHANGELOG.adoc
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_delete.md
  docs/cmd/kn_service_describe.md
  docs/cmd/kn_service_list.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/human_readable_flags.go
Labels: approved, cla: yes, lgtm, size/S

#1175 fix: Parsing the kn commands from error message
  CHANGELOG.adoc
  cmd/kn/main.go
Labels: approved, cla: yes, lgtm, size/S

#1188 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/defaults.go
  vendor/knative.dev/hack/codegen-library.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/labels/labels.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1194 Do not print serviceUID and configUID labels in service export result
  CHANGELOG.adoc
  pkg/kn/commands/service/export.go
  test/e2e/service_export_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1199 Rename configUID label to ConfigurationUID
  pkg/kn/commands/service/export.go
  test/e2e/service_export_test.go
Labels: approved, cla: yes, lgtm, size/S

#1193 Sorted changelog and added some missing entries
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#1198 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/S

#1196 [] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/channel_template_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_types.go
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/injection/README.md
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1200 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1201 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/examples/defaulter-gen/generators/defaulter.go
  vendor/k8s.io/gengo/examples/import-boss/generators/import_restrict.go
  vendor/k8s.io/gengo/examples/set-gen/generators/sets.go
  vendor/k8s.io/gengo/examples/set-gen/generators/tags.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/import_tracker.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1203 Making a toReference public to enable reuse from kn-plugins
  CHANGELOG.adoc
  pkg/kn/commands/source/binding/binding.go
  pkg/kn/commands/source/binding/create.go
  pkg/kn/commands/source/binding/describe_test.go
  pkg/kn/commands/source/binding/update.go
  pkg/util/parsing_helper.go
  pkg/util/parsing_helper_test.go
Labels: approved, cla: yes, lgtm, size/L

#1208 fix: Fix deprecated ServiceName in revision describe test
  pkg/kn/commands/revision/describe_test.go
Labels: approved, cla: yes, lgtm, size/XS
