Repository knative/client, pull requests merged in 2021-12, with the labels that each got.

#1536 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved, cla: yes

#1535 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#1534 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1538 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/golang.org/x/mod/internal/lazyregexp/lazyre.go
  vendor/golang.org/x/mod/module/module.go
  vendor/golang.org/x/mod/module/pseudo.go
  vendor/golang.org/x/mod/semver/semver.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/windows/mksyscall.go
  vendor/golang.org/x/sys/windows/setupapi_windows.go
  vendor/golang.org/x/sys/windows/setupapierrors_windows.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/golang.org/x/tools/go/ast/astutil/enclosing.go
  vendor/golang.org/x/tools/go/ast/astutil/rewrite.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go117.go
  vendor/golang.org/x/tools/internal/typeparams/enabled_go118.go
  vendor/golang.org/x/tools/internal/typeparams/normalize.go
  vendor/golang.org/x/tools/internal/typeparams/termlist.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/golang.org/x/tools/internal/typeparams/typeterm.go
  vendor/k8s.io/gengo/args/args.go
  vendor/k8s.io/gengo/examples/deepcopy-gen/generators/deepcopy.go
  vendor/k8s.io/gengo/generator/execute.go
  vendor/k8s.io/gengo/generator/generator.go
  vendor/k8s.io/gengo/parser/parse.go
  vendor/k8s.io/gengo/types/types.go
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, cla: yes

#1537 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#1539 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1544 :gift: Allow overriding of `build.sh` for downstream projects
  hack/build-flags.sh
  hack/build.sh
  hack/build.sh.d/README.md
Labels: lgtm, approved, size/M

#1541 docs: Fix broker class in create command
  docs/cmd/kn_broker_create.md
  pkg/kn/commands/broker/create.go
Labels: size/XS, lgtm, approved, ok-to-test

#1546 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1549 Use istio stable intead of latest
  go.mod
  go.sum
  test/common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1545 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1550 Update changelog
  CHANGELOG.adoc
Labels: lgtm, approved, size/S

#1551 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1552 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S
