Repository knative/client, pull requests merged in 2021-05, with the labels that each got.

#1297 chore: fixed documentation of configuration options in README
  docs/README.md
Labels: approved, cla: yes, lgtm, size/L

#1302 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-containerregistry/pkg/name/ref.go
  vendor/knative.dev/eventing/pkg/apis/messaging/config/channel_template_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1303 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1307 Fully qualified test images
  test/test_images/helloworld/Dockerfile
Labels: approved, cla: yes, lgtm, size/XS

#1306 Fix for serviceaccounts "default" not found flaky issue
  CHANGELOG.adoc
  lib/test/integration.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1310 Fixe formatting in README
  docs/README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1311 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: approved, cla: yes, lgtm, size/M

#1312 Fix replicas *int32 type in describe commands
  go.mod
  go.sum
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/describe_test.go
  pkg/kn/commands/service/describe_test.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/channelable_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/sequence_types.go
  vendor/knative.dev/eventing/pkg/apis/flows/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1314 [main] Update actions
  .github/workflows/knative-go-build.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1317 Add knative-release-leads to OWNERS
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1301 Refactor waiting loop to use resourceVersion
  pkg/eventing/v1/client.go
  pkg/eventing/v1/client_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_test.go
  pkg/wait/poll_watcher.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/L

#1305 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1313 add code cov
  .codecov.yaml
  README.md
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1319 Update version.go for release 0.23
  pkg/kn/commands/version/version.go
Labels: approved, cla: yes, lgtm, size/XS

#1315 Update changelog for release v0.23.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, size/M

#1321 Revert "Refactor waiting loop to use resourceVersion
  CHANGELOG.adoc
  pkg/eventing/v1/client.go
  pkg/eventing/v1/client_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_test.go
  pkg/wait/poll_watcher.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
Labels: approved, cla: yes, lgtm, size/L

#1320 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1323 bump presubmit to .23
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1325 [main] Update community files
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, size/XS

#1326 Fix Subscription's Channel to use KRefence type
  go.mod
  go.sum
  pkg/kn/commands/subscription/subscription_test.go
  pkg/kn/flags/channel_types.go
  pkg/kn/flags/channel_types_test.go
  pkg/messaging/v1/subscriptions_client.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscribable_channelable_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1331 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS
