Repository knative/client, pull requests merged in 2021-02, with the labels that each got.

#1209 fix: Pin go-openapi/spec version to fix conflict
  go.mod
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1210 Allow to specify build platform for test images
  test/README.md
  test/upload-test-images.sh
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1211 Include homebrew install instructions in user guide
  docs/README.md
Labels: approved, cla: yes, lgtm, size/XS

#1213 fix: Fix go-openapi/spec replace with correct module
  go.mod
  go.sum
  vendor/github.com/go-openapi/spec/.golangci.yml
  vendor/github.com/go-openapi/spec/bindata.go
  vendor/github.com/go-openapi/spec/contact_info.go
  vendor/github.com/go-openapi/spec/expander.go
  vendor/github.com/go-openapi/spec/go.mod
  vendor/github.com/go-openapi/spec/go.sum
  vendor/github.com/go-openapi/spec/license.go
  vendor/github.com/go-openapi/spec/ref.go
  vendor/github.com/go-openapi/spec/schema_loader.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/L

#1214 [Automated] Update actions
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, size/XS

#1215 fix: Fix deprecated terminal lib
  go.mod
  go.sum
  pkg/templates/template_engine.go
  third_party/VENDOR-LICENSE/golang.org/x/term/LICENSE
  vendor/golang.org/x/sys/plan9/asm.s
  vendor/golang.org/x/sys/plan9/asm_plan9_386.s
  vendor/golang.org/x/sys/plan9/asm_plan9_amd64.s
  vendor/golang.org/x/sys/plan9/asm_plan9_arm.s
  vendor/golang.org/x/sys/plan9/const_plan9.go
  vendor/golang.org/x/sys/plan9/dir_plan9.go
  vendor/golang.org/x/sys/plan9/env_plan9.go
  vendor/golang.org/x/sys/plan9/errors_plan9.go
  vendor/golang.org/x/sys/plan9/mkall.sh
  vendor/golang.org/x/sys/plan9/mkerrors.sh
  vendor/golang.org/x/sys/plan9/mksysnum_plan9.sh
  vendor/golang.org/x/sys/plan9/pwd_go15_plan9.go
  vendor/golang.org/x/sys/plan9/pwd_plan9.go
  vendor/golang.org/x/sys/plan9/race.go
  vendor/golang.org/x/sys/plan9/race0.go
  vendor/golang.org/x/sys/plan9/str.go
  vendor/golang.org/x/sys/plan9/syscall.go
  vendor/golang.org/x/sys/plan9/syscall_plan9.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_386.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_amd64.go
  vendor/golang.org/x/sys/plan9/zsyscall_plan9_arm.go
  vendor/golang.org/x/sys/plan9/zsysnum_plan9.go
  vendor/golang.org/x/term/AUTHORS
  vendor/golang.org/x/term/CONTRIBUTING.md
  vendor/golang.org/x/term/CONTRIBUTORS
  vendor/golang.org/x/term/LICENSE
  vendor/golang.org/x/term/PATENTS
  vendor/golang.org/x/term/README.md
  vendor/golang.org/x/term/go.mod
  vendor/golang.org/x/term/go.sum
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/term/term_plan9.go
  vendor/golang.org/x/term/term_solaris.go
  vendor/golang.org/x/term/term_unix.go
  vendor/golang.org/x/term/term_unix_aix.go
  vendor/golang.org/x/term/term_unix_bsd.go
  vendor/golang.org/x/term/term_unix_linux.go
  vendor/golang.org/x/term/term_unix_zos.go
  vendor/golang.org/x/term/term_unsupported.go
  vendor/golang.org/x/term/term_windows.go
  vendor/golang.org/x/term/terminal.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XXL

#1216 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_types.go
  vendor/knative.dev/networking/pkg/stats.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1221 Drop pkg/errors dependency and replace with stdlib usage
  cmd/kn/main.go
  go.mod
  pkg/kn/commands/completion/completion.go
  pkg/kn/commands/options/options.go
  pkg/kn/commands/plugin/list.go
  pkg/kn/commands/service/apply_mock_test.go
  pkg/kn/config/config.go
  pkg/kn/plugin/manager.go
  pkg/kn/root/root.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1218 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/XS

#1223 Enable errorlint and fix all issues
  .golangci.yaml
  cmd/kn/main.go
  pkg/dynamic/lib.go
  pkg/errors/factory.go
  pkg/kn/commands/options/options.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/service.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/source/duck/multisourcelist.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/config/config.go
  pkg/kn/plugin/manager.go
  pkg/kn/plugin/verify.go
  pkg/kn/root/root.go
  pkg/printers/tablegenerator.go
  pkg/serving/config_changes.go
  pkg/util/logging_http_transport.go
  pkg/util/logging_http_transport_test.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1225 Update link to contribution guidelines
  docs/DEVELOPMENT.md
Labels: approved, cla: yes, lgtm, size/XS

#1224 Enable unparam linter and fix issues
  .golangci.yaml
  pkg/kn/commands/revision/list.go
  pkg/kn/commands/service/update.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/traffic/compute.go
  pkg/printers/tableprinter.go
  pkg/wait/poll_watcher.go
  pkg/wait/wait_for_ready.go
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1228 Enable gosec linter and fix existing issues
  .golangci.yaml
  pkg/dynamic/client.go
  pkg/kn/commands/broker/list.go
  pkg/kn/commands/channel/flags.go
  pkg/kn/commands/revision/human_readable_flags.go
  pkg/kn/commands/route/human_readable_flags.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/human_readable_flags.go
  pkg/kn/commands/source/apiserver/flags.go
  pkg/kn/commands/source/binding/flags.go
  pkg/kn/commands/source/container/human_readable_flags.go
  pkg/kn/commands/source/duck/multisourcelist.go
  pkg/kn/commands/source/human_readable_flags.go
  pkg/kn/commands/source/ping/flags.go
  pkg/kn/commands/subscription/flags.go
  pkg/kn/commands/trigger/list_flags.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/plugin/manager.go
  pkg/serving/service.go
  pkg/util/corev1_helper.go
Labels: approved, cla: yes, lgtm, size/L

#1230 [Automated] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1219 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/controller/stats_reporter.go
  vendor/knative.dev/pkg/metrics/memstats.go
  vendor/knative.dev/pkg/metrics/reflector.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_helpers.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/XL

#1229 Reorg OWNERS and introduced OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1233 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/sources/config/ping_defaults.go
  vendor/knative.dev/eventing/pkg/apis/sources/config/store.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1alpha2/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/M

#1235 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/S

#1237 [master] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/configuration_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, size/M

#1238 chore: Update for release 0.21.0
  CHANGELOG.adoc
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1239 Update to 0.21 deps
  go.mod
  go.sum
  pkg/kn/commands/version/version.go
  vendor/modules.txt
Labels: approved, cla: yes, lgtm, ok-to-test, size/S

#1240 update: Change default to server-side generated revision names (extended)
  CHANGELOG.adoc
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/service_update_mock_test.go
  pkg/kn/commands/service/update.go
  pkg/kn/commands/service/update_test.go
  pkg/serving/v1/client.go
  pkg/serving/v1/client_mock.go
  pkg/serving/v1/client_mock_test.go
  pkg/serving/v1/client_test.go
  pkg/serving/v1/gitops.go
  pkg/serving/v1/gitops_test.go
  pkg/wait/wait_for_ready.go
  pkg/wait/wait_for_ready_test.go
  test/e2e/revision_test.go
  test/e2e/service_test.go
  test/e2e/traffic_split_test.go
Labels: approved, cla: yes, lgtm, size/L

#1242 chore: Update E2E setup to latest release
  test/presubmit-integration-tests-latest-release.sh
Labels: approved, cla: yes, lgtm, size/XS

#1243 Adding itsmurugappan to the `reviewers:` list
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS

#1244 Adding dsimansk to reviewers:
  OWNERS
Labels: approved, cla: yes, lgtm, size/XS
