Repository knative/client, pull requests merged in 2021-09, with the labels that each got.

#1444 [release-0.25] Fix release script to published darwin/arm64 bits
  hack/release.sh
Labels: size/XS, lgtm, approved, cla: yes

#1442 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_validation.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/pkg/reconciler/leader.go
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/knative.dev/pkg/test/request.go
  vendor/knative.dev/pkg/test/spoof/response_checks.go
  vendor/knative.dev/pkg/test/spoof/spoof.go
  vendor/knative.dev/serving/test/adding_tests.md
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1441 Adding retry loop to update
  CHANGELOG.adoc
  pkg/eventing/v1/client.go
  pkg/eventing/v1/client_mock.go
  pkg/eventing/v1/client_mock_test.go
  pkg/eventing/v1/client_test.go
  pkg/kn/commands/domain/update.go
  pkg/kn/commands/source/container/update.go
  pkg/kn/commands/source/ping/ping.go
  pkg/kn/commands/source/ping/update.go
  pkg/kn/commands/subscription/update.go
  pkg/kn/commands/trigger/update.go
  pkg/messaging/v1/subscriptions_client.go
  pkg/messaging/v1/subscriptions_client_mock.go
  pkg/serving/v1/client.go
  pkg/serving/v1alpha1/client.go
  pkg/serving/v1alpha1/client_mock.go
  pkg/serving/v1alpha1/client_mock_test.go
  pkg/serving/v1alpha1/client_test.go
  pkg/sources/v1/container_client.go
  pkg/sources/v1/container_client_mock.go
  pkg/sources/v1/container_client_mock_test.go
  pkg/sources/v1/container_client_test.go
  pkg/sources/v1beta2/ping_client.go
  pkg/sources/v1beta2/ping_client_mock.go
  pkg/sources/v1beta2/ping_client_mock_test.go
  pkg/sources/v1beta2/ping_client_test.go
Labels: size/XL, lgtm, approved, cla: yes

#1448 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/apis/duck/ABOUT.md
  vendor/knative.dev/pkg/apis/duck/v1/podspec_defaults.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_types.go
  vendor/knative.dev/pkg/apis/duck/v1/podspec_validation.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/reconciler/reconcile_common.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1454 Remove `DeprecatedImageDigest` field
  pkg/kn/commands/revision/describe.go
  pkg/kn/commands/revision/describe_test.go
  pkg/kn/commands/service/describe_test.go
  pkg/kn/commands/service/update_test.go
Labels: lgtm, approved, size/S, cla: yes

#1453 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/S, cla: yes

#1451 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/M, cla: yes

#1452 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/container_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/sinkbinding_validation.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1beta2/ping_validation.go
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1455 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: lgtm, approved, size/L, cla: yes

#1456 Update changelog for 0.26 release
  CHANGELOG.adoc
Labels: lgtm, approved, size/S, cla: yes

#1278 Fix describe/list commands with json/yaml output format
  pkg/eventing/v1/client.go
  pkg/eventing/v1/client_test.go
  pkg/kn/commands/broker/broker_test.go
  pkg/kn/commands/broker/describe_test.go
  pkg/kn/commands/broker/list_test.go
  pkg/kn/commands/channel/describe_test.go
  pkg/kn/commands/channel/list_test.go
  pkg/kn/commands/channel/list_types_test.go
  pkg/kn/commands/route/list_test.go
  pkg/kn/commands/service/describe_test.go
  pkg/kn/commands/service/list_test.go
  pkg/kn/commands/subscription/describe_test.go
  pkg/kn/commands/subscription/list_test.go
  pkg/kn/commands/trigger/describe_test.go
  pkg/kn/commands/trigger/list_test.go
  pkg/kn/commands/trigger/trigger_test.go
  pkg/messaging/v1/channels_client.go
  pkg/messaging/v1/subscriptions_client.go
  pkg/util/unstructured.go
  pkg/util/unstructured_test.go
Labels: size/XL, lgtm, approved, ok-to-test, cla: yes

#1457 Fix windows e2e plugin tests
  hack/build.sh
  test/e2e/plugins_test.go
Labels: lgtm, approved, size/M, cla: yes

#1458 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S, cla: yes

#1459 Update versions for 0.26.0
  CHANGELOG.adoc
  pkg/kn/commands/version/version.go
  pkg/kn/config/config_test.go
  test/presubmit-integration-tests-latest-release.sh
Labels: lgtm, approved, size/S, cla: yes

#1460 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, cla: yes

#1462 Automatically set the proper version for the serving and eventing dependencies
  hack/build-flags.sh
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
Labels: lgtm, approved, size/S, cla: yes

#1461 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/S, cla: yes

#1464 Renaming COC doc to ALLCAPS
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/S, cla: yes, kind/documentation

#1467 Fix sync serviceDelete in test utils
  lib/test/service.go
Labels: size/XS, lgtm, approved, cla: yes
