Repository knative/client, pull requests merged in 2022-06, with the labels that each got.

#1685 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1686 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1687 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1689 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1688 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/metrics/metrics_worker.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/serving/test/test_images/grpc-ping/proto/ping.pb.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1690 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/go.uber.org/multierr/LICENSE.txt
  vendor/github.com/cloudevents/sdk-go/v2/client/client.go
  vendor/github.com/cloudevents/sdk-go/v2/client/options.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_data.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol_retry.go
  vendor/go.uber.org/multierr/.travis.yml
  vendor/go.uber.org/multierr/CHANGELOG.md
  vendor/go.uber.org/multierr/LICENSE.txt
  vendor/go.uber.org/multierr/Makefile
  vendor/go.uber.org/multierr/README.md
  vendor/go.uber.org/multierr/error.go
  vendor/go.uber.org/zap/.readme.tmpl
  vendor/go.uber.org/zap/CHANGELOG.md
  vendor/go.uber.org/zap/README.md
  vendor/go.uber.org/zap/global.go
  vendor/go.uber.org/zap/global_go112.go
  vendor/go.uber.org/zap/global_prego112.go
  vendor/go.uber.org/zap/level.go
  vendor/go.uber.org/zap/logger.go
  vendor/go.uber.org/zap/stacktrace.go
  vendor/go.uber.org/zap/zapcore/clock.go
  vendor/go.uber.org/zap/zapcore/console_encoder.go
  vendor/go.uber.org/zap/zapcore/encoder.go
  vendor/go.uber.org/zap/zapcore/json_encoder.go
  vendor/go.uber.org/zap/zapcore/level.go
  vendor/go.uber.org/zap/zapcore/reflected_encoder.go
  vendor/go.uber.org/zap/zapcore/sampler.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/certificates/v1/types.go
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/pkg/version/.gitattributes
  vendor/k8s.io/client-go/tools/cache/thread_safe_store.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_types.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1679 Added support for mounting EmptyDir volume type
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
Labels: lgtm, approved, size/L

#1695 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1696 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
