Repository knative/client, pull requests merged in 2022-03, with the labels that each got.

#1601 change display versions
  hack/build-flags.sh
Labels: lgtm, approved, size/S, ok-to-test

#1613 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/net/http2/go118.go
  vendor/golang.org/x/net/http2/not_go118.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/sys/unix/ioctl_linux.go
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_linux_386.go
  vendor/golang.org/x/sys/unix/syscall_linux_alarm.go
  vendor/golang.org/x/sys/unix/syscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm.go
  vendor/golang.org/x/sys/unix/syscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_mipsx.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/syscall_linux_ppc64x.go
  vendor/golang.org/x/sys/unix/syscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/syscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/syscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_386.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsyscall_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/knative.dev/pkg/configmap/parse.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#1612 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1598 Added eventtype support
  docs/cmd/kn.md
  docs/cmd/kn_eventtype.md
  docs/cmd/kn_eventtype_create.md
  docs/cmd/kn_eventtype_delete.md
  docs/cmd/kn_eventtype_describe.md
  docs/cmd/kn_eventtype_list.md
  lib/test/eventtype.go
  pkg/eventing/v1beta1/client.go
  pkg/eventing/v1beta1/client_mock.go
  pkg/eventing/v1beta1/client_mock_test.go
  pkg/eventing/v1beta1/client_test.go
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/eventtype/create.go
  pkg/kn/commands/eventtype/create_test.go
  pkg/kn/commands/eventtype/delete.go
  pkg/kn/commands/eventtype/delete_test.go
  pkg/kn/commands/eventtype/describe.go
  pkg/kn/commands/eventtype/describe_test.go
  pkg/kn/commands/eventtype/eventtype.go
  pkg/kn/commands/eventtype/eventtype_test.go
  pkg/kn/commands/eventtype/list.go
  pkg/kn/commands/eventtype/list_test.go
  pkg/kn/commands/flags/eventtype.go
  pkg/kn/commands/flags/eventtype_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  pkg/kn/root/root.go
  test/e2e/eventtype_test.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1611 [main] Update actions
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-style.yaml
Labels: lgtm, approved, size/S

#1614 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1618 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1619 Update changelog for 1.3 release
  CHANGELOG.adoc
Labels: lgtm, approved, size/S

#1617 Traffic split auto redirection should only consider the active revisions
  pkg/kn/traffic/compute.go
  pkg/kn/traffic/compute_test.go
  test/e2e/traffic_split_test.go
Labels: lgtm, approved, size/M

#1620 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/autoscaling/annotation_validation.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/metadata_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/autoscaler/config/autoscalerconfig/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/autoscaling_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/metric.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/autoscaling/v1alpha1/podautoscaler.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_configuration.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/fake/fake_serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/revision.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/route.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/service.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1/serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/fake/fake_serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/serving_client.go
  vendor/knative.dev/serving/pkg/gc/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/zz_generated.deepcopy.go
  vendor/knative.dev/serving/test/test_images/grpc-ping/proto/ping.pb.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1621 Refactor version command to use go modules
  go.mod
  pkg/kn/commands/version/version.go
  pkg/kn/commands/version/version_test.go
  third_party/VENDOR-LICENSE/golang.org/x/mod/semver/LICENSE
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1623 Grab latest version in presubmit
  test/presubmit-integration-tests-latest-release.sh
Labels: size/XS, lgtm, approved

#1622 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1626 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1628 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1627 Infer versions for E2E tests from current branch
  test/common.sh
  test/presubmit-integration-tests-latest-release.sh
Labels: lgtm, approved, size/M

#1634 Adding code of conduct to reference knative/community's CoC
  CODE-OF-CONDUCT.md
Labels: lgtm, approved, size/M

#1630 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1635 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/api/policy/v1beta1/generated.proto
  vendor/k8s.io/api/policy/v1beta1/types.go
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/exit.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/hack/CODE-OF-CONDUCT.md
  vendor/knative.dev/hack/CODE_OF_CONDUCT.md
  vendor/knative.dev/networking/pkg/apis/networking/ports.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/serving/pkg/apis/autoscaling/v1alpha1/pa_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/service_validation.go
  vendor/knative.dev/serving/pkg/autoscaler/config/config.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL
