Repository knative/client, pull requests merged in 2022-05, with the labels that each got.

#1667 Bump Tekton pipeline version to latest by default
  test/tekton-tests.sh
Labels: size/XS, lgtm, approved

#1668 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1672 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1673 Fix Tekton e2e script
  test/tekton-tests.sh
Labels: size/XS, lgtm, approved

#1669 Cleanup sugar controller setup
  test/common.sh
Labels: size/XS, lgtm, approved

#1671 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/pkg/apis/deprecated.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/logging/config.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1674 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1676 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1675 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/update_test.go
  test/e2e/service_test.go
  third_party/VENDOR-LICENSE/k8s.io/utils/internal/third_party/forked/golang/LICENSE
  vendor/k8s.io/utils/internal/third_party/forked/golang/golang-lru/lru.go
  vendor/k8s.io/utils/lru/lru.go
  vendor/knative.dev/networking/pkg/apis/networking/register.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/networking/pkg/config/doc.go
  vendor/knative.dev/networking/pkg/config/zz_generated.deepcopy.go
  vendor/knative.dev/networking/pkg/deprecated_config.go
  vendor/knative.dev/networking/pkg/deprecated_header.go
  vendor/knative.dev/networking/pkg/deprecated_http.go
  vendor/knative.dev/networking/pkg/deprecated_labels.go
  vendor/knative.dev/networking/pkg/deprecated_port.go
  vendor/knative.dev/networking/pkg/http/constants.go
  vendor/knative.dev/networking/pkg/http/error.go
  vendor/knative.dev/networking/pkg/http/header/header.go
  vendor/knative.dev/networking/pkg/http/probe/handler.go
  vendor/knative.dev/networking/pkg/http/proxy/bufferpool.go
  vendor/knative.dev/networking/pkg/http/proxy/constants.go
  vendor/knative.dev/networking/pkg/http/stats/request.go
  vendor/knative.dev/networking/pkg/k8s/ports.go
  vendor/knative.dev/serving/pkg/networking/util.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/store.go
  vendor/knative.dev/serving/pkg/reconciler/route/domains/domains.go
  vendor/knative.dev/serving/pkg/reconciler/route/resources/labels/labels.go
  vendor/knative.dev/serving/test/test_images/grpc-ping/main.go
  vendor/knative.dev/serving/test/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1678 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M
