Repository knative/client, pull requests merged in 2022-08, with the labels that each got.

#1714 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/k8s.io/klog/v2/README.md
  vendor/k8s.io/klog/v2/contextual.go
  vendor/k8s.io/klog/v2/imports.go
  vendor/k8s.io/klog/v2/internal/clock/README.md
  vendor/k8s.io/klog/v2/internal/clock/clock.go
  vendor/k8s.io/klog/v2/internal/dbg/dbg.go
  vendor/k8s.io/klog/v2/internal/serialize/keyvalues.go
  vendor/k8s.io/klog/v2/k8s_references.go
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klogr.go
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#1715 Bump Go version to 1.18
  go.mod
  go.sum
Labels: lgtm, approved, kind/cleanup

#1716 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_types.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1717 Add support for providing sink spec in GVR format
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
Labels: lgtm, approved, size/S, kind/enhancement

#1718 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1720 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1721 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved, skip-review

#1719 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/configuration.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1726 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1724 Added gvr sink test cases and support to specify resource as singular/plural
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
Labels: lgtm, approved, size/S, kind/enhancement

#1725 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1727 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1728 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/defaults.go
  vendor/modules.txt
Labels: lgtm, approved, size/S
