Repository knative/client, pull requests merged in 2022-04, with the labels that each got.

#1636 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/S

#1637 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/XL, lgtm, approved

#1640 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1638 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/pkg/leaderelection/context.go
  vendor/knative.dev/serving/pkg/networking/util.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1639 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#1646 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1647 Fix latest release CI setup
  test/common.sh
Labels: lgtm, approved, size/S

#1649 Align codecov config with rest of the org
  .codecov.yaml
Labels: lgtm, approved, size/S

#1650 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/networking/pkg/network.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1651 [main] Update actions
  .github/workflows/knative-go-test.yaml
Labels: size/XS, lgtm, approved

#1644 Added pull-policy flag to service
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/commands/service/configuration_edit_flags_test.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/kn/flags/podspec_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
Labels: lgtm, approved, size/L

#1643 Add timeout option to service create
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/service/create_test.go
Labels: lgtm, approved, size/S

#1652 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/generate-cert.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1653 Added scale-metric flag to configure metric name
  CHANGELOG.adoc
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/configuration_edit_flags_test.go
  pkg/serving/config_changes.go
  pkg/serving/config_changes_test.go
  vendor/k8s.io/code-generator/generate-groups.sh
  vendor/knative.dev/pkg/hack/generate-knative.sh
Labels: lgtm, approved, size/L

#1655 Added subpath functionality to --mount flag
  CHANGELOG.adoc
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_test.go
  test/e2e/service_test.go
Labels: lgtm, approved, size/L

#1657 Fix build warning from go version upgrade
  go.mod
  go.sum
  vendor/github.com/prometheus/procfs/Makefile
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/README.md
  vendor/github.com/prometheus/procfs/cmdline.go
  vendor/github.com/prometheus/procfs/doc.go
  vendor/github.com/prometheus/procfs/fixtures.ttar
  vendor/github.com/prometheus/procfs/mdstat.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/netstat.go
  vendor/github.com/prometheus/procfs/proc_cgroup.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/github.com/prometheus/procfs/zoneinfo.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1658 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/generate-cert.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1659 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1660 test: use `T.TempDir` to create temporary test directory
  CHANGELOG.adoc
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/namespaced_test.go
  pkg/kn/commands/plugin/list_test.go
  pkg/kn/commands/service/create_test.go
  pkg/kn/commands/service/import_test.go
  pkg/kn/commands/types_test.go
  pkg/kn/config/config_test.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/kn/flags/podspec_test.go
  pkg/kn/plugin/manager_test.go
  pkg/serving/v1/gitops_test.go
  test/e2e/channels_test.go
  test/e2e/extra_containers_test.go
  test/e2e/plugins_test.go
  test/e2e/service_file_test.go
  test/e2e/service_import_test.go
  test/e2e/sinkprefix_test.go
Labels: lgtm, approved, size/L, ok-to-test

#1664 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1661 Mark --inject-broker flag as deprecated
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  pkg/kn/commands/trigger/update_flags.go
Labels: size/XS, lgtm, approved

#1662 Fix display version in OCI image
  .ko.yaml
  hack/build-flags.sh
Labels: lgtm, approved, size/S

#1663 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/pkg/hack/update-codegen.sh
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1666 Fix OCI image build
  hack/build-flags.sh
  hack/build.sh
  hack/release.sh
Labels: lgtm, approved, size/M
