Repository knative/client, pull requests merged in 2022-01, with the labels that each got.

#1547 Added autocompletion for service name
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/namespaced.go
  pkg/kn/commands/service/delete.go
  pkg/kn/commands/service/describe.go
  pkg/kn/commands/service/update.go
Labels: lgtm, approved, size/L

#1554 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#1559 Added autocompletion for broker
  pkg/kn/commands/broker/delete.go
  pkg/kn/commands/broker/describe.go
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
Labels: lgtm, approved, size/L

#1560 Added completion for revision resource
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/revision/delete.go
  pkg/kn/commands/revision/describe.go
Labels: lgtm, approved, size/L

#1563 Remove deprecated Hugo frontmatter generation for docs
  CHANGELOG.adoc
  hack/generate-docs.go
Labels: lgtm, approved, size/M

#1561 Added completion for route name
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/route/describe.go
Labels: lgtm, approved, size/L

#1564 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1562 Added completion for domain command
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/domain/delete.go
  pkg/kn/commands/domain/describe.go
  pkg/kn/commands/domain/update.go
Labels: lgtm, approved, size/L

#1568 Fix for panic during channel list
  CHANGELOG.adoc
  pkg/kn/commands/channel/flags.go
Labels: lgtm, approved, size/S

#1566 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved

#1565 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/k8s.io/klog/LICENSE
  vendor/github.com/go-logr/logr/.golangci.yaml
  vendor/github.com/go-logr/logr/CHANGELOG.md
  vendor/github.com/go-logr/logr/CONTRIBUTING.md
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/discard.go
  vendor/github.com/go-logr/logr/go.mod
  vendor/github.com/go-logr/logr/logr.go
  vendor/k8s.io/klog/.travis.yml
  vendor/k8s.io/klog/CONTRIBUTING.md
  vendor/k8s.io/klog/LICENSE
  vendor/k8s.io/klog/README.md
  vendor/k8s.io/klog/RELEASE.md
  vendor/k8s.io/klog/SECURITY_CONTACTS
  vendor/k8s.io/klog/code-of-conduct.md
  vendor/k8s.io/klog/go.mod
  vendor/k8s.io/klog/go.sum
  vendor/k8s.io/klog/klog.go
  vendor/k8s.io/klog/klog_file.go
  vendor/k8s.io/klog/v2/go.mod
  vendor/k8s.io/klog/v2/go.sum
  vendor/k8s.io/klog/v2/klog.go
  vendor/k8s.io/klog/v2/klog_file.go
  vendor/k8s.io/klog/v2/klog_file_others.go
  vendor/k8s.io/klog/v2/klog_file_windows.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/source_types.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_duck.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/fake_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_factory.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_controller_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_reconciler_stub.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/reconciler_state.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/main.go
  vendor/knative.dev/pkg/injection/config.go
  vendor/knative.dev/pkg/leaderelection/config.go
  vendor/knative.dev/pkg/leaderelection/doc.go
  vendor/knative.dev/pkg/test/logging/logging.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1567 Adding completion for remaining Eventing resources
  pkg/kn/commands/channel/delete.go
  pkg/kn/commands/channel/describe.go
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/source/apiserver/delete.go
  pkg/kn/commands/source/apiserver/describe.go
  pkg/kn/commands/source/apiserver/update.go
  pkg/kn/commands/source/binding/delete.go
  pkg/kn/commands/source/binding/describe.go
  pkg/kn/commands/source/binding/update.go
  pkg/kn/commands/source/container/delete.go
  pkg/kn/commands/source/container/describe.go
  pkg/kn/commands/source/ping/delete.go
  pkg/kn/commands/source/ping/describe.go
  pkg/kn/commands/source/ping/update.go
  pkg/kn/commands/subscription/delete.go
  pkg/kn/commands/subscription/describe.go
  pkg/kn/commands/subscription/update.go
  pkg/kn/commands/trigger/delete.go
  pkg/kn/commands/trigger/describe.go
  pkg/kn/commands/trigger/update.go
  pkg/kn/commands/types.go
Labels: lgtm, approved, size/XXL

#1569 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1572 Remove k8s cluster version pin
  test/e2e-tests.sh
Labels: size/XS, lgtm, approved

#1571 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/pkg/testing/v1/revision.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1573 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/spf13/afero/README.md
  vendor/github.com/spf13/afero/cacheOnReadFs.go
  vendor/github.com/spf13/afero/go.mod
  vendor/github.com/spf13/afero/go.sum
  vendor/github.com/spf13/afero/unionFile.go
  vendor/github.com/spf13/viper/go.mod
  vendor/github.com/spf13/viper/go.sum
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#1575 Fix for file not found error message discrepancy in windows
  test/e2e/service_file_test.go
  test/e2e/service_import_test.go
Labels: lgtm, approved, size/S

#1576 Update changelog for 1.2 release
  CHANGELOG.adoc
Labels: lgtm, approved, size/M

#1578 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1577 Updates kn versions for presubmit integration test
  test/presubmit-integration-tests-latest-release.sh
Labels: size/XS, lgtm, approved

#1592 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved
