Repository knative/client, pull requests merged in 2022-02, with the labels that each got.

#1594 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1593 Update README.md
  docs/README.md
Labels: size/XS, lgtm, approved

#1595 [main] Update actions
  .github/workflows/knative-security.yaml
Labels: size/XS, lgtm, approved

#1596 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/e2e-tests.sh
  vendor/knative.dev/hack/infra-library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/resolver/addressable_resolver.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1599 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1600 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/e2e-auto-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/knative.dev/serving/test/prober.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1602 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_validation.go
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/networking/pkg/network.go
  vendor/knative.dev/serving/test/README.md
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1605 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1597 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: lgtm, approved, size/M

#1606 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved

#1607 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/testing/v1/service.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/knative.dev/serving/test/e2e-upgrade-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1608 [main] Update actions
  .github/workflows/knative-style.yaml
Labels: size/XS, lgtm, approved

#1603 remove hardcoded kn for usage and error
  cmd/kn/main.go
  cmd/kn/main_test.go
  docs/cmd/kn.md
  hack/generate-docs.go
  pkg/kn/root/root.go
  pkg/kn/root/root_test.go
Labels: lgtm, approved, size/M

#1610 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  third_party/VENDOR-LICENSE/golang.org/x/sync/LICENSE
  vendor/cloud.google.com/go/compute/LICENSE
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_go113.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/errors_xerrors.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/export_unsafe.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
  vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
  vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
  vendor/github.com/google/go-cmp/cmp/internal/value/name.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/github.com/google/go-cmp/cmp/report_slices.go
  vendor/github.com/gregjones/httpcache/README.md
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
  vendor/golang.org/x/term/codereview.cfg
  vendor/golang.org/x/term/term.go
  vendor/golang.org/x/tools/internal/imports/sortimports.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/credentials/insecure/insecure.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/grpclog/loggerv2.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpclog/grpclog.go
  vendor/google.golang.org/grpc/internal/grpcutil/regex.go
  vendor/google.golang.org/grpc/regenerate.sh
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/trigger_validation.go
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/url.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/controller/controller.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XXL
