Repository knative/client, pull requests merged in 2022-10, with the labels that each got.

#1732 Added config support to specify read only volumes
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
  test/e2e/service_test.go
Labels: lgtm, approved, size/L

#1738 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_config_set.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserialization_options.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_deserializer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/atn_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/dfa_state.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/error_strategy.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/lexer_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/ll1_analyzer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/parser_atn_simulator.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/recognizer.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/semantic_context.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/tree.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils.go
  vendor/github.com/antlr/antlr4/runtime/Go/antlr/utils_set.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/README.md
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParser.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/CESQLParserLexer.interp
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_base_visitor.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_lexer.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_parser.go
  vendor/github.com/cloudevents/sdk-go/sql/v2/gen/cesqlparser_visitor.go
  vendor/github.com/cloudevents/sdk-go/v2/alias.go
  vendor/github.com/cloudevents/sdk-go/v2/event/event_unmarshal.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/protocol.go
  vendor/github.com/cloudevents/sdk-go/v2/protocol/http/utility.go
  vendor/knative.dev/hack/release.sh
  vendor/modules.txt
Labels: lgtm, approved, size/XXL

#1743 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1744 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, lgtm, approved, skip-review

#1747 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e_flags.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1749 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/reconciler/route/config/domain.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1750 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1751 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1752 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#1753 Fix namespaced unit test
  pkg/kn/commands/namespaced_test.go
Labels: lgtm, approved, size/S

#1755 Resolve Serving version to released tag
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved

#1757 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1759 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
