Repository knative/client, pull requests merged in 2022-09, with the labels that each got.

#1729 Add --scale-activation flag to match new Serving option
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  pkg/kn/commands/service/configuration_edit_flags.go
  pkg/kn/commands/service/configuration_edit_flags_test.go
  pkg/serving/config_changes.go
  test/e2e/service_options_test.go
Labels: kind/feature, lgtm, approved, size/M

#1730 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/test/kube_checks.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1733 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/S

#1737 Fix release script version calculation
  hack/release.sh
Labels: kind/bug, size/XS, lgtm, approved

#1736 Update knb to recognize drop-in module replace
  tools/knb/README.md
  tools/knb/pkg/plugin/distro.go
  tools/knb/pkg/plugin/plugin.go
Labels: lgtm, approved, size/M

#1739 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1740 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
