Repository knative/client, pull requests merged in 2023-08, with the labels that each got.

#1837 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: size/S, skip-review

#1839 Remove e2e skip flags after release
  test/e2e/eventtype_test.go
  test/e2e/service_export_test.go
Labels: lgtm, approved, size/S

#1844 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1845 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1850 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1849 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/tools/internal/gocommand/invoke.go
  vendor/golang.org/x/tools/internal/gopathwalk/walk.go
  vendor/golang.org/x/tools/internal/imports/mod_cache.go
  vendor/golang.org/x/tools/internal/typeparams/common.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go117.go
  vendor/golang.org/x/tools/internal/typeparams/typeparams_go118.go
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/pubsub.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/shared_buffer_pool.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#1847 Remove unusable `--broker` flag from `trigger update` cmd
  docs/cmd/kn_trigger_update.md
  pkg/kn/commands/trigger/update_flags.go
  pkg/kn/commands/trigger/update_test.go
Labels: kind/bug, lgtm, approved, size/S

#1856 Upgrade deprecated v1alpha1 DomainMapping API to newer one
  go.mod
  go.sum
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/domain/create.go
  pkg/kn/commands/domain/create_test.go
  pkg/kn/commands/domain/delete.go
  pkg/kn/commands/domain/delete_test.go
  pkg/kn/commands/domain/describe.go
  pkg/kn/commands/domain/describe_test.go
  pkg/kn/commands/domain/domain_test.go
  pkg/kn/commands/domain/human_readable_flags.go
  pkg/kn/commands/domain/list.go
  pkg/kn/commands/domain/list_test.go
  pkg/kn/commands/domain/update.go
  pkg/kn/commands/domain/update_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  pkg/serving/v1beta1/client.go
  pkg/serving/v1beta1/client_mock.go
  pkg/serving/v1beta1/client_mock_test.go
  pkg/serving/v1beta1/client_test.go
  vendor/gomodules.xyz/jsonpatch/v2/jsonpatch.go
  vendor/knative.dev/networking/pkg/config/config.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/README.md
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/conversion_error.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_defaults.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_types.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/domainmapping_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/scheme/register.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/generated_expansion.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1alpha1/serving_client.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/doc.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_domainmapping.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/typed/serving/v1beta1/fake/fake_serving_client.go
  vendor/knative.dev/serving/test/clients.go
  vendor/modules.txt
Labels: lgtm, approved, size/XXL, ok-to-test, kind/cleanup

#1853 Remove deprecated --inject-broker flag from trigger cmds
  pkg/kn/commands/trigger/create.go
  pkg/kn/commands/trigger/create_test.go
  pkg/kn/commands/trigger/update_flags.go
  test/e2e/trigger_inject_broker_test.go
Labels: lgtm, approved, size/L, ok-to-test, kind/cleanup

#1848 Update PR template not to mention changelog anymore
  .github/pull-request-template.md
Labels: lgtm, approved, size/S
