Repository knative/client, pull requests merged in 2023-04, with the labels that each got.

#1798 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/config/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/zz_generated.deepcopy.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/pkg/apis/duck/v1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1/knative_reference.go
  vendor/knative.dev/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/addressable_types.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/destination.go
  vendor/knative.dev/pkg/apis/duck/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/injection/health_check.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/serving/pkg/apis/serving/v1alpha1/zz_generated.deepcopy.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1804 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1802 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1803 [main] Update actions
  .github/workflows/knative-boilerplate.yaml
  .github/workflows/knative-donotsubmit.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-vulnerability.yaml
Labels: size/L, skip-review

#1807 [main] Update actions
  .github/workflows/knative-release-notes.yaml
Labels: size/S, skip-review

#1794 feat: Add experimental filters to trigger describe cmd
  pkg/kn/commands/trigger/describe.go
  pkg/kn/commands/trigger/describe_test.go
Labels: lgtm, approved, size/L

#1805 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/release.sh
  vendor/knative.dev/pkg/metrics/opencensus_exporter.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1793 fix: Use go_run from common lib
  hack/build.sh
Labels: lgtm, approved, size/S

#1809 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/networking/constants.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1810 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
