Repository knative/client, pull requests merged in 2023-07, with the labels that each got.

#1825 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1826 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1821 Add default SecurityContext to every new ksvc
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  go.mod
  lib/test/service.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/source/container/container_test.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/kn/flags/podspec_test.go
  test/e2e/service_export_test.go
Labels: lgtm, approved, size/L

#1816 Fix plugin inlining that uses client-pkg dependency
  go.mod
  go.sum
  pkg/kn/plugin/manager.go
  pkg/kn/plugin/manager_test.go
  third_party/VENDOR-LICENSE/knative.dev/client-pkg/pkg/kn/plugin/LICENSE
  vendor/knative.dev/client-pkg/LICENSE
  vendor/knative.dev/client-pkg/pkg/kn/plugin/types.go
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#1828 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/hack/presubmit-tests.sh
  vendor/knative.dev/serving/pkg/apis/config/features.go
  vendor/knative.dev/serving/pkg/apis/serving/register.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_validation.go
  vendor/knative.dev/serving/test/cleanup.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1831 Add support for Eventing/v1beta2 EventTypes
  docs/cmd/kn_eventtype_create.md
  docs/cmd/kn_source_apiserver_create.md
  docs/cmd/kn_source_apiserver_update.md
  docs/cmd/kn_source_binding_create.md
  docs/cmd/kn_source_binding_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  docs/cmd/kn_source_ping_create.md
  docs/cmd/kn_source_ping_update.md
  docs/cmd/kn_subscription_create.md
  docs/cmd/kn_subscription_update.md
  docs/cmd/kn_trigger_create.md
  docs/cmd/kn_trigger_update.md
  hack/build.sh
  pkg/eventing/v1beta2/client.go
  pkg/eventing/v1beta2/client_mock.go
  pkg/eventing/v1beta2/client_mock_test.go
  pkg/eventing/v1beta2/client_test.go
  pkg/kn/commands/broker/delivery_option_flags.go
  pkg/kn/commands/completion_helper.go
  pkg/kn/commands/completion_helper_test.go
  pkg/kn/commands/eventtype/create.go
  pkg/kn/commands/eventtype/create_test.go
  pkg/kn/commands/eventtype/delete.go
  pkg/kn/commands/eventtype/delete_test.go
  pkg/kn/commands/eventtype/describe.go
  pkg/kn/commands/eventtype/describe_test.go
  pkg/kn/commands/eventtype/eventtype.go
  pkg/kn/commands/eventtype/eventtype_test.go
  pkg/kn/commands/eventtype/list.go
  pkg/kn/commands/eventtype/list_test.go
  pkg/kn/commands/flags/eventtype.go
  pkg/kn/commands/flags/sink.go
  pkg/kn/commands/flags/sink_test.go
  pkg/kn/commands/types.go
  pkg/kn/commands/types_test.go
  test/e2e/eventtype_test.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/doc.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventing_client.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/fake/fake_eventtype.go
  vendor/knative.dev/eventing/pkg/client/clientset/versioned/typed/eventing/v1beta2/generated_expansion.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#1832 Change default SecurityContext to none
  docs/cmd/kn_container_add.md
  docs/cmd/kn_service_apply.md
  docs/cmd/kn_service_create.md
  docs/cmd/kn_service_update.md
  docs/cmd/kn_source_container_create.md
  docs/cmd/kn_source_container_update.md
  lib/test/service.go
  pkg/kn/commands/service/create_mock_test.go
  pkg/kn/commands/source/container/container_test.go
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_helper_test.go
  pkg/kn/flags/podspec_test.go
  test/e2e/service_export_test.go
Labels: lgtm, approved, size/M

#1834 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1835 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1836 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: size/XS, lgtm, approved
