Repository knative/client, pull requests merged in 2023-10, with the labels that each got.

#1872 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1875 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1878 [release-1.10] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1880 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1855 Context Sharing POC
  cmd/kn/main.go
  cmd/kn/main_test.go
  pkg/kn/commands/service/describe.go
  pkg/kn/config/config.go
  pkg/kn/config/config_test.go
  pkg/kn/config/testing.go
  pkg/kn/config/testing_test.go
  pkg/kn/config/types.go
  pkg/kn/plugin/context_sharing.go
  pkg/kn/plugin/context_sharing_test.go
  pkg/kn/plugin/context_types.go
  pkg/kn/plugin/manager.go
Labels: size/XL, lgtm, approved

#1881 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/golang.org/x/tools/imports/forward.go
  vendor/golang.org/x/tools/internal/fastwalk/fastwalk_portable.go
  vendor/golang.org/x/tools/internal/imports/fix.go
  vendor/golang.org/x/tools/internal/imports/mod.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/subscription_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/ping_lifecycle.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/network/transports.go
  vendor/modules.txt
Labels: size/XL, lgtm, approved

#1882 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/feature/features.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/apis/serving/v1beta1/domainmapping_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-external-domain-tls-tests.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1883 [release-1.11] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1884 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved, size/S
