Repository knative/client, pull requests merged in 2023-06, with the labels that each got.

#1819 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1820 Fix broker condition check
  lib/test/eventtype.go
Labels: size/XS, lgtm, approved

#1822 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, lgtm, approved, skip-review

#1817 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/eventing/pkg/apis/duck/v1/delivery_types.go
  vendor/knative.dev/eventing/pkg/apis/duck/v1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/broker_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1/test_helper.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_conversion.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta1/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_defaults.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/eventtype_types.go
  vendor/knative.dev/eventing/pkg/apis/eventing/v1beta2/zz_generated.deepcopy.go
  vendor/knative.dev/eventing/pkg/apis/feature/flag_names.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/messaging/v1/in_memory_channel_lifecycle.go
  vendor/knative.dev/eventing/pkg/apis/sources/v1/apiserver_lifecycle.go
  vendor/knative.dev/hack/README.md
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/certificate_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/domain_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/ingress_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_defaults.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/realm_validation.go
  vendor/knative.dev/networking/pkg/apis/networking/v1alpha1/serverlessservice_defaults.go
  vendor/knative.dev/networking/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/pkg/apis/duck/v1/kresource_type.go
  vendor/knative.dev/pkg/environment/client_config.go
  vendor/knative.dev/pkg/injection/clients.go
  vendor/knative.dev/pkg/injection/informers.go
  vendor/knative.dev/pkg/injection/interface.go
  vendor/knative.dev/serving/pkg/client/clientset/versioned/clientset.go
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L
