Repository knative/client, pull requests merged in 2023-03, with the labels that each got.

#1784 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1787 Helloworld image running with non root user
  test/test_images/helloworld/Dockerfile
Labels: size/XS, lgtm, approved

#1789 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1786 [main] Update actions
  .github/workflows/knative-go-build.yaml
  .github/workflows/knative-go-test.yaml
  .github/workflows/knative-releasability.yaml
  .github/workflows/knative-release-notes.yaml
  .github/workflows/knative-security.yaml
  .github/workflows/knative-stale.yaml
  .github/workflows/knative-style.yaml
  .github/workflows/knative-verify.yaml
Labels: lgtm, approved, size/S, skip-review

#1790 [main] Update actions
  .github/workflows/knative-releasability.yaml
Labels: size/XS, skip-review

#1796 fix: Fix image tag for nightly builds
  hack/release.sh
Labels: lgtm, approved, size/S
