Repository knative/client, pull requests merged in 2023-02, with the labels that each got.

#1772 [main] Update community files
  OWNERS_ALIASES
Labels: size/M, skip-review

#1774 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1777 Fixing some linter issues
  pkg/errors/factory_test.go
  pkg/printers/tablegenerator.go
Labels: lgtm, approved, size/S

#1778 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1779 Fixing errors related to Go 1.20
  cmd/kn/main.go
  pkg/printers/tablegenerator.go
  pkg/serving/service.go
  pkg/serving/service_test.go
Labels: lgtm, approved, size/S, ok-to-test
