Repository knative/client, pull requests merged in 2023-09, with the labels that each got.

#1860 Fix shellcheck warnings in hack/build.sh script
  hack/build.sh
Labels: lgtm, approved, size/M, ok-to-test, kind/cleanup

#1862 initial proposal for a 48h Knative proposal template
  .github/ISSUE_TEMPLATE/knative48h.md
Labels: lgtm, approved, size/M

#1864 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1865 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1867 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/hack/go.work.sum
  vendor/knative.dev/hack/library.sh
  vendor/knative.dev/serving/pkg/apis/serving/fieldmask.go
  vendor/knative.dev/serving/pkg/apis/serving/k8s_validation.go
  vendor/knative.dev/serving/pkg/apis/serving/v1/revision_defaults.go
  vendor/knative.dev/serving/test/conformance.go
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1869 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
