Repository knative/client, pull requests merged in 2024-03, with the labels that each got.

#1921 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-common.sh
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/knative.dev/serving/test/e2e-tests.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1918 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1923 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/github.com/golang/protobuf/ptypes/any.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#1919 Fix wait-loop in domain E2E test
  test/e2e/domain_mapping_test.go
Labels: size/XS, lgtm, approved

#1930 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1929 Add completion support for fish and PowerShell shells
  docs/cmd/kn_completion.md
  pkg/kn/commands/completion/completion.go
  pkg/kn/commands/completion/completion_test.go
Labels: lgtm, approved, size/M, ok-to-test
