Repository knative/client, pull requests merged in 2024-04, with the labels that each got.

#1933 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1927 Populate container.SecurityContext.RunAsUser when --user flag is used
  pkg/kn/flags/podspec.go
  pkg/kn/flags/podspec_helper.go
  pkg/kn/flags/podspec_test.go
Labels: lgtm, approved, size/S

#1936 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1925 Fix `kn service wait` for already ready ksvc
  pkg/serving/v1/client.go
  pkg/serving/v1/client_test.go
Labels: kind/bug, lgtm, approved, size/S

#1937 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/test/e2e-networking-library.sh
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1939 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  vendor/knative.dev/serving/pkg/apis/serving/v1/route_lifecycle.go
  vendor/knative.dev/serving/pkg/testing/v1/route.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1940 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
