Repository knative/client, pull requests merged in 2024-11, with the labels that each got.

#1974 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1978 Fix package location for build flags
  hack/build-flags.sh
Labels: size/XS, lgtm, approved

#1972 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  go.work
  go.work.sum
  pkg/go.mod
  pkg/go.sum
Labels: lgtm, approved, size/L

#1982 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1981 Add target platform flag to build script
  hack/build.sh
Labels: lgtm, approved, size/M
