Repository knative/client, pull requests merged in 2024-07, with the labels that each got.

#1955 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#1956 Add release note template
  .github/release.yml
Labels: lgtm, approved, size/S

#1957 Remove release notes template in favor of global one
  .github/release.yml
Labels: lgtm, approved, size/S

#1958 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  test/common.sh
  vendor/knative.dev/eventing/pkg/apis/eventing/v1alpha1/eventpolicy_validation.go
  vendor/modules.txt
Labels: lgtm, approved, size/M

#1960 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
