Repository knative/client, pull requests merged in 2025-01, with the labels that each got.

#1984 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1980 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  go.work.sum
  pkg/go.mod
  pkg/go.sum
Labels: lgtm, approved, size/L

#1986 Checking parts of the message to combat flaky tests
  pkg/output/tui/spinner_test.go
Labels: lgtm, approved, size/M

#1988 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  go.work.sum
  pkg/go.mod
  pkg/go.sum
Labels: lgtm, approved, size/S

#1990 Remove dependency on deprecated client-pkg
  go.mod
  go.sum
  go.work.sum
  pkg/go.mod
  pkg/go.sum
  pkg/plugin/manager.go
Labels: lgtm, approved, size/S

#1991 Refactor PingSourve to v1 API version
  pkg/commands/completion_helper.go
  pkg/commands/completion_helper_test.go
  pkg/commands/flags/sink_test.go
  pkg/commands/source/list_test.go
  pkg/commands/source/ping/create.go
  pkg/commands/source/ping/create_test.go
  pkg/commands/source/ping/delete_test.go
  pkg/commands/source/ping/describe.go
  pkg/commands/source/ping/describe_test.go
  pkg/commands/source/ping/flags.go
  pkg/commands/source/ping/list_test.go
  pkg/commands/source/ping/ping.go
  pkg/commands/source/ping/ping_test.go
  pkg/commands/source/ping/update.go
  pkg/commands/source/ping/update_test.go
  pkg/commands/types.go
  pkg/commands/types_test.go
  pkg/dynamic/client_test.go
  pkg/dynamic/fake/fake.go
  pkg/sources/common.go
  pkg/sources/common_test.go
  pkg/sources/v1/client.go
  pkg/sources/v1/ping_client.go
  pkg/sources/v1/ping_client_mock.go
  pkg/sources/v1/ping_client_mock_test.go
  pkg/sources/v1/ping_client_test.go
  pkg/sources/v1beta2/client.go
Labels: lgtm, approved, size/L

#1992 [main] Upgrade to latest dependencies
  go.mod
  go.sum
  pkg/go.mod
  pkg/go.sum
Labels: lgtm, approved, size/S

#1993 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#1994 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review
